import type { Dil } from '../i18n/ui';
import { ELIFBA_HARFLERI } from './elifba-verisi';
import { EZBER_LISTESI } from './ezber-verisi';
import { QUIZ_SORULARI } from './quiz-verisi';
export const uc = (tr: string, fr: string, en: string): Record<Dil, string> => ({ tr, fr, en });
export type Etkinlik = { id: string; alan: 'harf' | 'ezber' | 'bilgi' | 'hayat'; baslik: Record<Dil,string>; metin: Record<Dil,string>; soru: Record<Dil,string>; aciklama: Record<Dil,string>; secenek?: Record<Dil,string>[]; dogru?: number; arapca?: string; ses?: string; kaynak: string; dakika: number };
const diyanet = 'https://egitimhizmetleri.diyanet.gov.tr/sayfa/1034';
const hayat = (id: string, baslik: Record<Dil,string>, soru: Record<Dil,string>, secenek: Record<Dil,string>[], aciklama: Record<Dil,string>): Etkinlik => ({id:`hayat-${id}`,alan:'hayat',baslik,metin:uc('Bu hayalî durumu birlikte düşünelim.','Réfléchissons ensemble à cette situation imaginaire.','Let’s think about this imaginary situation together.'),soru,secenek,dogru:0,aciklama,kaynak:diyanet,dakika:3});
export const HAYAT_ETKINLIKLERI = [
 hayat('davet',uc('Oyuna davet','Inviter à jouer','Invite someone to play'),uc('Yeni gelen arkadaşın yalnız oturuyor. Ne yapabilirsin ?','Un nouvel élève est assis seul. Que peux-tu faire ?','A new pupil is sitting alone. What can you do?'),[uc('Yanına gidip oyuna davet ederim.','Je vais lui proposer de jouer.','I go over and invite them to play.'),uc('Diğerlerinin çağırmasını beklerim.','J’attends que les autres l’invitent.','I wait for someone else to invite them.')],uc('Nazik bir davet, arkadaşının kendini gruba ait hissetmesine yardımcı olabilir. Evde bir davet cümlesi deneyin.','Une invitation gentille peut aider ton camarade à se sentir accueilli. Essayez une phrase ensemble.','A kind invitation can help your classmate feel welcome. Practise an invitation together.')),
 hayat('hata',uc('Hata yapınca','Quand on se trompe','When we make a mistake'),uc('Arkadaşın bir harfi karıştırdı. Nasıl yardımcı olursun?','Ton camarade confond une lettre. Comment l’aider ?','Your friend mixes up a letter. How can you help?'),[uc('Birlikte tekrar dinlemeyi öneririm.','Je propose de réécouter ensemble.','I suggest listening together again.'),uc('Gülüp hemen cevabı söylerim.','Je ris et je donne la réponse.','I laugh and tell them the answer.')],uc('Hata, nerede desteğe ihtiyaç olduğunu gösterir. Gülmek yerine zaman ver; emin değilsen hocaya sor.','Une erreur montre ce qui a besoin d’être travaillé. Laisse du temps ; si tu hésites, demande à l’enseignant.','A mistake shows what needs practice. Give your friend time; ask the teacher if you are unsure.')),
 hayat('emanet',uc('Ödünç aldığım kitap','Le livre emprunté','The borrowed book'),uc('Ödünç aldığın kitabın sayfası kazayla yırtıldı. Ne yaparsın?','Une page du livre emprunté se déchire par accident. Que fais-tu ?','A page in a borrowed book tears by accident. What do you do?'),[uc('Sahibine dürüstçe anlatır, onarmak için yardım isterim.','Je l’explique honnêtement et je propose de le réparer.','I explain honestly and offer to help repair it.'),uc('Fark edilmesin diye kitabı saklarım.','Je cache le livre pour éviter qu’on le voie.','I hide the book so nobody notices.')],uc('Sorumluluk almak, olanı saklamadan anlatmayı ve çözüm aramayı içerir. Bir özür ve çözüm cümlesi kur.','Prendre ses responsabilités, c’est expliquer et chercher une solution. Formule une excuse et une proposition.','Taking responsibility means explaining what happened and looking for a solution. Practise an apology and an offer to help.')),
 hayat('su',uc('Suyu koruyalım','Préservons l’eau','Save water'),uc('Ellerini yıkadıktan sonra musluk açık kaldı. Ne yaparsın?','Le robinet reste ouvert après le lavage des mains. Que fais-tu ?','The tap is still running after you wash your hands. What do you do?'),[uc('Musluğu kapatırım.','Je ferme le robinet.','I turn off the tap.'),uc('Başkasının kapatmasını beklerim.','J’attends que quelqu’un le ferme.','I wait for someone else to turn it off.')],uc('Küçük bir davranışla ortak kaynaklarımızı koruyabiliriz. Evde suyu koruyan başka bir davranış düşün.','Un petit geste protège nos ressources communes. Trouve un autre geste pour économiser l’eau à la maison.','A small action can protect shared resources. Think of another way to save water at home.')),
 hayat('dinle',uc('Sıra ile konuşalım','Parlons à tour de rôle','Take turns speaking'),uc('Bir arkadaşın konuşurken senin de söyleyeceğin var. Ne yaparsın?','Tu veux parler pendant qu’un camarade parle. Que fais-tu ?','You want to speak while a classmate is talking. What do you do?'),[uc('Dinler, bitirince söz isterim.','J’écoute puis je demande la parole.','I listen, then ask for a turn.'),uc('Sesimi yükseltip araya girerim.','Je parle plus fort pour l’interrompre.','I speak louder to interrupt.')],uc('Dinlemek, karşımızdakine değer verdiğimizi gösterir. Bir dakika sırayla konuşmayı deneyin.','Écouter montre que l’autre compte. Essayez de parler chacun votre tour pendant une minute.','Listening shows that the other person matters. Try taking turns for one minute.')),
 hayat('tesekkur',uc('Teşekkür ve emek','Merci pour ton aide','Thank you for helping'),uc('Birisi çantanı hazırlamana yardım etti. Ne söyleyebilirsin?','Quelqu’un t’aide à préparer ton sac. Que peux-tu dire ?','Someone helps you pack your bag. What could you say?'),[uc('Yardımın için teşekkür ederim.','Merci pour ton aide.','Thank you for helping me.'),uc('Zaten bunu yapmak zorundaydın.','Tu devais le faire de toute façon.','You had to do it anyway.')],uc('Teşekkür ederken hangi yardımı fark ettiğini söyle. Bugün emek veren birine teşekkür et.','Nomme l’aide que tu as appréciée. Remercie quelqu’un pour un effort aujourd’hui.','Say what help you appreciated. Thank someone for an effort today.')),
 hayat('guven',uc('İzin isteyelim','Demandons la permission','Ask permission'),uc('Arkadaşının fotoğrafını paylaşmak istiyorsun. İlk adımın ne olur?','Tu voudrais partager une photo de ton camarade. Quelle est la première étape ?','You want to share a photo of your friend. What is the first step?'),[uc('Paylaşmadan önce bir yetişkine danışır, izin isterim.','Je demande conseil à un adulte et l’autorisation avant de partager.','I ask a trusted adult and get permission before sharing.'),uc('Önce paylaşır, sonra sorarım.','Je partage puis je demande.','I share it first and ask later.')],uc('Başkalarının özel alanına saygı gösteririz. Bu etkinlik için fotoğraf çekmen veya yüklemen gerekmiyor.','Nous respectons la vie privée des autres. Tu n’as pas besoin de prendre ou d’envoyer une photo pour cette activité.','We respect other people’s privacy. You do not need to take or upload a photo for this activity.')),
 hayat('baris',uc('Anlaşmazlığı çözelim','Résolvons un désaccord','Resolve a disagreement'),uc('Aynı kalemi kullanmak istiyorsunuz. Ne önerebilirsin?','Vous voulez utiliser le même crayon. Que proposes-tu ?','You both want to use the same pencil. What could you suggest?'),[uc('Sırayla kullanalım.','Utilisons-le chacun notre tour.','Let’s take turns.'),uc('Kalemi arkadaşımın elinden alırım.','Je prends le crayon de force.','I grab the pencil.')],uc('Sakinleşmek ve sırayla kullanmak çözüm olabilir. Çözemediğinizde güvendiğiniz bir yetişkinden yardım isteyin.','Se calmer et partager à tour de rôle peut aider. Si besoin, demandez l’aide d’un adulte de confiance.','Calming down and taking turns can help. Ask a trusted adult for help if you cannot resolve it.')),
];
export const ETKINLIKLER: Etkinlik[] = [
 ...ELIFBA_HARFLERI.map((h):Etkinlik=>({id:`harf-${h.id}`,alan:'harf',baslik:h.ad,metin:uc('Harf sesini dinle. Şekline ve noktalarına bak.','Écoute le son. Observe la forme et les points.','Listen to the sound. Look at its shape and dots.'),soru:uc('Dinlediğin harfi bul.','Retrouve la lettre entendue.','Find the letter you heard.'),aciklama:uc('Cevabı kontrol ettikten sonra harfi parmağınla havaya çiz.','Après avoir vérifié, trace la lettre dans l’air avec ton doigt.','After checking, trace the letter in the air with your finger.'),arapca:h.harf,ses:`/media/ses/elifba/${h.id}.mp3`,kaynak:'https://kuran.diyanet.gov.tr/elifba/',dakika:2})),
 ...EZBER_LISTESI.map((e):Etkinlik=>({id:`ezber-${e.id}`,alan:'ezber',baslik:e.ad,metin:e.anlam,soru:uc('Metni açmadan hatırladığın bölümü oku. Sonra kaydı ve metni kontrol et.','Récite le passage dont tu te souviens sans regarder. Vérifie ensuite avec le texte et l’enregistrement.','Recall a passage without looking. Then check the text and recording.'),aciklama:uc('Bugün yalnız hocanın verdiği kısa bölümü çalışabilirsin. Okuyuşunu hocana dinlet; buradaki öz değerlendirme bir yeterlilik onayı değildir.','Travaille seulement le court passage donné par l’enseignant. Fais-lui écouter ta récitation ; cette auto-évaluation n’est pas une validation de maîtrise.','You can practise just the short passage your teacher assigned. Let your teacher hear your recitation; this self-assessment does not certify mastery.'),arapca:e.arapca,ses:e.sesUrl,kaynak:'https://kuran.diyanet.gov.tr/',dakika:4})),
 ...QUIZ_SORULARI.map((q):Etkinlik=>({id:`bilgi-${q.id}`,alan:'bilgi',baslik:q.soru,metin:uc('Önce kendin düşün, sonra cevabını kontrol et.','Réfléchis d’abord, puis vérifie ta réponse.','Think first, then check your answer.'),soru:q.soru,secenek:q.secenekler.tr.map((_,i)=>uc(q.secenekler.tr[i],q.secenekler.fr[i],q.secenekler.en[i])),dogru:q.dogruCevapIndex,aciklama:q.aciklama,kaynak:q.id==='peygamberimiz-dogum'?'https://islamansiklopedisi.org.tr/muhammed':diyanet,dakika:2})),
 ...HAYAT_ETKINLIKLERI,
];
export const VELI_REHBERLERI = [
 [uc('Kur’an okumayı bilmiyorum; nasıl yardım ederim?','Je ne sais pas lire le Coran : comment aider ?','I cannot read the Quran. How can I help?'),uc('Birlikte kısa bir kayıt dinleyin. Çocuğunuzdan öğrendiği bir şeyi size göstermesini isteyin. Telaffuzu tahmin ederek düzeltmeyin; zorlandığı harfi hocasına sormak üzere not edin.','Écoutez un court enregistrement ensemble. Demandez à votre enfant de vous montrer un apprentissage. Ne devinez pas la prononciation ; notez la lettre à revoir avec l’enseignant.','Listen to a short recording together. Ask your child to show you something they learned. Do not guess pronunciation corrections; note the letter to discuss with the teacher.')],
 [uc('Evde kısa çalışma düzeni','Une petite routine à la maison','A short home routine'),uc('Birlikte uygun bir zaman seçin. Önce tek hedef belirleyin, kısa bir örnek dinleyin, metne bakmadan hatırlayın. Yorulduğunda ara verin. Buradaki süreler öneridir; tamamlamak için acele etmeyin.','Choisissez ensemble un moment. Fixez un seul objectif, écoutez un exemple, puis rappelez-le sans regarder. Faites une pause en cas de fatigue. Les durées sont indicatives.','Choose a time together. Set one goal, listen to an example, then recall it without looking. Take a break when tired. Times shown here are suggestions, not deadlines.')],
 [uc('Hata yaptığında ne söyleyebilirim?','Que dire après une erreur ?','What can I say after a mistake?'),uc('“Bu kısmı tekrar deneyelim; nerede karıştı?” deyin. Önce çocuğun düşünmesine zaman verin, sonra küçük bir ipucu sunun. Gayretini ve kullandığı yöntemi fark edin; kardeşleriyle karşılaştırmayın.','Dites : « Réessayons ce passage ; où était la difficulté ? » Laissez le temps de réfléchir puis donnez un petit indice. Valorisez l’effort et la méthode sans comparer les enfants.','Try: “Let’s try that part again. Where did it get tricky?” Allow thinking time, then offer a small hint. Notice effort and strategy without comparing siblings.')],
 [uc('İki dilde öğrenmek','Apprendre avec deux langues','Learning with two languages'),uc('Açıklamayı çocuğunuzun rahat anladığı dilde konuşun. Bir kelimenin Türkçesini ve Fransızcasını birlikte karşılaştırın. Arapça tilaveti resmî kayıttan dinleyin; anlam çevirisiyle tilaveti birbirinden ayırın.','Discutez du sens dans la langue la mieux comprise. Comparez ensemble un mot en turc et en français. Écoutez la récitation arabe officielle ; distinguez le sens traduit de la récitation.','Discuss the meaning in the language your child understands best. Compare a Turkish and a French word together. Listen to official Arabic recitation; distinguish the translation from the recitation.')],
 [uc('Tekrarı günlere yaymak','Répartir les révisions','Spread out practice'),uc('Aynı şeyi bir oturuşta çok kez tekrarlamak yerine başka bir gün yeniden hatırlamayı deneyin. Portalın tekrar tarihleri yardımcı bir öneridir. Çocuğun yorgunluğuna ve hocanın yönlendirmesine göre uyarlayın.','Revenez sur l’apprentissage un autre jour plutôt que de tout répéter en une seule séance. Les dates proposées par le portail sont des repères à adapter avec l’enseignant.','Try recalling learning on another day instead of repeating everything in one sitting. Portal review dates are suggestions to adapt to your child and the teacher’s guidance.')],
 [uc('Derse hazır gelmek','Préparer le cours','Get ready for class'),uc('Bu haftanın ders ve ödevini portalda açın. İstenen kitap, defter ve malzemeyi birlikte kontrol edin. Kitap seçiminize cevap verin. Gelemeyeceğiniz gün için portalın bildirim formunu kullanın.','Consultez les cours et devoirs de la semaine. Vérifiez ensemble les livres, cahiers et le matériel demandé. Répondez au choix du livre. Signalez une absence via le formulaire du portail.','Open this week’s lessons and homework. Check the requested books, notebook and materials together. Respond to the book choice. Use the portal form to report an absence.')],
 [uc('Hocaya yararlı bir mesaj','Un message utile à l’enseignant','A useful message to the teacher'),uc('Hangi konu üzerinde, ne denediğinizi ve nerede zorlandığınızı kısaca yazın. “Harfleri iki kez dinledik; şu ikisini karıştırıyoruz” gibi somut bir örnek verin. Mesajı göndermeden önce okuyun.','Indiquez le sujet, ce que vous avez essayé et la difficulté. Donnez un exemple concret : « Nous avons réécouté ; ces deux lettres restent difficiles. » Relisez avant d’envoyer.','Briefly name the topic, what you tried and the difficulty. Give an example: “We listened again but still mix up these two letters.” Review before sending.')],
 [uc('Ekran dışında birlikte öğrenmek','Apprendre ensemble sans écran','Learn together away from the screen'),uc('Bir davranışı canlandırın, bir harfi kâğıda çizin veya çocuğunuzdan size bir konuyu anlatmasını isteyin. Fotoğraf ya da ses kaydı göndermek gerekmez. Çalışma sonunda “Bugün ne işine yaradı?” diye sorun.','Jouez une situation, dessinez une lettre sur papier ou demandez une explication. Aucune photo ni aucun enregistrement à envoyer. Terminez par : « Qu’est-ce qui t’a aidé aujourd’hui ? »','Act out a situation, draw a letter on paper or ask your child to explain a topic. No photo or recording is needed. Finish with: “What helped you today?”')],
];
