import type { Dil } from './ui';

type Ders = { baslik: string; giris: string; konular: [string, string, string]; uygulama: string };
type Rehber = {
  yol: string; aciklama: string; uygulama: string; kaynak: string; sesler: string;
  rutin: string; rutinMetni: string; adimlar: [string, string, string];
  kitaplar: string; kitapNotu: string; kutuphane: string; sorular: string;
  sss: [string, string][]; dersler: Ders[];
};

// Ulu Camii'nin öğrenme önerisi; resmî bir müfredatın veya sertifikanın yerine geçmez.
// Kaynaklar ve ders bağlantıları MuhtediEgitimi.astro içinde görünür olarak sunulur.
export const EGITIM_REHBERI: Record<Dil, Rehber> = {
  tr: {
    yol: 'Adım adım öğrenme yolu',
    aciklama: 'Bu sıra, Ulu Camii’nin başlangıç için hazırladığı bir çalışma önerisidir. Bildiğiniz bölümleri tekrar için kullanabilir, zorlandığınız konuları din görevlisiyle birlikte çalışabilirsiniz. Her başlığı açarak konuları ve küçük uygulamayı görün.',
    uygulama: 'Kendiniz deneyin', kaynak: 'Okuyun ve inceleyin', sesler: 'Bütün sesli dersler',
    rutin: 'Kısa ama düzenli bir çalışma', rutinMetni: 'Örneğin günde 15 dakika öğrenmeye zaman ayırın. Bu, ders çalışma önerisidir; ibadetlerin vakit ve yükümlülüklerinden ayrıdır.',
    adimlar: ['5 dakika: Bir konuyu okuyun; anlamadığınız kelimeyi not edin.', '5 dakika: Kısa bir kaydı dinleyin, durdurun ve tekrar edin.', '5 dakika: Öğrendiğinizi anlatın veya uygulayın; bir sonraki görüşme için sorunuzu yazın.'],
    kitaplar: 'Yanınızda bulunacak kaynaklar', kitapNotu: 'Aşağıdaki ücretsiz PDF’ler Diyanet’in Fransızca yayınlarıdır. Diğer dillerdeki kitaplara kütüphanemizden ulaşabilirsiniz.', kutuphane: 'Çok dilli Diyanet kütüphanesi', sorular: 'Başlarken aklınıza gelebilir',
    sss: [
      ['Önce bütün Arap harflerini öğrenmeli miyim?', 'Temel inanç bilgilerini, temizliği ve namazı öğrenmeye harf çalışmanızla birlikte başlayabilirsiniz. Okuyuş için kısa kayıtları tekrar edin; namazı öğrenirken din görevlisinden uygulamalı destek alın.'],
      ['Kitabım veya üyeliğim yok; derslere erişebilir miyim?', 'Evet. Bu rehber, 73 sesli ders ve kaynak bağlantıları herkese açıktır. Kitaptaki karekodlar da aynı dersleri açmaya devam eder.'],
      ['Sesli derslerde nasıl çalışmalıyım?', 'Bir harfe veya satıra dokunun. Dinledikten sonra kendiniz tekrar edin; gerektiğinde yavaşlatma ve tekrar seçeneklerini kullanın. Kayıtla çalışmaya ek olarak okuyuşunuzu bir öğreticiye dinletin.'],
      ['Kendi durumuma ilişkin dinî sorumu kime sorabilirim?', 'Caminin iletişim sayfasından din görevlisine ulaşabilirsiniz. Aile, çalışma hayatı veya ibadetle ilgili sorunuzu kendi şartlarınızla birlikte sorun; bir başkasına verilen cevabı kendinize doğrudan uygulamayın.'],
    ],
    dersler: [
      { baslik: 'İlk adım: İslâm ve kelime-i şehâdet', giris: 'Önce inandığınız şeyi anlamaya odaklanın. Sorularınızı rahatça sorabileceğiniz bir öğrenme ilişkisi kurun.', konular: ['Kelime-i şehâdet, Allah’ın birliğine ve Hz. Muhammed’in O’nun kulu ve elçisi olduğuna tanıklığı ifade eder.', 'İman, ibadet ve güzel ahlâk kavramlarını birbirinden ayırarak tanıyın; İslâm’ı yalnızca bir uygulamalar listesi olarak öğrenmeyin.', 'İslâm’ı tanıma rehberini okuyun; bilmediğiniz terimleri ve öğrenmek istediğiniz konuları bir deftere yazın.'], uygulama: 'Şehâdetin anlamını kendi cümlelerinizle açıklayın ve din görevlisine sormak istediğiniz üç soruyu seçin.' },
      { baslik: 'İmanın esasları ve anlamı', giris: 'İnancın temel kavramlarını ezberin yanında anlamlarıyla öğrenin.', konular: ['Allah’a, meleklere, kitaplara, peygamberlere, âhiret gününe ve kadere iman başlıklarını tanıyın.', 'Kur’an ile Hz. Peygamber’in örnekliği hakkında giriş metinlerini okuyun; bilmediğiniz bir kavramın açıklamasını güvenilir kaynağından arayın.', 'İman konularını günlük hayattaki sorumluluk, ümit ve davranışlarınızla birlikte düşünün; anlamadığınız konuyu geçiştirmeyin.'], uygulama: 'Her iman esası için bir kısa açıklama yazın. Açıklayamadığınız başlığı sonraki görüşmenize taşıyın.' },
      { baslik: 'Temizlik, abdest ve gusül', giris: 'İbadete hazırlığı uygulayarak öğrenin. Resimli rehber, hareketleri sırayla takip etmenize yardımcı olur.', konular: ['Beden, elbise ve ibadet yerinin temizliği ile abdestin farklı konular olduğunu öğrenin.', 'Abdestte yüzün ve dirseklerle birlikte kolların yıkanması, başın mesh edilmesi ve topuklarla birlikte ayakların yıkanmasını uygulamalı çalışın; tam sıra ve sünnetler için rehberi izleyin.', 'Abdesti bozan durumlar, guslün gerektiği hâller ve teyemmüm konularını kaynaktan okuyun; kendi durumunuzda tereddüt ettiğiniz noktayı sorun.'], uygulama: 'Resimli rehberle bir abdest uygulaması yapın; sırayı ve eksik bıraktığınız yeri bir öğreticiyle kontrol edin.' },
      { baslik: 'Namazı adım adım öğrenme', giris: 'Hazırlık, hareketler ve okuyuşları birlikte çalışın. Bir öğreticiyle uygulama yapmak öğrenmeyi kolaylaştırır.', konular: ['Beş vakit namazı, vakitlerini, kıbleyi, niyeti ve namaza hazırlık şartlarını tanıyın. Güncel yerel vakitleri sitemizin ana sayfasından takip edin.', 'Kıyam, rükû, secde ve oturuşu resimli namaz rehberiyle çalışın; rekât kavramını ve hareketlerin sırasını öğrenin.', 'Fâtiha, kısa sûreler ve namaz dualarını küçük parçalarla dinleyin. Hareket ve okuyuşları birleştiren uygulamanızı din görevlisiyle gözden geçirin.'], uygulama: 'Bir rekâtın hareket sırasını rehberden takip ederek gösterin; hangi bölümde ne okunduğunu işaretleyin.' },
      { baslik: 'Arap harflerinden Kur’an okumaya', giris: 'Harfin adı ile harekeli okunuşu farklıdır. Sesli örnekleri görerek ve tekrar ederek bu ayrımı yerleştirin.', konular: ['Alfabeden başlayın; birbirine benzeyen harflerin noktalarına ve şekillerine dikkat edin.', 'Fetha (üstün), kesra (esre) ve damme (ötre) derslerini sırayla çalışın. Her kareyi dinleyip aynı sesi tekrar edin.', 'Kısa–uzun okuma karşılaştırmalarından sonra cezim, şedde ve birleştirme alıştırmalarına ilerleyin; bir başlık zor gelirse önceki derse dönün.'], uygulama: 'Beş harf seçin; önce adlarını, sonra üç harekeyle seslerini dinleyin. Karıştırdığınız iki harfi ayrıca tekrar edin.' },
      { baslik: 'Sûreler, dualar ve anlamları', giris: 'Kısa bir bölümü doğru okumak ve anlamını öğrenmek, çalışma için somut bir başlangıçtır.', konular: ['Fâtiha’yı satır satır dinleyin; her satırdan sonra durup tekrar edin ve sayfadaki Fransızca anlamını okuyun.', 'İhlâs, Felak ve Nâs gibi kısa sûrelerle çalışmanızı sürdürün. Okuyuşunuzu bir öğreticiyle kontrol edin.', 'Sübhâneke, Tahiyyât, Salli ve Bârik dualarını ilgili seslerden çalışın; nerede okunduklarını namaz rehberinden takip edin.'], uygulama: 'Bir satırı metne bakarak üç kez tekrar edin; ardından metne bakmadan deneyin. Takıldığınız yere dönün.' },
      { baslik: 'Oruç, paylaşma ve diğer ibadetler', giris: 'İbadetlerin amaçlarını ve temel kavramlarını tanıyın; ayrıntıları ihtiyaç duyduğunuzda kaynaktan çalışın.', konular: ['Ramazan, oruç, sahur ve iftar kavramlarını öğrenin; orucun şartları ve mazeretleri için ibadet rehberini okuyun.', 'Zekât ile gönüllü sadakanın farkını tanıyın. Kişisel yükümlülük ve hesap sorularını kendi şartlarınızla birlikte din görevlisine sorun.', 'Hac ve umrenin temel anlamını, birbirinden farkını ve ibadetlerin hayat içindeki yerini öğrenin.'], uygulama: 'Oruç, zekât, sadaka, hac ve umre için birer cümlelik sözlük hazırlayın; bilmediğiniz ayrıntıları soru olarak ekleyin.' },
      { baslik: 'Peygamberimizin örnekliği ve günlük hayat', giris: 'Öğrendiklerinizi aile, komşuluk, iş ve toplum hayatınızla ilişkilendirin.', konular: ['Hz. Muhammed’in hayatını güvenilir bir giriş kitabından okuyun; doğruluk, merhamet ve güvenilirlikle ilgili örnekleri belirleyin.', 'Anne babaya ve komşulara iyi davranma, verilen sözü tutma ve başkalarının hakkını gözetme konularını düşünün.', 'Farklı inançtaki yakınlarınızla iletişim veya yeni alışkanlıklar hakkında zorlandığınız noktaları din görevlisiyle konuşun; sorularınızı tek başınıza taşımayın.'], uygulama: 'Bu hafta uygulayabileceğiniz bir iyilik seçin. Haftanın sonunda öğrendiğiniz bir bilgiyi ve yaşadığınız bir soruyu not edin.' },
    ],
  },
  fr: {
    yol: 'Un parcours, étape par étape', aciklama: 'Ce parcours est une proposition de travail d’Ulu Camii pour débuter. Révisez les sujets déjà connus et étudiez les difficultés avec l’imam. Ouvrez chaque étape pour découvrir les points à travailler et un exercice.',
    uygulama: 'À vous de pratiquer', kaynak: 'Lire et approfondir', sesler: 'Tous les cours audio',
    rutin: 'Un peu chaque jour', rutinMetni: 'Vous pouvez, par exemple, consacrer 15 minutes par jour à l’apprentissage. Il s’agit d’un conseil d’étude, distinct des horaires et des obligations des actes d’adoration.',
    adimlar: ['5 minutes : lisez un sujet et notez un mot nouveau.', '5 minutes : écoutez un court extrait, faites une pause et répétez.', '5 minutes : expliquez ou pratiquez ce que vous avez appris ; notez une question pour votre prochaine rencontre.'],
    kitaplar: 'Des ressources pour vous accompagner', kitapNotu: 'Ces PDF gratuits sont des publications officielles de la Diyanet en français. Notre bibliothèque propose aussi des livres dans d’autres langues.', kutuphane: 'Bibliothèque multilingue de la Diyanet', sorular: 'Vos premières questions',
    sss: [
      ['Faut-il d’abord maîtriser tout l’alphabet arabe ?', 'Vous pouvez apprendre les bases de la foi, la purification et la prière en parallèle avec les lettres. Répétez de courts enregistrements et demandez une démonstration à l’imam pour apprendre la prière.'],
      ['Puis-je accéder aux cours sans livre ni compte ?', 'Oui. Ce guide, les 73 cours audio et les liens vers les ressources sont ouverts à tous. Les codes QR du livre continuent à ouvrir les mêmes cours.'],
      ['Comment travailler avec les enregistrements ?', 'Touchez une lettre ou une ligne. Écoutez, puis répétez vous-même ; utilisez au besoin les options de vitesse et de répétition. Faites également vérifier votre lecture par une personne qui enseigne.'],
      ['À qui poser une question sur ma situation ?', 'La page de contact vous permet de joindre l’imam. Expliquez votre situation pour les questions de famille, de travail ou de pratique religieuse ; une réponse donnée à quelqu’un d’autre ne s’applique pas automatiquement à vous.'],
    ],
    dersler: [
      { baslik: 'Premiers pas : l’islam et la chahada', giris: 'Commencez par comprendre votre foi et trouvez un cadre où vous pouvez poser vos questions.', konular: ['La chahada exprime le témoignage de l’unicité d’Allah et de la mission de Muhammad, Son serviteur et messager.', 'Découvrez les notions de foi, d’adoration et de bon comportement, au-delà d’une simple liste de pratiques.', 'Lisez le guide de découverte de l’islam et notez les mots et les sujets que vous souhaitez comprendre.'], uygulama: 'Expliquez le sens de la chahada avec vos propres mots et choisissez trois questions à poser à l’imam.' },
      { baslik: 'Comprendre les fondements de la foi', giris: 'Apprenez les notions de base en cherchant leur sens, en plus de les retenir.', konular: ['Découvrez la foi en Allah, en Ses anges, en Ses livres, en Ses prophètes, au Jour dernier et au destin.', 'Lisez une introduction au Coran et à l’exemple du Prophète ; vérifiez les termes nouveaux dans une source fiable.', 'Reliez vos questions de foi à la responsabilité, à l’espérance et à vos actions quotidiennes ; gardez les questions encore ouvertes.'], uygulama: 'Écrivez une courte explication de chaque fondement. Apportez à votre prochaine rencontre les points que vous ne pouvez pas encore expliquer.' },
      { baslik: 'Propreté, ablutions et grande ablution', giris: 'Apprenez la préparation à la prière par la pratique, avec un guide illustré.', konular: ['Distinguez la propreté du corps, des vêtements et du lieu de prière des ablutions rituelles.', 'Travaillez le lavage du visage, des bras avec les coudes et des pieds avec les chevilles, ainsi que le passage des mains humides sur la tête. Suivez le guide pour l’ordre complet et les pratiques recommandées.', 'Étudiez ce qui annule les ablutions, les situations nécessitant le ghousl et le tayammoum ; posez les questions liées à votre situation.'], uygulama: 'Faites une démonstration avec le guide illustré et vérifiez les étapes avec une personne qui enseigne.' },
      { baslik: 'Apprendre la prière pas à pas', giris: 'Associez préparation, gestes et récitations, avec une démonstration accompagnée.', konular: ['Découvrez les cinq prières quotidiennes, leurs horaires, la qibla, l’intention et les conditions de préparation. Les horaires locaux sont sur notre page d’accueil.', 'Travaillez la station debout, l’inclinaison, la prosternation et la position assise avec le guide illustré ; apprenez ce qu’est une rak‘a.', 'Écoutez la Fâtiha, les courtes sourates et les invocations par petits passages. Revoyez avec l’imam la coordination des gestes et des paroles.'], uygulama: 'Montrez l’ordre des gestes d’une rak‘a à l’aide du guide et repérez ce qui se récite à chaque étape.' },
      { baslik: 'Des lettres arabes à la lecture du Coran', giris: 'Le nom d’une lettre et son son avec une voyelle sont différents. Regardez, écoutez et répétez.', konular: ['Commencez par l’alphabet et observez les points et les formes qui distinguent les lettres proches.', 'Travaillez successivement la fatḥa, la kasra et la ḍamma. Écoutez chaque case, puis reproduisez le son.', 'Comparez les sons courts et longs, puis poursuivez avec le soukoun, la chadda et les exercices de liaison. Revenez au cours précédent si nécessaire.'], uygulama: 'Choisissez cinq lettres ; écoutez leur nom, puis leur son avec les trois voyelles. Reprenez les deux lettres que vous confondez.' },
      { baslik: 'Sourates, invocations et compréhension', giris: 'Un court passage bien travaillé et compris constitue un objectif concret.', konular: ['Écoutez la Fâtiha ligne par ligne ; arrêtez-vous pour répéter et lisez la traduction française affichée.', 'Continuez avec de courtes sourates comme al-Ikhlâs, al-Falaq et an-Nâs. Faites vérifier votre lecture.', 'Travaillez les invocations Soubhânaka, Tachahhoud, Salli et Bârik ; consultez le guide de prière pour savoir où elles sont récitées.'], uygulama: 'Répétez une ligne trois fois avec le texte, puis essayez sans regarder. Revenez au passage qui vous pose difficulté.' },
      { baslik: 'Jeûne, partage et autres adorations', giris: 'Découvrez les objectifs et le vocabulaire de base ; approfondissez les règles selon vos besoins.', konular: ['Apprenez les notions de Ramadan, de jeûne, de souhour et d’iftar ; consultez le guide pour les conditions et les dispenses.', 'Distinguez la zakât de l’aumône volontaire. Posez vos questions de calcul et d’obligation personnelle à l’imam en précisant votre situation.', 'Découvrez le sens du hajj et de la ‘omra, leur différence et la place des adorations dans la vie.'], uygulama: 'Préparez un petit glossaire : jeûne, zakât, aumône, hajj et ‘omra. Ajoutez une question pour chaque point encore inconnu.' },
      { baslik: 'L’exemple du Prophète et la vie quotidienne', giris: 'Reliez votre apprentissage à la famille, au voisinage, au travail et à la société.', konular: ['Lisez une introduction fiable à la vie du Prophète Muhammad et relevez des exemples de sincérité, de compassion et de confiance.', 'Réfléchissez à la bonté envers les parents et les voisins, au respect des engagements et des droits d’autrui.', 'Parlez avec l’imam des difficultés liées à vos nouvelles habitudes ou aux relations avec des proches d’une autre conviction.'], uygulama: 'Choisissez une bonne action à réaliser cette semaine. À la fin, notez une chose apprise et une question rencontrée.' },
    ],
  },
  en: {
    yol: 'A step-by-step learning path', aciklama: 'This is Ulu Camii’s suggested starting route. Revisit familiar topics and work through difficulties with the imam. Open each step for study points and a small exercise.', uygulama: 'Try it yourself', kaynak: 'Read and explore', sesler: 'All audio lessons',
    rutin: 'A little, regularly', rutinMetni: 'For example, set aside 15 minutes a day for learning. This is a study suggestion, separate from the times and obligations of worship.', adimlar: ['5 minutes: read about one topic and note a new word.', '5 minutes: listen to a short recording, pause and repeat.', '5 minutes: explain or practise what you learned; write a question for your next meeting.'],
    kitaplar: 'Resources to keep close', kitapNotu: 'These free PDFs are official Diyanet publications in French. Our library also includes books in other languages.', kutuphane: 'Multilingual Diyanet library', sorular: 'Questions when getting started',
    sss: [
      ['Must I learn the whole Arabic alphabet first?', 'You can learn the basics of belief, purification and prayer alongside the letters. Repeat short recordings and ask the imam for practical help when learning prayer.'],
      ['Can I use the lessons without a book or account?', 'Yes. This guide, all 73 audio lessons and resource links are open to everyone. The printed QR codes continue to open the same lessons.'],
      ['How should I use the recordings?', 'Tap a letter or line, listen and repeat. Use the speed and repeat options as needed. Also ask a teacher to check your recitation.'],
      ['Who can help with a question about my situation?', 'Use our contact page to reach the imam. Explain your circumstances when asking about family, work or worship; an answer given to someone else may not apply to you.'],
    ],
    dersler: [
      { baslik: 'First steps: Islam and the shahada', giris: 'Begin by understanding your belief and finding a setting where you can ask questions.', konular: ['The shahada expresses testimony to Allah’s oneness and to Muhammad as His servant and messenger.', 'Explore belief, worship and good character as connected aspects of Islam, beyond a list of practices.', 'Read the introduction to Islam and keep a note of unfamiliar terms and subjects you want to understand.'], uygulama: 'Explain the meaning of the shahada in your own words and choose three questions to ask the imam.' },
      { baslik: 'Understanding the foundations of belief', giris: 'Learn what the key concepts mean, as well as remembering their names.', konular: ['Explore belief in Allah, His angels, His books, His prophets, the Last Day and divine decree.', 'Read an introduction to the Qur’an and the Prophet’s example; look up unfamiliar concepts in reliable sources.', 'Think about belief alongside responsibility, hope and everyday actions; keep track of questions you have not resolved.'], uygulama: 'Write a brief explanation of each foundation. Bring anything you cannot yet explain to your next meeting.' },
      { baslik: 'Cleanliness, wudu and ghusl', giris: 'Learn preparation for worship through practice with an illustrated guide.', konular: ['Distinguish bodily cleanliness, clean clothing and a clean prayer space from ritual ablution.', 'Practise washing the face, arms including elbows and feet including ankles, and wiping the head. Follow the guide for the full sequence and recommended practices.', 'Read about what breaks wudu, when ghusl is required and tayammum; ask about uncertainties in your own circumstances.'], uygulama: 'Demonstrate ablution with the illustrated guide and check the steps with a teacher.' },
      { baslik: 'Learning prayer step by step', giris: 'Study preparation, movements and recitation together, with practical guidance.', konular: ['Learn about the five daily prayers, their times, the qibla, intention and preparation. Current local times appear on our home page.', 'Use the illustrated guide to practise standing, bowing, prostrating and sitting; learn what a rak‘ah is.', 'Listen to al-Fatiha, short surahs and prayer supplications in small parts. Review how movements and recitation fit together with the imam.'], uygulama: 'Use the guide to show the movement sequence of one rak‘ah and identify what is recited at each stage.' },
      { baslik: 'From Arabic letters to reading the Qur’an', giris: 'A letter’s name and its sound with a vowel are different. Look, listen and repeat.', konular: ['Start with the alphabet and notice the dots and shapes that distinguish similar letters.', 'Work through fatha, kasra and damma. Listen to each tile and repeat its sound.', 'Compare short and long sounds, then move to sukun, shadda and joined reading exercises. Return to an earlier lesson when needed.'], uygulama: 'Choose five letters. Listen to their names, then their sounds with all three vowels. Revisit two letters you confuse.' },
      { baslik: 'Surahs, supplications and their meanings', giris: 'A short passage studied carefully is a clear and achievable learning target.', konular: ['Listen to al-Fatiha line by line, pause to repeat and read the French translation on the lesson page.', 'Continue with short surahs such as al-Ikhlas, al-Falaq and an-Nas. Ask a teacher to check your reading.', 'Practise Subhanaka, Tashahhud, Salli and Barik using the recordings; refer to the prayer guide for where they are recited.'], uygulama: 'Repeat one line three times while looking at the text, then try without it. Return to any difficult part.' },
      { baslik: 'Fasting, giving and other worship', giris: 'Learn the purposes and basic vocabulary; explore detailed rules as you need them.', konular: ['Learn the terms Ramadan, fasting, suhur and iftar; consult the worship guide about conditions and exemptions.', 'Distinguish zakat from voluntary charity. Ask the imam about personal obligations and calculations with your circumstances in mind.', 'Explore the meaning of hajj and ‘umrah, their differences and the place of worship in daily life.'], uygulama: 'Make a one-sentence glossary for fasting, zakat, charity, hajj and ‘umrah. Add questions about unfamiliar details.' },
      { baslik: 'The Prophet’s example and everyday life', giris: 'Connect your learning with family, neighbours, work and community.', konular: ['Read a reliable introduction to Prophet Muhammad’s life and identify examples of honesty, compassion and trustworthiness.', 'Reflect on kindness to parents and neighbours, keeping commitments and respecting other people’s rights.', 'Discuss challenges with new habits or relatives of other beliefs with the imam; you do not have to keep your questions to yourself.'], uygulama: 'Choose one act of kindness for this week. At the end, note one thing you learned and one question that arose.' },
    ],
  },
  nl: {
    yol: 'Stap voor stap leren', aciklama: 'Dit is een voorgestelde leerroute van Ulu Camii voor beginners. Herhaal bekende onderwerpen en bespreek moeilijkheden met de imam. Open elke stap voor de leerpunten en een oefening.', uygulama: 'Zelf oefenen', kaynak: 'Lezen en verdiepen', sesler: 'Alle audiolessen',
    rutin: 'Elke dag een beetje', rutinMetni: 'Reserveer bijvoorbeeld dagelijks 15 minuten om te leren. Dit is een studieadvies, los van de tijden en verplichtingen van de aanbidding.', adimlar: ['5 minuten: lees over één onderwerp en noteer een nieuw woord.', '5 minuten: luister naar een kort fragment, pauzeer en herhaal.', '5 minuten: leg uit of oefen wat u leerde; noteer een vraag voor uw volgende gesprek.'],
    kitaplar: 'Bronnen om bij de hand te houden', kitapNotu: 'Deze gratis PDF’s zijn officiële Franstalige publicaties van Diyanet. Onze bibliotheek bevat ook boeken in andere talen.', kutuphane: 'Meertalige Diyanet-bibliotheek', sorular: 'Vragen bij de start',
    sss: [
      ['Moet ik eerst het hele Arabische alfabet kennen?', 'U kunt de grondslagen van het geloof, reiniging en gebed tegelijk met de letters leren. Herhaal korte opnamen en vraag de imam om praktische begeleiding bij het gebed.'],
      ['Kan ik zonder boek of account de lessen volgen?', 'Ja. Deze gids, alle 73 audiolessen en de bronverwijzingen zijn voor iedereen toegankelijk. De QR-codes in het boek blijven dezelfde lessen openen.'],
      ['Hoe gebruik ik de opnamen?', 'Tik op een letter of regel, luister en herhaal. Gebruik zo nodig de snelheids- en herhaalfuncties. Laat uw uitspraak ook door een docent controleren.'],
      ['Bij wie kan ik terecht met een persoonlijke vraag?', 'Via onze contactpagina kunt u de imam bereiken. Beschrijf uw omstandigheden bij vragen over familie, werk of aanbidding; een antwoord voor iemand anders geldt niet automatisch voor u.'],
    ],
    dersler: [
      { baslik: 'Eerste stappen: islam en de geloofsgetuigenis', giris: 'Begin met het begrijpen van uw geloof en zoek een omgeving waar u vragen kunt stellen.', konular: ['De shahada getuigt van de eenheid van Allah en van Muhammad als Zijn dienaar en boodschapper.', 'Verken geloof, aanbidding en goed gedrag als samenhangende aspecten van de islam, naast de afzonderlijke praktijken.', 'Lees de kennismaking met de islam en noteer onbekende begrippen en onderwerpen die u wilt begrijpen.'], uygulama: 'Leg de betekenis van de shahada in eigen woorden uit en kies drie vragen voor de imam.' },
      { baslik: 'De grondslagen van het geloof begrijpen', giris: 'Leer de betekenis van de kernbegrippen, naast het onthouden van hun namen.', konular: ['Verken het geloof in Allah, Zijn engelen, Zijn boeken, Zijn profeten, de Laatste Dag en de voorbeschikking.', 'Lees een inleiding over de Koran en het voorbeeld van de Profeet; zoek onbekende begrippen op in betrouwbare bronnen.', 'Denk na over geloof in verband met verantwoordelijkheid, hoop en dagelijkse handelingen; bewaar vragen die nog openstaan.'], uygulama: 'Schrijf bij elke grondslag een korte uitleg. Bespreek wat u nog niet kunt uitleggen tijdens uw volgende ontmoeting.' },
      { baslik: 'Reinheid, woedoe en ghoesl', giris: 'Leer de voorbereiding op de aanbidding door te oefenen met een geïllustreerde gids.', konular: ['Maak onderscheid tussen een schoon lichaam, schone kleding en gebedsplek enerzijds en de rituele wassing anderzijds.', 'Oefen het wassen van gezicht, armen inclusief ellebogen en voeten inclusief enkels, en het bestrijken van het hoofd. Volg de gids voor de volledige volgorde en aanbevolen handelingen.', 'Lees wat de woedoe verbreekt, wanneer ghoesl nodig is en wat tayammoem is; bespreek onzekerheden over uw situatie.'], uygulama: 'Doe de wassing voor met de geïllustreerde gids en controleer de stappen met een docent.' },
      { baslik: 'Het gebed stap voor stap leren', giris: 'Leer voorbereiding, bewegingen en recitatie samen, met praktische begeleiding.', konular: ['Maak kennis met de vijf dagelijkse gebeden, hun tijden, de qibla, de intentie en de voorbereiding. Actuele lokale tijden staan op onze startpagina.', 'Oefen staan, buigen, neerknielen en zitten met de geïllustreerde gids; leer wat een rak‘a is.', 'Luister in kleine delen naar al-Fatiha, korte soera’s en smeekbeden. Bespreek met de imam hoe bewegingen en recitatie samengaan.'], uygulama: 'Laat met de gids de bewegingen van één rak‘a zien en geef aan wat bij elke stap wordt gereciteerd.' },
      { baslik: 'Van Arabische letters naar Koran lezen', giris: 'De naam van een letter verschilt van de klank met een klinkerteken. Kijk, luister en herhaal.', konular: ['Begin met het alfabet en let op de punten en vormen die gelijkende letters onderscheiden.', 'Oefen achtereenvolgens fatha, kasra en damma. Luister naar elk vakje en herhaal de klank.', 'Vergelijk korte en lange klanken en ga verder met soekoen, sjadda en verbonden lezen. Keer zo nodig terug naar een eerdere les.'], uygulama: 'Kies vijf letters. Luister naar hun namen en daarna naar de klanken met drie klinkertekens. Herhaal twee letters die u verwart.' },
      { baslik: 'Soera’s, smeekbeden en betekenissen', giris: 'Een kort fragment zorgvuldig oefenen en begrijpen is een concreet leerdoel.', konular: ['Luister regel voor regel naar al-Fatiha, pauzeer om te herhalen en lees de Franse vertaling op de lespagina.', 'Ga verder met korte soera’s zoals al-Ikhlas, al-Falaq en an-Nas. Laat uw lezing controleren.', 'Oefen Subhanaka, Tasjahhoed, Salli en Barik met de opnamen; kijk in de gebedsgids waar ze worden gelezen.'], uygulama: 'Herhaal één regel drie keer met de tekst en probeer het daarna zonder te kijken. Keer terug naar het moeilijke stukje.' },
      { baslik: 'Vasten, delen en andere aanbidding', giris: 'Leer de doelen en basisbegrippen; verdiep u in regels wanneer u die nodig hebt.', konular: ['Leer de begrippen Ramadan, vasten, soehoer en iftar; raadpleeg de gids over voorwaarden en vrijstellingen.', 'Maak onderscheid tussen zakaat en vrijwillige liefdadigheid. Vraag de imam naar persoonlijke verplichtingen en berekeningen met uw omstandigheden erbij.', 'Verken de betekenis van hadj en ‘oemra, hun verschillen en de plaats van aanbidding in het leven.'], uygulama: 'Maak een kleine woordenlijst met vasten, zakaat, liefdadigheid, hadj en ‘oemra; voeg uw vragen toe.' },
      { baslik: 'Het voorbeeld van de Profeet in het dagelijks leven', giris: 'Verbind uw studie met familie, buren, werk en samenleving.', konular: ['Lees een betrouwbare inleiding over het leven van de Profeet Muhammad en zoek voorbeelden van eerlijkheid, medeleven en betrouwbaarheid.', 'Denk na over goed zijn voor ouders en buren, afspraken nakomen en de rechten van anderen respecteren.', 'Bespreek moeilijkheden met nieuwe gewoonten of familieleden met een andere overtuiging met de imam.'], uygulama: 'Kies een goede daad voor deze week. Noteer aan het eind iets wat u leerde en een vraag die opkwam.' },
    ],
  },
  de: {
    yol: 'Schritt für Schritt lernen', aciklama: 'Dieser Lernweg ist ein Vorschlag von Ulu Camii für den Einstieg. Wiederholen Sie Bekanntes und besprechen Sie Schwierigkeiten mit dem Imam. Öffnen Sie jeden Schritt für die Themen und eine kleine Übung.', uygulama: 'Selbst üben', kaynak: 'Lesen und vertiefen', sesler: 'Alle Audiokurse',
    rutin: 'Regelmäßig ein wenig lernen', rutinMetni: 'Nehmen Sie sich zum Beispiel täglich 15 Minuten zum Lernen. Dies ist ein Lernvorschlag, unabhängig von den Zeiten und Pflichten der Gottesdienste.', adimlar: ['5 Minuten: Lesen Sie ein Thema und notieren Sie ein neues Wort.', '5 Minuten: Hören Sie eine kurze Aufnahme, halten Sie an und wiederholen Sie.', '5 Minuten: Erklären oder üben Sie das Gelernte; notieren Sie eine Frage für Ihr nächstes Gespräch.'],
    kitaplar: 'Quellen zum Nachschlagen', kitapNotu: 'Diese kostenlosen PDFs sind offizielle Veröffentlichungen der Diyanet auf Französisch. Unsere Bibliothek bietet auch Bücher in anderen Sprachen.', kutuphane: 'Mehrsprachige Diyanet-Bibliothek', sorular: 'Fragen zum Einstieg',
    sss: [
      ['Muss ich zuerst das ganze arabische Alphabet lernen?', 'Sie können die Glaubensgrundlagen, Reinigung und das Gebet parallel zu den Buchstaben lernen. Wiederholen Sie kurze Aufnahmen und bitten Sie den Imam um praktische Hilfe beim Gebet.'],
      ['Kann ich die Kurse ohne Buch oder Konto nutzen?', 'Ja. Dieser Leitfaden, alle 73 Audiokurse und die Quellen sind für alle offen. Die QR-Codes im Buch öffnen weiterhin dieselben Kurse.'],
      ['Wie lerne ich mit den Aufnahmen?', 'Tippen Sie auf einen Buchstaben oder eine Zeile, hören Sie zu und wiederholen Sie. Nutzen Sie bei Bedarf die Geschwindigkeits- und Wiederholungsfunktionen. Lassen Sie Ihre Aussprache auch von einer Lehrperson prüfen.'],
      ['Wer hilft mir bei einer persönlichen Frage?', 'Über unsere Kontaktseite erreichen Sie den Imam. Beschreiben Sie Ihre Umstände bei Fragen zu Familie, Arbeit oder Gottesdienst; eine Antwort für jemand anderen gilt nicht automatisch für Sie.'],
    ],
    dersler: [
      { baslik: 'Erste Schritte: Islam und Glaubensbekenntnis', giris: 'Verstehen Sie zunächst Ihren Glauben und suchen Sie einen Rahmen, in dem Sie Fragen stellen können.', konular: ['Die Schahada bezeugt die Einheit Allahs und Muhammad als Seinen Diener und Gesandten.', 'Lernen Sie Glauben, Gottesdienst und gutes Verhalten als zusammengehörige Bereiche kennen, über eine Liste von Handlungen hinaus.', 'Lesen Sie die Einführung zum Islam und notieren Sie unbekannte Begriffe und Themen, die Sie verstehen möchten.'], uygulama: 'Erklären Sie die Bedeutung der Schahada mit eigenen Worten und wählen Sie drei Fragen für den Imam.' },
      { baslik: 'Die Glaubensgrundlagen verstehen', giris: 'Lernen Sie die Bedeutung der Grundbegriffe, nicht nur ihre Namen.', konular: ['Lernen Sie den Glauben an Allah, Seine Engel, Seine Bücher, Seine Propheten, den Jüngsten Tag und die Vorherbestimmung kennen.', 'Lesen Sie eine Einführung zum Koran und zum Vorbild des Propheten; schlagen Sie unbekannte Begriffe in verlässlichen Quellen nach.', 'Denken Sie über Glauben im Zusammenhang mit Verantwortung, Hoffnung und Ihrem Alltag nach; halten Sie offene Fragen fest.'], uygulama: 'Schreiben Sie zu jeder Grundlage eine kurze Erklärung. Bringen Sie Unklares zum nächsten Gespräch mit.' },
      { baslik: 'Reinheit, Gebetswaschung und Ganzwaschung', giris: 'Lernen Sie die Vorbereitung zum Gottesdienst praktisch mit einem bebilderten Leitfaden.', konular: ['Unterscheiden Sie einen sauberen Körper, saubere Kleidung und einen sauberen Gebetsort von der rituellen Waschung.', 'Üben Sie das Waschen von Gesicht, Armen einschließlich Ellenbogen und Füßen einschließlich Knöcheln sowie das Bestreichen des Kopfes. Folgen Sie dem Leitfaden für die vollständige Reihenfolge und empfohlene Handlungen.', 'Lesen Sie, was die Gebetswaschung aufhebt, wann die Ganzwaschung erforderlich ist und was Tayammum bedeutet; fragen Sie bei persönlichen Unklarheiten nach.'], uygulama: 'Führen Sie die Waschung mit dem bebilderten Leitfaden vor und prüfen Sie die Schritte mit einer Lehrperson.' },
      { baslik: 'Das Gebet Schritt für Schritt lernen', giris: 'Verbinden Sie Vorbereitung, Bewegungen und Rezitation mit praktischer Begleitung.', konular: ['Lernen Sie die fünf täglichen Gebete, ihre Zeiten, die Qibla, die Absicht und die Vorbereitung kennen. Aktuelle Ortszeiten stehen auf unserer Startseite.', 'Üben Sie Stehen, Verbeugung, Niederwerfung und Sitzen mit dem bebilderten Leitfaden; lernen Sie, was eine Rak‘a ist.', 'Hören Sie al-Fatiha, kurze Suren und Gebetsworte in kleinen Abschnitten. Besprechen Sie mit dem Imam das Zusammenspiel von Bewegungen und Rezitation.'], uygulama: 'Zeigen Sie anhand des Leitfadens die Bewegungsfolge einer Rak‘a und ordnen Sie die Rezitationen zu.' },
      { baslik: 'Von arabischen Buchstaben zum Koranlesen', giris: 'Der Name eines Buchstabens unterscheidet sich von seinem Laut mit einem Vokalzeichen. Schauen, hören und wiederholen Sie.', konular: ['Beginnen Sie mit dem Alphabet und beachten Sie Punkte und Formen, die ähnliche Buchstaben unterscheiden.', 'Üben Sie nacheinander Fatha, Kasra und Damma. Hören Sie jedes Feld an und sprechen Sie den Laut nach.', 'Vergleichen Sie kurze und lange Laute; üben Sie anschließend Sukun, Schadda und verbundenes Lesen. Wiederholen Sie frühere Lektionen bei Bedarf.'], uygulama: 'Wählen Sie fünf Buchstaben. Hören Sie ihre Namen und ihre Laute mit drei Vokalzeichen. Wiederholen Sie zwei leicht verwechselte Buchstaben.' },
      { baslik: 'Suren, Bittgebete und ihre Bedeutung', giris: 'Ein kurzer, sorgfältig gelernter und verstandener Abschnitt ist ein greifbares Lernziel.', konular: ['Hören Sie al-Fatiha zeilenweise, halten Sie zum Wiederholen an und lesen Sie die französische Übersetzung auf der Kursseite.', 'Lernen Sie mit kurzen Suren wie al-Ichlas, al-Falaq und an-Nas weiter. Lassen Sie Ihre Rezitation prüfen.', 'Üben Sie Subhanaka, Taschahhud, Salli und Barik mit den Aufnahmen; der Gebetsleitfaden zeigt, wo sie gesprochen werden.'], uygulama: 'Wiederholen Sie eine Zeile dreimal mit dem Text und versuchen Sie es dann ohne Hinsehen. Kehren Sie zu schwierigen Stellen zurück.' },
      { baslik: 'Fasten, Teilen und weitere Gottesdienste', giris: 'Lernen Sie die Ziele und Grundbegriffe; vertiefen Sie Einzelheiten nach Bedarf.', konular: ['Lernen Sie die Begriffe Ramadan, Fasten, Suhur und Iftar; lesen Sie im Leitfaden über Voraussetzungen und Ausnahmen.', 'Unterscheiden Sie Zakat von freiwilligen Spenden. Fragen Sie den Imam nach persönlichen Pflichten und Berechnungen unter Berücksichtigung Ihrer Situation.', 'Lernen Sie die Bedeutung von Hadsch und ‘Umra, ihre Unterschiede und den Platz der Gottesdienste im Leben kennen.'], uygulama: 'Erstellen Sie ein kleines Glossar zu Fasten, Zakat, Spenden, Hadsch und ‘Umra und ergänzen Sie offene Fragen.' },
      { baslik: 'Das Vorbild des Propheten und der Alltag', giris: 'Verbinden Sie das Gelernte mit Familie, Nachbarschaft, Arbeit und Gesellschaft.', konular: ['Lesen Sie eine verlässliche Einführung in das Leben des Propheten Muhammad und suchen Sie Beispiele für Ehrlichkeit, Mitgefühl und Vertrauenswürdigkeit.', 'Denken Sie über Güte gegenüber Eltern und Nachbarn, das Einhalten von Zusagen und die Rechte anderer nach.', 'Besprechen Sie Schwierigkeiten mit neuen Gewohnheiten oder Angehörigen anderer Überzeugungen mit dem Imam.'], uygulama: 'Wählen Sie eine gute Tat für diese Woche. Notieren Sie am Ende etwas Gelerntes und eine entstandene Frage.' },
    ],
  },
};
