/* Bütün kurs duyuruları, kayıt onayları ve yönetici davetleri için ortak şablon. */
var VELI_EPOSTA_GORSEL = 'https://github.com/ulucamii2026/ulucamii2026.github.io/releases/download/eposta-kurumsal-v1/kurs-kurumsal-v1.gif';
function veliEpostaKacis(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function veliEpostaBelge(dil,baslik,icerik,dip){
  if(['tr','fr'].indexOf(dil)<0)throw new Error('veli-eposta-dil');
  var e=veliEpostaKacis,ad=dil==='fr'?'Cours de Coran · Ulu Camii':'Ulu Camii · Kur’an Kursu';
  return '<!doctype html><html lang="'+dil+'"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="x-apple-disable-message-reformatting"></head><body style="margin:0;padding:0;background:#eef3f3;font-family:Arial,sans-serif;font-size:20px;line-height:1.5;-webkit-text-size-adjust:100%;text-size-adjust:100%"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="width:100%;table-layout:fixed"><tr><td align="center" style="padding:8px 4px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;width:100%;table-layout:fixed;background:#fff;border-radius:10px;overflow:hidden"><tr><td align="center" style="background:#153e36;padding:22px 16px;color:#fff"><img src="https://www.ulucamii.be/media/logo/kuran-kursu-logo-256.png" width="104" height="104" alt="'+e(ad)+'" style="display:block;width:104px;height:104px;max-width:100%;border:0;margin:0 auto 12px"><p style="font-family:Arial,sans-serif;font-size:16px;line-height:1.5;color:#f3e9d3;margin:0 0 6px">'+e(ad)+'</p><p style="font-family:Arial,sans-serif;font-size:14px;color:#f3e9d3;margin:0 0 18px">MARCHE-EN-FAMENNE</p><h1 style="font-family:Arial,sans-serif;font-size:30px;line-height:1.25;color:#fff;margin:0;word-wrap:break-word">'+e(baslik)+'</h1></td></tr><tr><td><img src="'+VELI_EPOSTA_GORSEL+'" width="600" alt="" style="display:block;width:100%;max-width:600px;height:auto;border:0"></td></tr><tr><td style="font-family:Arial,sans-serif;font-size:20px;line-height:1.5;color:#293f42;word-wrap:break-word;padding:24px 16px 16px">'+icerik+'</td></tr><tr><td style="font-family:Arial,sans-serif;padding:22px 16px;background:#e9f1ee;font-size:16px;line-height:1.5;color:#435b5e;word-wrap:break-word">'+e(dip|| (dil==='fr'?'Merci de consulter régulièrement nos e-mails et le portail des parents.':'Lütfen e-postalarımızı ve veli portalını düzenli takip ediniz.'))+'<br>info@ulucamii.be<br>imam@ulucamii.be</td></tr></table></td></tr></table></body></html>';
}
function veliEpostaDuzMetin(metin,dil,baslik){
  var html=String(metin).split(/\n\s*\n/).map(function(p){return '<p style="font-family:Arial,sans-serif;font-size:20px;line-height:1.5;margin:0 0 20px;word-wrap:break-word">'+veliEpostaKacis(p).replace(/https:\/\/[^\s<]+/g,function(url){return '<a href="'+url+'" style="color:#23666b;word-break:break-all">'+url+'</a>';}).replace(/\n/g,'<br>')+'</p>';}).join('');
  return veliEpostaBelge(dil,baslik,html,'');
}
