/** Seviye testi soru bankası — ahlak ve âdâb (docs/SEVIYE-TESTI.md §5 soru yazım kılavuzu).
 *
 *  12 madde: B1 4 · B2 4 · B3 4. Kaynaklar madde başına `kaynak` alanındadır (TDV İslâm
 *  Ansiklopedisi ve Diyanet Kur’an portalı). Mezhebe bağlı madde yoktur; sorular kimseyi
 *  yargılamayan, günlük hayatta karşılığı olan davranış ve kavramlar üzerine kurulmuştur.
 */
import type { BilgiMaddesi } from '../tipler.ts';

export const AHLAK: BilgiMaddesi[] = [
  {
    tur: 'bilgi',
    alan: 'ahlak',
    basamak: 1,
    id: 'ah01',
    soru: {
      tr: 'Bir müslüman «es-selâmü aleyküm» diyerek selâm verdiğinde kendisine nasıl karşılık verilir?',
      fr: 'Lorsqu’un musulman vous salue en disant « as-salâmou alaykoum », que lui répondez-vous ?',
      en: 'When a Muslim greets you by saying “as-salâmu alaykum”, what do you reply?',
      nl: 'Wanneer een moslim u begroet met “as-salaamoe alaykoem”, wat antwoordt u dan?',
      de: 'Wenn ein Muslim Sie mit „as-salamu alaikum“ begrüßt, was antworten Sie ihm?',
    },
    siklar: [
      {
        tr: 'Ve aleykümü’s-selâm (selâm sizin de üzerinize olsun)',
        fr: 'Wa alaykoum as-salâm (que la paix soit aussi sur vous)',
        en: 'Wa alaykum as-salâm (and peace be upon you too)',
        nl: 'Wa alaykoem as-salaam (en vrede zij ook met u)',
        de: 'Wa alaikum as-salam (und auch mit Ihnen sei der Friede)',
      },
      {
        tr: 'Bismillâhirrahmânirrahîm (Rahmân ve rahîm Allah’ın adıyla)',
        fr: 'Bismillâhi ar-Rahmâni ar-Rahîm (au nom d’Allah, le Tout Miséricordieux)',
        en: 'Bismillâhi ar-Rahmâni ar-Rahîm (in the name of Allah, the Most Merciful)',
        nl: 'Bismillaahi ar-Rahmaani ar-Rahiem (in de naam van Allah, de meest Barmhartige)',
        de: 'Bismillahi ar-Rahmani ar-Rahim (im Namen Allahs, des Allerbarmers)',
      },
      {
        tr: 'Elhamdülillâh (hamd ve övgü Allah’a mahsustur)',
        fr: 'Al-hamdou lillâh (la louange appartient à Allah)',
        en: 'Al-hamdu lillâh (all praise belongs to Allah)',
        nl: 'Al-hamdoe lillaah (alle lof behoort aan Allah)',
        de: 'Al-hamdu lillah (alles Lob gebührt Allah)',
      },
      {
        tr: 'Sübhânallah (Allah her türlü eksiklikten uzaktır)',
        fr: 'Soubhâna Allah (Allah est exempt de toute imperfection)',
        en: 'Subhânallâh (Allah is free from every imperfection)',
        nl: 'Soebhaanallah (Allah is vrij van elke onvolkomenheid)',
        de: 'Subhanallah (Allah ist frei von jeder Unvollkommenheit)',
      },
    ],
    dogru: 0,
    kaynak: 'TDV İslâm Ansiklopedisi, «Selâm» — islamansiklopedisi.org.tr/selam',
  },
  {
    tur: 'bilgi',
    alan: 'ahlak',
    basamak: 1,
    id: 'ah02',
    soru: {
      tr: 'Yemeğe ve her işe başlarken söylenen «Bismillâhirrahmânirrahîm» sözüne ne ad verilir?',
      fr: 'Comment appelle-t-on la formule « Bismillâhi ar-Rahmâni ar-Rahîm », prononcée avant de manger et avant toute action ?',
      en: 'What is the name of the formula “Bismillâhi ar-Rahmâni ar-Rahîm”, said before eating and before starting anything?',
      nl: 'Hoe heet de formule “Bismillaahi ar-Rahmaani ar-Rahiem”, die men uitspreekt vóór het eten en vóór elke handeling?',
      de: 'Wie heißt die Formel „Bismillahi ar-Rahmani ar-Rahim“, die man vor dem Essen und vor jeder Handlung spricht?',
    },
    siklar: [
      {
        tr: 'Tekbir',
        fr: 'Le takbîr',
        en: 'The takbir',
        nl: 'De takbir',
        de: 'Der Takbir',
      },
      {
        tr: 'Salâvat',
        fr: 'La prière sur le Prophète (salawât)',
        en: 'The prayer upon the Prophet (salawat)',
        nl: 'Het gebed voor de Profeet (salawaat)',
        de: 'Das Gebet für den Propheten (Salawat)',
      },
      {
        tr: 'Besmele',
        fr: 'La basmala',
        en: 'The basmala',
        nl: 'De basmala',
        de: 'Die Basmala',
      },
      {
        tr: 'Tesbih',
        fr: 'Le tasbîh',
        en: 'The tasbih',
        nl: 'De tasbih',
        de: 'Der Tasbih',
      },
    ],
    dogru: 2,
    kaynak: 'TDV İslâm Ansiklopedisi, «Besmele» — islamansiklopedisi.org.tr/besmele',
  },
  {
    tur: 'bilgi',
    alan: 'ahlak',
    basamak: 1,
    id: 'ah03',
    soru: {
      tr: 'İslâm ahlâkında yalanın karşıtı olan ve başlıca erdemlerden sayılan davranış hangisidir?',
      fr: 'Dans l’éthique musulmane, quel comportement est l’opposé du mensonge et compte parmi les principales vertus ?',
      en: 'In Islamic ethics, which quality is the opposite of lying and counts among the chief virtues?',
      nl: 'Welke eigenschap is in de islamitische ethiek het tegendeel van de leugen en geldt als een van de voornaamste deugden?',
      de: 'Welche Eigenschaft ist in der islamischen Ethik das Gegenteil der Lüge und zählt zu den wichtigsten Tugenden?',
    },
    siklar: [
      {
        tr: 'Cömertlik: elindekini başkalarıyla paylaşabilmek',
        fr: 'La générosité : savoir partager ce que l’on possède',
        en: 'Generosity: being able to share what one has',
        nl: 'Vrijgevigheid: kunnen delen wat men bezit',
        de: 'Großzügigkeit: teilen können, was man besitzt',
      },
      {
        tr: 'Doğruluk: sözde ve işte gerçeğe uygun olmak',
        fr: 'La véracité : être conforme à la vérité en parole et en acte',
        en: 'Truthfulness: being true to reality in word and deed',
        nl: 'Waarachtigheid: in woord en daad met de werkelijkheid overeenstemmen',
        de: 'Wahrhaftigkeit: in Wort und Tat der Wirklichkeit entsprechen',
      },
      {
        tr: 'Sabır: sıkıntı ve zorluk karşısında dayanabilmek',
        fr: 'La patience : tenir bon face à l’épreuve et à la difficulté',
        en: 'Patience: holding firm in the face of hardship and difficulty',
        nl: 'Geduld: standhouden bij beproeving en tegenslag',
        de: 'Geduld: bei Prüfung und Schwierigkeit standhalten',
      },
      {
        tr: 'Tevâzu: kendini başkalarından üstün görmemek',
        fr: 'L’humilité : ne pas se croire supérieur aux autres',
        en: 'Humility: not considering oneself above other people',
        nl: 'Nederigheid: zich niet boven anderen verheven achten',
        de: 'Demut: sich nicht über andere erhaben fühlen',
      },
    ],
    dogru: 1,
    kaynak: 'TDV İslâm Ansiklopedisi, «Sıdk» — islamansiklopedisi.org.tr/sidk',
  },
  {
    tur: 'bilgi',
    alan: 'ahlak',
    basamak: 1,
    id: 'ah04',
    soru: {
      tr: 'Kur’an-ı Kerim (İsrâ sûresi, 23. âyet) yaşlanan ana babaya karşı nasıl davranılmasını ister?',
      fr: 'Que demande le Coran (sourate al-Isrâ, verset 23) quant à l’attitude envers des parents devenus âgés ?',
      en: 'What does the Qur’an (Surah Al-Isra, verse 23) ask regarding one’s conduct towards ageing parents?',
      nl: 'Wat vraagt de Koran (soera al-Isra, vers 23) over de houding tegenover ouders die oud geworden zijn?',
      de: 'Was verlangt der Koran (Sure al-Isra, Vers 23) in Bezug auf das Verhalten gegenüber alt gewordenen Eltern?',
    },
    siklar: [
      {
        tr: 'İhtiyaçları karşılandıktan sonra ayrı yaşamalarının sağlanmasını',
        fr: 'Qu’on subvienne à leurs besoins puis qu’ils vivent séparément',
        en: 'That their needs be met and that they then live separately',
        nl: 'Dat in hun behoeften wordt voorzien en dat zij daarna apart wonen',
        de: 'Dass für ihre Bedürfnisse gesorgt wird und sie danach getrennt wohnen',
      },
      {
        tr: 'Yalnız bayram ve özel günlerde ziyaret edilmelerini',
        fr: 'Qu’on leur rende visite seulement lors des fêtes et des jours particuliers',
        en: 'That they be visited only on feast days and special occasions',
        nl: 'Dat zij alleen op feestdagen en bijzondere dagen worden bezocht',
        de: 'Dass sie nur an Festtagen und besonderen Tagen besucht werden',
      },
      {
        tr: 'Kendilerine «öf» bile denmeden güzel ve tatlı söz söylenmesini',
        fr: 'Qu’on ne leur dise pas même « fi ! » et qu’on leur parle avec douceur',
        en: 'That not even “ugh” be said to them and that they be addressed kindly',
        nl: 'Dat men zelfs geen “foei” tegen hen zegt en hen vriendelijk toespreekt',
        de: 'Dass man nicht einmal „pfui“ zu ihnen sagt und freundlich mit ihnen spricht',
      },
      {
        tr: 'Aile kararlarında görüşlerinin sonradan alınmasını',
        fr: 'Que leur avis soit recueilli après coup dans les décisions familiales',
        en: 'That their opinion be sought afterwards in family decisions',
        nl: 'Dat hun mening bij gezinsbeslissingen pas achteraf wordt gevraagd',
        de: 'Dass ihre Meinung bei Familienentscheidungen erst nachträglich eingeholt wird',
      },
    ],
    dogru: 2,
    kaynak:
      'Diyanet Kur’an portalı, İsrâ sûresi 17/23 («sakın onlara “öf!” bile deme; onları azarlama; onlara tatlı ve güzel söz söyle») — kuran.diyanet.gov.tr/mushaf/kuran-meal-2/isra-suresi-17/ayet-23/diyanet-isleri-baskanligi-meali-1',
  },
  {
    tur: 'bilgi',
    alan: 'ahlak',
    basamak: 2,
    id: 'ah05',
    soru: {
      tr: 'Bir kimsenin başkasının hakkını yemesine «kul hakkı» denir. Bu hakkın bağışlanması için ne gerekir?',
      fr: 'Porter atteinte au droit d’autrui relève de ce qu’on appelle « les droits des serviteurs » (houqoûq al-‘ibâd). Que faut-il pour en obtenir le pardon ?',
      en: 'Wronging another person in what is theirs by right is called “a debt owed to a fellow human being” (huquq al-‘ibad). What is needed for such a wrong to be forgiven?',
      nl: 'Iemand tekortdoen in wat hem rechtens toekomt, valt onder wat “de rechten van de dienaren” (hoeqoeq al-‘ibaad) wordt genoemd. Wat is nodig om daarvoor vergeving te krijgen?',
      de: 'Einem Menschen vorzuenthalten, was ihm rechtmäßig zusteht, fällt unter die sogenannten „Rechte der Diener“ (Huquq al-‘Ibad). Was ist nötig, um dafür Vergebung zu erlangen?',
    },
    siklar: [
      {
        tr: 'Bir süre oruç tutup fazladan sadaka vermek',
        fr: 'Jeûner un certain temps et donner une aumône supplémentaire',
        en: 'Fasting for a period and giving extra charity',
        nl: 'Een tijd lang vasten en extra aalmoezen geven',
        de: 'Eine Zeit lang fasten und zusätzliche Almosen geben',
      },
      {
        tr: 'Hakkı ödeyip hak sahibinin rızasını almak (helâlleşmek)',
        fr: 'Réparer le tort et obtenir l’agrément de la personne lésée',
        en: 'Making the wrong good and obtaining the wronged person’s pardon',
        nl: 'Het onrecht herstellen en de vergeving van de benadeelde verkrijgen',
        de: 'Das Unrecht wiedergutmachen und die Vergebung des Geschädigten erlangen',
      },
      {
        tr: 'Yalnız tövbe edip Allah’tan bağışlanma dilemek',
        fr: 'Se repentir seulement et demander le pardon d’Allah',
        en: 'Merely repenting and asking Allah for forgiveness',
        nl: 'Alleen berouw tonen en Allah om vergeving vragen',
        de: 'Nur Reue zeigen und Allah um Vergebung bitten',
      },
      {
        tr: 'Aynı hatayı bir daha yapmamaya karar vermek',
        fr: 'Décider de ne plus jamais commettre la même faute',
        en: 'Resolving never to repeat the same mistake',
        nl: 'Besluiten dezelfde fout nooit meer te maken',
        de: 'Beschließen, denselben Fehler nie mehr zu begehen',
      },
    ],
    dogru: 1,
    kaynak:
      'TDV İslâm Ansiklopedisi, «Kul hakkı»: «bu hakların sahiplerine ödenmesi veya onların rızalarının alınması gerektiğini bildirmişlerdir» — islamansiklopedisi.org.tr/kul-hakki',
  },
  {
    tur: 'bilgi',
    alan: 'ahlak',
    basamak: 2,
    id: 'ah06',
    soru: {
      tr: 'İslâm ahlâkında «gıybet» ne demektir?',
      fr: 'Que signifie « ghîba » (la médisance) dans l’éthique musulmane ?',
      en: 'What does “ghibah” (backbiting) mean in Islamic ethics?',
      nl: 'Wat betekent “ghiba” (kwaadspreken) in de islamitische ethiek?',
      de: 'Was bedeutet „Ghiba“ (üble Nachrede) in der islamischen Ethik?',
    },
    siklar: [
      {
        tr: 'Bir kimseyle yüz yüze tartışıp ona kırıcı sözler söylemek',
        fr: 'Discuter en face avec quelqu’un et lui adresser des paroles blessantes',
        en: 'Arguing with someone face to face and saying hurtful things to them',
        nl: 'Met iemand van aangezicht tot aangezicht ruziën en kwetsende woorden zeggen',
        de: 'Mit jemandem von Angesicht zu Angesicht streiten und ihm verletzende Worte sagen',
      },
      {
        tr: 'Bir kimseye, kendisinde bulunmayan bir kusuru yakıştırmak',
        fr: 'Imputer à quelqu’un un défaut qu’il n’a pas',
        en: 'Attributing to someone a fault that they do not have',
        nl: 'Iemand een gebrek toeschrijven dat hij niet heeft',
        de: 'Jemandem einen Fehler zuschreiben, den er nicht hat',
      },
      {
        tr: 'Bir kimsenin sırrını izni olmadan bir başkasına aktarmak',
        fr: 'Rapporter à autrui le secret de quelqu’un sans son accord',
        en: 'Passing on someone’s secret to another person without permission',
        nl: 'Het geheim van iemand zonder diens toestemming aan een ander doorvertellen',
        de: 'Das Geheimnis eines Menschen ohne dessen Zustimmung an andere weitergeben',
      },
      {
        tr: 'Bir kimseyi arkasından, hoşlanmayacağı gerçek bir kusuruyla anmak',
        fr: 'Évoquer en son absence un défaut réel qu’elle n’aimerait pas entendre',
        en: 'Mentioning, behind their back, a real fault they would not like to hear',
        nl: 'In iemands afwezigheid een werkelijk gebrek noemen dat hij niet graag zou horen',
        de: 'In Abwesenheit einer Person einen tatsächlichen Fehler erwähnen, den sie nicht gern hören würde',
      },
    ],
    dogru: 3,
    kaynak:
      'TDV İslâm Ansiklopedisi, «Gıybet»: kişiyi «kendisinde bulunan kusurlarla anmanın gıybet», bulunmayan kusuru isnat etmenin iftira (bühtan) olduğu — islamansiklopedisi.org.tr/giybet',
  },
  {
    tur: 'bilgi',
    alan: 'ahlak',
    basamak: 2,
    id: 'ah07',
    soru: {
      tr: 'İslâm ahlâkında «israf» ne anlama gelir?',
      fr: 'Que signifie « isrâf » (le gaspillage) dans l’éthique musulmane ?',
      en: 'What does “israf” (wastefulness) mean in Islamic ethics?',
      nl: 'Wat betekent “israf” (verspilling) in de islamitische ethiek?',
      de: 'Was bedeutet „Israf“ (Verschwendung) in der islamischen Ethik?',
    },
    siklar: [
      {
        tr: 'Mal ve imkânları ölçüsüzce, gereksiz yere harcayıp savurmak',
        fr: 'Dépenser ses biens sans mesure et les dissiper inutilement',
        en: 'Spending one’s wealth without measure and squandering it needlessly',
        nl: 'Zijn bezit mateloos uitgeven en het nodeloos verkwisten',
        de: 'Sein Vermögen maßlos ausgeben und es unnötig vergeuden',
      },
      {
        tr: 'Gereken yere bile harcamaktan kaçınıp elini sıkı tutmak',
        fr: 'S’abstenir de dépenser même là où il le faudrait, par avarice',
        en: 'Refusing to spend even where one should, out of stinginess',
        nl: 'Uit gierigheid zelfs daar niet uitgeven waar het nodig zou zijn',
        de: 'Aus Geiz selbst dort nicht ausgeben, wo es nötig wäre',
      },
      {
        tr: 'Kazancın bir bölümünü ileride kullanmak üzere biriktirmek',
        fr: 'Mettre de côté une part de ses revenus pour l’avenir',
        en: 'Setting aside part of one’s income for use in the future',
        nl: 'Een deel van zijn inkomsten opzijzetten voor later',
        de: 'Einen Teil seiner Einkünfte für später zurücklegen',
      },
      {
        tr: 'Gerekli yerlere gerektiği ölçüde eli açık biçimde harcamak',
        fr: 'Dépenser généreusement là où il faut et dans la juste mesure',
        en: 'Spending generously where needed and in the right measure',
        nl: 'Royaal en in de juiste maat uitgeven waar het nodig is',
        de: 'Dort, wo es nötig ist, großzügig und im rechten Maß ausgeben',
      },
    ],
    dogru: 0,
    kaynak: 'TDV İslâm Ansiklopedisi, «İsraf» — islamansiklopedisi.org.tr/israf',
  },
  {
    tur: 'bilgi',
    alan: 'ahlak',
    basamak: 2,
    id: 'ah08',
    soru: {
      tr: 'İslâm’da komşu hakkı konusunda aşağıdakilerden hangisi doğrudur?',
      fr: 'Au sujet des droits du voisin (djâr) en islam, laquelle de ces affirmations est exacte ?',
      en: 'Regarding the rights of the neighbour (jar) in Islam, which of the following is correct?',
      nl: 'Welke van de volgende uitspraken over de rechten van de buur (djaar) in de islam is juist?',
      de: 'Welche der folgenden Aussagen über die Rechte des Nachbarn (Dschar) im Islam trifft zu?',
    },
    siklar: [
      {
        tr: 'Komşu hakkı yalnız aynı binada oturanlar için geçerlidir',
        fr: 'Les droits du voisin ne valent que pour les habitants d’un même immeuble',
        en: 'Neighbours’ rights apply only to people living in the same building',
        nl: 'De rechten van de buur gelden alleen voor bewoners van hetzelfde gebouw',
        de: 'Die Rechte des Nachbarn gelten nur für Bewohner desselben Gebäudes',
      },
      {
        tr: 'Komşu hakkı yalnız akraba olan komşular için geçerlidir',
        fr: 'Les droits du voisin ne valent que pour les voisins de la même famille',
        en: 'Neighbours’ rights apply only to neighbours who are relatives',
        nl: 'De rechten van de buur gelden alleen voor buren die familie zijn',
        de: 'Die Rechte des Nachbarn gelten nur für Nachbarn, die verwandt sind',
      },
      {
        tr: 'Komşu hakkı, komşunun müslüman olup olmamasına bakılmadan gözetilir',
        fr: 'Les droits du voisin s’observent, que le voisin soit musulman ou non',
        en: 'Neighbours’ rights are observed whether or not the neighbour is Muslim',
        nl: 'De rechten van de buur gelden, of de buur nu moslim is of niet',
        de: 'Die Rechte des Nachbarn gelten, ob der Nachbar Muslim ist oder nicht',
      },
      {
        tr: 'Komşu hakkı yalnız komşu yardım istediğinde gözetilir',
        fr: 'Les droits du voisin ne s’observent que lorsqu’il demande de l’aide',
        en: 'Neighbours’ rights are observed only when the neighbour asks for help',
        nl: 'De rechten van de buur gelden alleen wanneer de buur om hulp vraagt',
        de: 'Die Rechte des Nachbarn gelten nur, wenn der Nachbar um Hilfe bittet',
      },
    ],
    dogru: 2,
    kaynak: 'TDV İslâm Ansiklopedisi, «Komşu» (Nisâ 4/36) — islamansiklopedisi.org.tr/komsu',
  },
  {
    tur: 'bilgi',
    alan: 'ahlak',
    basamak: 3,
    id: 'ah09',
    soru: {
      tr: 'Ahlâk ve tasavvuf terimi olarak «ihlâs» ne demektir?',
      fr: 'Comme terme d’éthique et de spiritualité, que signifie « ikhlâs » (la sincérité) ?',
      en: 'As a term of ethics and spirituality, what does “ikhlas” (sincerity) mean?',
      nl: 'Wat betekent “ikhlaas” (oprechtheid) als begrip uit de ethiek en de spiritualiteit?',
      de: 'Was bedeutet „Ichlas“ (Aufrichtigkeit) als Begriff der Ethik und der Spiritualität?',
    },
    siklar: [
      {
        tr: 'İbadetleri günün en faziletli vaktinde yerine getirmeye özen göstermek',
        fr: 'Veiller à accomplir les actes d’adoration au moment le plus méritoire',
        en: 'Taking care to perform acts of worship at the most meritorious time',
        nl: 'Ervoor zorgen dat men de eredienst op het meest verdienstelijke tijdstip verricht',
        de: 'Darauf achten, die gottesdienstlichen Handlungen zur verdienstvollsten Zeit zu verrichten',
      },
      {
        tr: 'Yapılan iyiliği başkalarına anlatarak onları da iyiliğe teşvik etmek',
        fr: 'Raconter le bien accompli afin d’encourager les autres à le faire',
        en: 'Telling others about one’s good deeds so as to encourage them too',
        nl: 'Het verrichte goede vertellen om ook anderen tot het goede aan te sporen',
        de: 'Das vollbrachte Gute erzählen, um auch andere zum Guten anzuspornen',
      },
      {
        tr: 'İbadetlerin şeklî şartlarına eksiksiz biçimde uymaya dikkat etmek',
        fr: 'Respecter scrupuleusement toutes les conditions formelles du culte',
        en: 'Carefully fulfilling every formal condition of an act of worship',
        nl: 'Alle vormvoorwaarden van de eredienst nauwgezet naleven',
        de: 'Alle formalen Bedingungen des Gottesdienstes gewissenhaft erfüllen',
      },
      {
        tr: 'İbadet ve iyilikleri gösterişten arındırıp yalnız Allah rızâsı için yapmak',
        fr: 'Accomplir adorations et bonnes actions sans ostentation, pour Allah seul',
        en: 'Doing worship and good deeds free of show, for Allah’s sake alone',
        nl: 'Eredienst en goede daden vrij van vertoon en alleen omwille van Allah verrichten',
        de: 'Gottesdienst und gute Taten ohne Zurschaustellung allein um Allahs willen verrichten',
      },
    ],
    dogru: 3,
    kaynak: 'TDV İslâm Ansiklopedisi, «İhlâs» — islamansiklopedisi.org.tr/ihlas',
  },
  {
    tur: 'bilgi',
    alan: 'ahlak',
    basamak: 3,
    id: 'ah10',
    soru: {
      tr: 'İslâm ahlâkında «tevekkül» ne anlama gelir?',
      fr: 'Que signifie « tawakkoul » (la confiance en Dieu) dans l’éthique musulmane ?',
      en: 'What does “tawakkul” (trust in God) mean in Islamic ethics?',
      nl: 'Wat betekent “tawakkoel” (vertrouwen op God) in de islamitische ethiek?',
      de: 'Was bedeutet „Tawakkul“ (Gottvertrauen) in der islamischen Ethik?',
    },
    siklar: [
      {
        tr: 'Hiçbir şey yapmadan sonucu beklemeye geçip olacakları seyretmek',
        fr: 'Ne rien entreprendre et attendre simplement que le sort s’accomplisse',
        en: 'Doing nothing at all and simply waiting for the outcome to unfold',
        nl: 'Niets ondernemen en eenvoudig afwachten hoe het afloopt',
        de: 'Nichts unternehmen und einfach abwarten, wie es ausgeht',
      },
      {
        tr: 'Geçmişte yapılan hataları düşünüp pişmanlık duymak',
        fr: 'Songer à ses fautes passées et en éprouver du regret',
        en: 'Reflecting on past mistakes and feeling regret for them',
        nl: 'Aan fouten uit het verleden denken en daar spijt van hebben',
        de: 'An vergangene Fehler denken und darüber Reue empfinden',
      },
      {
        tr: 'Sıkıntı anında insanlardan yardım istemekten kaçınmak',
        fr: 'Éviter de demander de l’aide à autrui dans l’épreuve',
        en: 'Avoiding asking other people for help in times of difficulty',
        nl: 'In moeilijke tijden vermijden anderen om hulp te vragen',
        de: 'In schweren Zeiten vermeiden, andere um Hilfe zu bitten',
      },
      {
        tr: 'Üzerine düşeni yaptıktan sonra sonucu Allah’a bırakıp O’na güvenmek',
        fr: 'Faire ce qui dépend de soi, puis s’en remettre à Allah avec confiance',
        en: 'Doing one’s own part and then entrusting the outcome to Allah',
        nl: 'Doen wat men zelf kan doen en de uitkomst vol vertrouwen aan Allah overlaten',
        de: 'Das Seine tun und den Ausgang dann vertrauensvoll Allah überlassen',
      },
    ],
    dogru: 3,
    kaynak: 'TDV İslâm Ansiklopedisi, «Tevekkül» — islamansiklopedisi.org.tr/tevekkul',
  },
  {
    tur: 'bilgi',
    alan: 'ahlak',
    basamak: 3,
    id: 'ah11',
    soru: {
      tr: 'Sıkıntıya dayanmaya «sabır» denir. Kişinin kendisine verilen nimetin değerini bilip söz ve davranışla karşılığını vermesine ne denir?',
      fr: 'Tenir bon dans l’épreuve s’appelle « sabr ». Comment nomme-t-on le fait de reconnaître la valeur d’un bienfait reçu et d’y répondre en parole et en acte ?',
      en: 'Enduring hardship is called “sabr”. What is it called when a person recognises the worth of a blessing received and responds to it in word and deed?',
      nl: 'Standhouden in beproeving heet “sabr”. Hoe noemt men het erkennen van de waarde van een ontvangen zegening en het beantwoorden daarvan in woord en daad?',
      de: 'Im Leid standzuhalten heißt „Sabr“. Wie nennt man es, wenn jemand den Wert einer empfangenen Wohltat erkennt und ihr in Wort und Tat entspricht?',
    },
    siklar: [
      { tr: 'Tevekkül', fr: 'Le tawakkoul', en: 'Tawakkul', nl: 'Tawakkoel', de: 'Tawakkul' },
      { tr: 'Şükür', fr: 'Le choukr', en: 'Shukr', nl: 'Sjoekr', de: 'Schukr' },
      { tr: 'Tövbe', fr: 'La tawba', en: 'Tawbah', nl: 'Tawba', de: 'Tawba' },
      { tr: 'İhlâs', fr: 'L’ikhlâs', en: 'Ikhlas', nl: 'Ikhlaas', de: 'Ichlas' },
    ],
    dogru: 1,
    kaynak: 'TDV İslâm Ansiklopedisi, «Şükür» — islamansiklopedisi.org.tr/sukur',
  },
  {
    tur: 'bilgi',
    alan: 'ahlak',
    basamak: 3,
    id: 'ah12',
    soru: {
      tr: 'İslâm ahlâkında «haset» ne anlama gelir?',
      fr: 'Que signifie « hasad » (l’envie) dans l’éthique musulmane ?',
      en: 'What does “hasad” (envy) mean in Islamic ethics?',
      nl: 'Wat betekent “hasad” (afgunst) in de islamitische ethiek?',
      de: 'Was bedeutet „Hasad“ (Neid) in der islamischen Ethik?',
    },
    siklar: [
      {
        tr: 'Başkasının elindeki nimetin ondan gitmesini istemek',
        fr: 'Souhaiter que le bienfait dont autrui jouit lui soit retiré',
        en: 'Wishing that a blessing someone enjoys be taken away from them',
        nl: 'Wensen dat een zegening die een ander geniet, hem wordt ontnomen',
        de: 'Wünschen, dass eine Wohltat, die ein anderer genießt, ihm entzogen wird',
      },
      {
        tr: 'Başkasının sahip olduğunun benzerini kıskanmadan istemek',
        fr: 'Désirer sans jalousie l’équivalent de ce que possède autrui',
        en: 'Wanting, without jealousy, the like of what another person has',
        nl: 'Zonder jaloezie hetzelfde wensen als wat een ander bezit',
        de: 'Ohne Eifersucht dasselbe wünschen, was ein anderer besitzt',
      },
      {
        tr: 'Başkasının elde ettiği başarıyı görmezden gelip küçümsemek',
        fr: 'Ignorer et minimiser la réussite obtenue par autrui',
        en: 'Ignoring and belittling the success another person has achieved',
        nl: 'Het succes dat een ander heeft behaald negeren en kleineren',
        de: 'Den Erfolg, den ein anderer erzielt hat, übergehen und kleinreden',
      },
      {
        tr: 'Başkasının sahip olduklarını sürekli kendisiyle karşılaştırmak',
        fr: 'Comparer sans cesse ce que possède autrui à ce que l’on a soi-même',
        en: 'Constantly comparing what others own with what one has oneself',
        nl: 'Voortdurend vergelijken wat anderen bezitten met wat men zelf heeft',
        de: 'Ständig vergleichen, was andere besitzen, mit dem, was man selbst hat',
      },
    ],
    dogru: 0,
    kaynak:
      'TDV İslâm Ansiklopedisi, «Haset» (haset ↔ gıpta ayrımı: kıskanılan kişinin nimetten mahrum kalmasını isteme) — islamansiklopedisi.org.tr/haset',
  },
];
