/** Seviye testi soru bankası — beyan (içerik yazımı sürüyor; docs/SEVIYE-TESTI.md kılavuzu).
 *
 *  Öz beyan maddeleri puanlanmaz; hoca raporunda katılımcının kendi anlatımı olarak yer alır.
 *  Seçenekler «henüz» diliyle, yargılamadan, en alt düzeyden en üste doğru sıralanmıştır.
 */
import type { BeyanMaddesi } from '../tipler.ts';

export const BEYAN: BeyanMaddesi[] = [
  // ——— Kur’an okuma beyanı ———
  {
    id: 'by01',
    kume: 'okuma',
    soru: {
      tr: "Kur’an-ı Kerim’i Arapça aslından (yüzünden) okuyabiliyor musunuz?",
      fr: "Arrivez-vous à lire le Coran directement dans le texte arabe ?",
      en: "Can you read the Qur’an directly from the Arabic text?",
      nl: "Kunt u de Koran rechtstreeks uit de Arabische tekst lezen?",
      de: "Können Sie den Koran unmittelbar aus dem arabischen Text lesen?",
    },
    secenekler: [
      {
        tr: 'Henüz okuyamıyorum',
        fr: 'Pas encore',
        en: 'Not yet',
        nl: 'Nog niet',
        de: 'Noch nicht',
      },
      {
        tr: 'Harfleri tanıyorum ama birleştiremiyorum',
        fr: "Je reconnais les lettres, mais je n’arrive pas à les relier",
        en: 'I recognise the letters but cannot join them yet',
        nl: 'Ik herken de letters, maar ik kan ze nog niet aan elkaar lezen',
        de: 'Ich erkenne die Buchstaben, kann sie aber noch nicht verbinden',
      },
      {
        tr: 'Heceleyerek okuyorum',
        fr: 'Je lis en syllabant',
        en: 'I read syllable by syllable',
        nl: 'Ik lees lettergreep voor lettergreep',
        de: 'Ich lese Silbe für Silbe',
      },
      {
        tr: 'Yavaş yavaş okuyorum',
        fr: 'Je lis lentement, mais je lis',
        en: 'I read slowly, but I do read',
        nl: 'Ik lees langzaam, maar ik lees',
        de: 'Ich lese langsam, aber ich lese',
      },
      {
        tr: 'Akıcı okuyorum',
        fr: 'Je lis couramment',
        en: 'I read fluently',
        nl: 'Ik lees vlot',
        de: 'Ich lese flüssig',
      },
      {
        tr: 'Tecvid kurallarına dikkat ederek okuyorum',
        fr: 'Je lis en appliquant les règles du tajwîd',
        en: 'I read applying the rules of tajwid',
        nl: 'Ik lees met toepassing van de regels van de tadjwied',
        de: 'Ich lese unter Anwendung der Tadschwid-Regeln',
      },
    ],
  },
  {
    id: 'by02',
    kume: 'okuma',
    soru: {
      tr: "Arap harflerini ve Kur’an okumayı nerede öğrendiniz?",
      fr: "Où avez-vous appris les lettres arabes et la lecture du Coran ?",
      en: "Where did you learn the Arabic letters and Qur’an reading?",
      nl: "Waar hebt u de Arabische letters en het lezen van de Koran geleerd?",
      de: "Wo haben Sie die arabischen Buchstaben und das Lesen des Korans gelernt?",
    },
    secenekler: [
      {
        tr: 'Henüz öğrenmedim',
        fr: "Je ne l’ai pas encore appris",
        en: 'I have not learnt it yet',
        nl: 'Ik heb het nog niet geleerd',
        de: 'Ich habe es noch nicht gelernt',
      },
      {
        tr: 'Kendi kendime: internet, uygulama ya da kitapla',
        fr: 'Seul(e) : internet, application ou livre',
        en: 'On my own: internet, an app or a book',
        nl: 'Zelfstandig: met internet, een app of een boek',
        de: 'Selbstständig: mit Internet, App oder Buch',
      },
      {
        tr: 'Ailemden ya da bir arkadaşımdan',
        fr: "Auprès de ma famille ou d’un(e) ami(e)",
        en: 'From my family or a friend',
        nl: 'In mijn familie of bij vrienden',
        de: 'In meiner Familie oder bei Freunden',
      },
      {
        tr: "Camide ya da Kur’an kursunda",
        fr: 'À la mosquée ou dans un cours de Coran',
        en: "At the mosque or in a Qur’an course",
        nl: "In de moskee of in een Koranles",
        de: "In der Moschee oder in einem Koranunterricht",
      },
      {
        tr: 'Okulda ya da üniversitede',
        fr: "À l’école ou à l’université",
        en: 'At school or university',
        nl: 'Op school of aan de universiteit',
        de: 'In der Schule oder an der Universität',
      },
    ],
  },
  {
    id: 'by03',
    kume: 'okuma',
    soru: {
      tr: 'Namazda okuduğunuz sûre ve duaları nereden okuyorsunuz?',
      fr: "Les sourates et les invocations que vous récitez dans la prière, d’où les lisez-vous ?",
      en: 'Where do you read the sûrahs and supplications you recite in prayer from?',
      nl: 'Waaruit leest u de soera’s en smeekbeden die u in het gebed opzegt?',
      de: 'Woraus lesen Sie die Suren und Bittgebete, die Sie im Gebet sprechen?',
    },
    secenekler: [
      {
        tr: 'Henüz okuyamıyorum',
        fr: 'Je ne les récite pas encore',
        en: 'I cannot recite them yet',
        nl: 'Ik zeg ze nog niet op',
        de: 'Ich spreche sie noch nicht',
      },
      {
        tr: 'Latin harfleriyle yazılmış metinden',
        fr: 'Dans un texte transcrit en lettres latines',
        en: 'From a text written in Latin letters',
        nl: 'Uit een tekst in Latijnse letters',
        de: 'Aus einem Text in lateinischer Schrift',
      },
      {
        tr: 'Ezberimden; Arapça yazıyı okuyamıyorum',
        fr: "De mémoire ; je ne lis pas l’écriture arabe",
        en: 'From memory; I cannot read the Arabic script',
        nl: 'Uit het hoofd; het Arabische schrift lees ik niet',
        de: 'Aus dem Gedächtnis; die arabische Schrift lese ich nicht',
      },
      {
        tr: 'Arapça yazıdan ve ezberimden',
        fr: "De l’écriture arabe et de mémoire",
        en: 'From the Arabic script and from memory',
        nl: 'Uit het Arabische schrift en uit het hoofd',
        de: 'Aus der arabischen Schrift und aus dem Gedächtnis',
      },
    ],
  },

  // ——— Uygulama öz beyanı ———
  {
    id: 'by04',
    kume: 'uygulama',
    soru: {
      tr: 'Abdest almayı ne kadar biliyorsunuz?',
      fr: 'Savez-vous faire les ablutions (woudou) ?',
      en: 'Do you know how to perform the ablution (wudu)?',
      nl: 'Weet u hoe u de rituele wassing (wudu) verricht?',
      de: 'Wissen Sie, wie man die rituelle Waschung (Wudu) verrichtet?',
    },
    secenekler: [
      {
        tr: 'Henüz öğrenmedim',
        fr: 'Pas encore',
        en: 'Not yet',
        nl: 'Nog niet',
        de: 'Noch nicht',
      },
      {
        tr: 'Biliyorum ama sırasından emin değilim',
        fr: "Je connais, mais je ne suis pas sûr(e) de l’ordre",
        en: 'I know it, but I am not sure of the order',
        nl: 'Ik weet het, maar ik ben niet zeker van de volgorde',
        de: 'Ich kenne sie, bin mir aber bei der Reihenfolge nicht sicher',
      },
      {
        tr: 'Yardım alarak alıyorum',
        fr: "Je les fais avec de l’aide",
        en: 'I do it with help',
        nl: 'Ik doe het met hulp',
        de: 'Ich verrichte sie mit Hilfe',
      },
      {
        tr: 'Kendi başıma rahatça alıyorum',
        fr: 'Je les fais seul(e), sans difficulté',
        en: 'I do it on my own, with ease',
        nl: 'Ik doe het zelfstandig, zonder moeite',
        de: 'Ich verrichte sie allein, ohne Mühe',
      },
    ],
  },
  {
    id: 'by05',
    kume: 'uygulama',
    soru: {
      tr: 'Boy abdesti (gusül) hakkında ne kadar bilgilisiniz?',
      fr: 'Que savez-vous de la grande ablution (ghousl) ?',
      en: 'How much do you know about the full ablution (ghusl)?',
      nl: 'Wat weet u over de grote rituele wassing (ghusl)?',
      de: 'Was wissen Sie über die große rituelle Waschung (Ghusl)?',
    },
    secenekler: [
      {
        tr: 'Henüz öğrenmedim',
        fr: 'Pas encore',
        en: 'Not yet',
        nl: 'Ik heb het nog niet geleerd',
        de: 'Ich habe es noch nicht gelernt',
      },
      {
        tr: 'Duydum ama ayrıntısını bilmiyorum',
        fr: "J’en ai entendu parler, sans en connaître les détails",
        en: 'I have heard of it but do not know the details',
        nl: 'Ik heb ervan gehoord, maar ken de details niet',
        de: 'Ich habe davon gehört, kenne aber die Einzelheiten nicht',
      },
      {
        tr: 'Genel hatlarıyla biliyorum',
        fr: 'Je le connais dans les grandes lignes',
        en: 'I know it broadly',
        nl: 'Ik ken het in grote lijnen',
        de: 'Ich kenne sie in groben Zügen',
      },
      {
        tr: 'Nasıl ve ne zaman gerektiğini rahatça biliyorum',
        fr: "Je sais sans difficulté comment et quand il est nécessaire",
        en: 'I know clearly how and when it is needed',
        nl: 'Ik weet zonder moeite hoe en wanneer zij nodig is',
        de: 'Ich weiß ohne Weiteres, wie und wann sie nötig ist',
      },
    ],
  },
  {
    id: 'by06',
    kume: 'uygulama',
    soru: {
      tr: 'Beş vakit namazı tek başınıza kılabiliyor musunuz?',
      fr: 'Arrivez-vous à accomplir seul(e) les cinq prières quotidiennes (salât) ?',
      en: 'Can you perform the five daily prayers (salah) on your own?',
      nl: 'Kunt u de vijf dagelijkse gebeden (salat) zelfstandig verrichten?',
      de: 'Können Sie die fünf täglichen Gebete (Salat) allein verrichten?',
    },
    secenekler: [
      {
        tr: 'Henüz kılamıyorum',
        fr: 'Pas encore',
        en: 'Not yet',
        nl: 'Nog niet',
        de: 'Noch nicht',
      },
      {
        tr: 'Birine bakarak ya da yardım alarak kılıyorum',
        fr: "Je les fais en suivant quelqu’un ou avec de l’aide",
        en: 'I follow someone else or need help',
        nl: 'Ik volg iemand anders of ik heb hulp nodig',
        de: 'Ich folge jemand anderem oder brauche Hilfe',
      },
      {
        tr: 'Bazı vakitleri kendi başıma kılıyorum',
        fr: 'Je fais certaines prières seul(e)',
        en: 'I perform some of the prayers on my own',
        nl: 'Sommige gebeden verricht ik zelfstandig',
        de: 'Einige Gebete verrichte ich allein',
      },
      {
        tr: 'Bütün vakitleri kendi başıma rahatça kılıyorum',
        fr: 'Je fais toutes les prières seul(e), sans difficulté',
        en: 'I perform all of them on my own, with ease',
        nl: 'Alle gebeden verricht ik zelfstandig, zonder moeite',
        de: 'Alle Gebete verrichte ich allein, ohne Mühe',
      },
    ],
  },
  {
    id: 'by07',
    kume: 'uygulama',
    soru: {
      tr: 'Namaz vakitlerini takip ediyor musunuz?',
      fr: 'Suivez-vous les horaires de prière ?',
      en: 'Do you follow the prayer times?',
      nl: 'Volgt u de gebedstijden?',
      de: 'Verfolgen Sie die Gebetszeiten?',
    },
    secenekler: [
      {
        tr: 'Henüz takip etmiyorum',
        fr: 'Pas encore',
        en: 'Not yet',
        nl: 'Nog niet',
        de: 'Noch nicht',
      },
      {
        tr: 'Ara sıra bakıyorum',
        fr: 'Je les regarde de temps en temps',
        en: 'I check them now and then',
        nl: 'Ik kijk er af en toe naar',
        de: 'Ich schaue ab und zu nach',
      },
      {
        tr: 'Çoğu gün takip ediyorum',
        fr: 'Je les suis la plupart des jours',
        en: 'I follow them most days',
        nl: 'Ik volg ze op de meeste dagen',
        de: 'Ich verfolge sie an den meisten Tagen',
      },
      {
        tr: 'Her gün düzenli takip ediyorum',
        fr: 'Je les suis chaque jour, régulièrement',
        en: 'I follow them every day, regularly',
        nl: 'Ik volg ze elke dag, regelmatig',
        de: 'Ich verfolge sie jeden Tag, regelmäßig',
      },
    ],
  },
  {
    id: 'by08',
    kume: 'uygulama',
    soru: {
      tr: 'Cemaatle namaza ve cuma namazına katılıyor musunuz?',
      fr: "Participez-vous à la prière en commun et à la prière du vendredi (djoumou’a) ?",
      en: "Do you attend congregational prayer and the Friday prayer (jumu’ah)?",
      nl: "Neemt u deel aan het gemeenschappelijke gebed en aan het vrijdaggebed (djoemoea)?",
      de: "Nehmen Sie am Gemeinschaftsgebet und am Freitagsgebet (Dschumua) teil?",
    },
    secenekler: [
      {
        tr: 'Henüz katılmadım',
        fr: 'Pas encore',
        en: 'Not yet',
        nl: 'Nog niet',
        de: 'Noch nicht',
      },
      {
        tr: 'Bir iki kez katıldım',
        fr: "J’y ai participé une ou deux fois",
        en: 'I have attended once or twice',
        nl: 'Ik heb één of twee keer deelgenomen',
        de: 'Ich habe ein- oder zweimal teilgenommen',
      },
      {
        tr: 'Ara sıra katılıyorum',
        fr: "J’y participe de temps en temps",
        en: 'I attend now and then',
        nl: 'Ik neem af en toe deel',
        de: 'Ich nehme ab und zu teil',
      },
      {
        tr: 'Cuma namazına düzenli katılıyorum',
        fr: 'Je participe régulièrement à la prière du vendredi',
        en: 'I attend the Friday prayer regularly',
        nl: 'Ik neem regelmatig deel aan het vrijdaggebed',
        de: 'Ich nehme regelmäßig am Freitagsgebet teil',
      },
      {
        tr: 'Hem cuma namazına hem vakit namazlarına cemaatle katılıyorum',
        fr: 'Je participe à la prière du vendredi et aux prières quotidiennes en commun',
        en: 'I attend both the Friday prayer and the daily prayers in congregation',
        nl: 'Ik neem deel aan het vrijdaggebed en aan de dagelijkse gemeenschappelijke gebeden',
        de: 'Ich nehme am Freitagsgebet und an den täglichen Gebeten in Gemeinschaft teil',
      },
    ],
  },
  {
    id: 'by09',
    kume: 'uygulama',
    soru: {
      tr: 'Ramazan orucu tecrübeniz nedir?',
      fr: 'Quelle est votre expérience du jeûne du ramadan ?',
      en: 'What is your experience of fasting in Ramadan?',
      nl: 'Wat is uw ervaring met het vasten in de ramadan?',
      de: 'Welche Erfahrung haben Sie mit dem Fasten im Ramadan?',
    },
    secenekler: [
      {
        tr: 'Henüz oruç tutmadım',
        fr: "Je n’ai pas encore jeûné",
        en: 'I have not fasted yet',
        nl: 'Ik heb nog niet gevast',
        de: 'Ich habe noch nicht gefastet',
      },
      {
        tr: 'Birkaç gün tuttum',
        fr: "J’ai jeûné quelques jours",
        en: 'I have fasted a few days',
        nl: 'Ik heb enkele dagen gevast',
        de: 'Ich habe einige Tage gefastet',
      },
      {
        tr: "Ramazan’ın bir bölümünü tuttum",
        fr: "J’ai jeûné une partie du ramadan",
        en: 'I have fasted part of Ramadan',
        nl: 'Ik heb een deel van de ramadan gevast',
        de: 'Ich habe einen Teil des Ramadans gefastet',
      },
      {
        tr: "Bir Ramazan’ı baştan sona tuttum",
        fr: "J’ai jeûné un ramadan en entier",
        en: 'I have fasted a whole Ramadan',
        nl: 'Ik heb een hele ramadan gevast',
        de: 'Ich habe einen ganzen Ramadan gefastet',
      },
      {
        tr: 'Her yıl Ramazan orucunu tutuyorum',
        fr: 'Je jeûne le ramadan chaque année',
        en: 'I fast Ramadan every year',
        nl: 'Ik vast elk jaar de ramadan',
        de: 'Ich faste jedes Jahr den Ramadan',
      },
    ],
  },
  {
    id: 'by10',
    kume: 'uygulama',
    soru: {
      tr: 'Dua etme alışkanlığınız nasıl?',
      fr: "Comment décririez-vous votre habitude d’invoquer Dieu (du’â) ?",
      en: "How would you describe your habit of supplication (du’a)?",
      nl: "Hoe zou u uw gewoonte om tot God te bidden (doea) beschrijven?",
      de: "Wie würden Sie Ihre Gewohnheit beschreiben, Gott anzurufen (Dua)?",
    },
    secenekler: [
      {
        tr: 'Henüz nasıl dua edeceğimi bilmiyorum',
        fr: 'Je ne sais pas encore comment faire',
        en: 'I do not know how yet',
        nl: 'Ik weet nog niet hoe dat moet',
        de: 'Ich weiß noch nicht, wie das geht',
      },
      {
        tr: 'Kendi dilimde, içimden geldiği gibi dua ediyorum',
        fr: 'Je prie dans ma propre langue, avec mes mots',
        en: 'I pray in my own language, in my own words',
        nl: 'Ik bid in mijn eigen taal, met mijn eigen woorden',
        de: 'Ich bete in meiner eigenen Sprache, mit meinen eigenen Worten',
      },
      {
        tr: 'Ezberimdeki kısa duaları okuyorum',
        fr: 'Je récite les courtes invocations que je connais par cœur',
        en: 'I recite the short supplications I know by heart',
        nl: 'Ik zeg de korte smeekbeden op die ik uit het hoofd ken',
        de: 'Ich spreche die kurzen Bittgebete, die ich auswendig kann',
      },
      {
        tr: 'Günlük duaları düzenli olarak okuyorum',
        fr: 'Je récite régulièrement les invocations quotidiennes',
        en: 'I recite the daily supplications regularly',
        nl: 'Ik zeg de dagelijkse smeekbeden regelmatig op',
        de: 'Ich spreche die täglichen Bittgebete regelmäßig',
      },
    ],
  },
  {
    id: 'by11',
    kume: 'uygulama',
    soru: {
      tr: 'Helal gıda konusunda kendinizi ne kadar bilgili hissediyorsunuz?',
      fr: "Dans quelle mesure vous sentez-vous informé(e) au sujet de l’alimentation halal ?",
      en: 'How informed do you feel about halal food?',
      nl: 'Hoe goed voelt u zich geïnformeerd over halalvoeding?',
      de: 'Wie gut fühlen Sie sich über Halal-Ernährung informiert?',
    },
    secenekler: [
      {
        tr: 'Henüz bilgim yok',
        fr: 'Pas encore informé(e)',
        en: 'Not informed yet',
        nl: 'Nog niet geïnformeerd',
        de: 'Noch nicht informiert',
      },
      {
        tr: 'Temelini biliyorum, ayrıntılarda zorlanıyorum',
        fr: 'Je connais les bases, les détails me posent problème',
        en: 'I know the basics but struggle with the details',
        nl: 'Ik ken de basis, met de details heb ik moeite',
        de: 'Ich kenne die Grundlagen, mit den Einzelheiten tue ich mich schwer',
      },
      {
        tr: 'Alışverişte etiketlere bakacak kadar biliyorum',
        fr: "J’en sais assez pour lire les étiquettes en faisant mes courses",
        en: 'I know enough to check labels when shopping',
        nl: 'Ik weet genoeg om bij het winkelen de etiketten te lezen',
        de: 'Ich weiß genug, um beim Einkaufen die Etiketten zu lesen',
      },
      {
        tr: 'Rahatım; başkasına da anlatabilirim',
        fr: "Je suis à l’aise et je peux l’expliquer à quelqu’un d’autre",
        en: 'I feel at ease and could explain it to someone else',
        nl: 'Ik voel me op mijn gemak en kan het aan anderen uitleggen',
        de: 'Ich fühle mich sicher und kann es anderen erklären',
      },
    ],
  },
  {
    id: 'by12',
    kume: 'uygulama',
    soru: {
      tr: 'Camiye ne sıklıkla geliyorsunuz?',
      fr: 'À quelle fréquence venez-vous à la mosquée ?',
      en: 'How often do you come to the mosque?',
      nl: 'Hoe vaak komt u naar de moskee?',
      de: 'Wie oft kommen Sie in die Moschee?',
    },
    secenekler: [
      {
        tr: 'Henüz gelmedim',
        fr: 'Pas encore venu(e)',
        en: 'I have not come yet',
        nl: 'Nog niet geweest',
        de: 'Noch nicht gewesen',
      },
      {
        tr: 'Yılda birkaç kez',
        fr: 'Quelques fois par an',
        en: 'A few times a year',
        nl: 'Enkele keren per jaar',
        de: 'Ein paar Mal im Jahr',
      },
      {
        tr: 'Ayda birkaç kez',
        fr: 'Quelques fois par mois',
        en: 'A few times a month',
        nl: 'Enkele keren per maand',
        de: 'Ein paar Mal im Monat',
      },
      {
        tr: 'Haftada en az bir kez',
        fr: 'Au moins une fois par semaine',
        en: 'At least once a week',
        nl: 'Minstens één keer per week',
        de: 'Mindestens einmal pro Woche',
      },
      {
        tr: 'Hemen her gün',
        fr: 'Presque tous les jours',
        en: 'Almost every day',
        nl: 'Bijna elke dag',
        de: 'Fast jeden Tag',
      },
    ],
  },
  {
    id: 'by13',
    kume: 'uygulama',
    soru: {
      tr: 'Sizin için en verimli öğrenme biçimi hangisi?',
      fr: "Quelle façon d’apprendre vous convient le mieux ?",
      en: 'Which way of learning suits you best?',
      nl: 'Welke manier van leren past het best bij u?',
      de: 'Welche Art zu lernen passt am besten zu Ihnen?',
    },
    secenekler: [
      {
        tr: 'Okuyarak',
        fr: 'En lisant',
        en: 'By reading',
        nl: 'Door te lezen',
        de: 'Durch Lesen',
      },
      {
        tr: 'Dinleyerek ve izleyerek',
        fr: 'En écoutant et en regardant',
        en: 'By listening and watching',
        nl: 'Door te luisteren en te kijken',
        de: 'Durch Zuhören und Zuschauen',
      },
      {
        tr: 'Uygulayarak, birlikte yaparak',
        fr: 'En pratiquant, en faisant ensemble',
        en: 'By practising, doing it together',
        nl: 'Door te oefenen en het samen te doen',
        de: 'Durch Üben und gemeinsames Tun',
      },
      {
        tr: 'Birebir soru-cevapla',
        fr: 'En posant des questions en tête-à-tête',
        en: 'Through one-to-one questions and answers',
        nl: 'Door vragen te stellen, één op één',
        de: 'Durch Fragen und Antworten im Einzelgespräch',
      },
    ],
  },
];
