/** Seviye testi soru bankası — kuran-bilgi (içerik yazımı sürüyor; docs/SEVIYE-TESTI.md kılavuzu). */
import type { BilgiMaddesi } from '../tipler.ts';

export const KURAN_BILGI: BilgiMaddesi[] = [
  // ——— B1: ilk haftalarda öğrenilen temel bilgi ———
  {
    id: 'kb01',
    tur: 'bilgi',
    alan: 'kuranBilgi',
    basamak: 1,
    soru: {
      tr: 'Kur’an-ı Kerim hangi peygambere ve hangi dilde indirilmiştir?',
      fr: 'À quel prophète et dans quelle langue le Coran a-t-il été révélé ?',
      en: 'To which prophet and in which language was the Qur’an revealed?',
      nl: 'Aan welke profeet en in welke taal is de Koran geopenbaard?',
      de: 'Welchem Propheten und in welcher Sprache wurde der Koran offenbart?',
    },
    siklar: [
      {
        tr: 'Hz. Mûsâ’ya (a.s.), İbrânîce',
        fr: 'Au prophète Moïse (Moussa), en hébreu',
        en: 'To Prophet Moses (Musa), in Hebrew',
        nl: 'Aan de profeet Mozes (Moesa), in het Hebreeuws',
        de: 'Dem Propheten Moses (Musa), auf Hebräisch',
      },
      {
        tr: 'Hz. Îsâ’ya (a.s.), Süryânîce',
        fr: 'Au prophète Jésus (Issa), en syriaque',
        en: 'To Prophet Jesus (Isa), in Syriac',
        nl: 'Aan de profeet Jezus (Isa), in het Syrisch',
        de: 'Dem Propheten Jesus (Isa), auf Syrisch',
      },
      {
        tr: 'Hz. Muhammed’e (s.a.s.), Arapça',
        fr: 'Au prophète Muhammad (paix et salut sur lui), en arabe',
        en: 'To Prophet Muhammad (peace be upon him), in Arabic',
        nl: 'Aan de profeet Mohammed (vrede zij met hem), in het Arabisch',
        de: 'Dem Propheten Muhammad (Friede sei mit ihm), auf Arabisch',
      },
      {
        tr: 'Hz. Muhammed’e (s.a.s.), Farsça',
        fr: 'Au prophète Muhammad (paix et salut sur lui), en persan',
        en: 'To Prophet Muhammad (peace be upon him), in Persian',
        nl: 'Aan de profeet Mohammed (vrede zij met hem), in het Perzisch',
        de: 'Dem Propheten Muhammad (Friede sei mit ihm), auf Persisch',
      },
    ],
    dogru: 2,
    kaynak: 'TDV İslâm Ansiklopedisi, «Kur’an» maddesi — https://islamansiklopedisi.org.tr/kuran (Arapça olarak Hz. Muhammed’e indirilmiştir)',
  },
  {
    id: 'kb02',
    tur: 'bilgi',
    alan: 'kuranBilgi',
    basamak: 1,
    soru: {
      tr: 'Kur’an-ı Kerim’in en başında yer alan, adı «açılış» anlamına gelen sûre hangisidir?',
      fr: 'Quelle est la sourate placée tout au début du Coran, dont le nom signifie « l’ouverture » ?',
      en: 'Which surah stands at the very beginning of the Qur’an and has a name meaning “the opening”?',
      nl: 'Welke soera staat helemaal aan het begin van de Koran en draagt een naam die “de opening” betekent?',
      de: 'Welche Sure steht ganz am Anfang des Korans und trägt einen Namen, der „die Eröffnung“ bedeutet?',
    },
    siklar: [
      { tr: 'İhlâs sûresi', fr: 'Sourate Al-Ikhlas', en: 'Surah Al-Ikhlas', nl: 'Soera Al-Ichlas', de: 'Sure Al-Ichlas' },
      { tr: 'Fâtiha sûresi', fr: 'Sourate Al-Fatiha', en: 'Surah Al-Fatiha', nl: 'Soera Al-Fatiha', de: 'Sure Al-Fatiha' },
      { tr: 'Bakara sûresi', fr: 'Sourate Al-Baqara', en: 'Surah Al-Baqara', nl: 'Soera Al-Baqara', de: 'Sure Al-Baqara' },
      { tr: 'Yâsîn sûresi', fr: 'Sourate Ya-Sin', en: 'Surah Ya-Sin', nl: 'Soera Ya-Sien', de: 'Sure Ya-Sin' },
    ],
    dogru: 1,
    kaynak: 'TDV İslâm Ansiklopedisi, «Fâtiha Sûresi» maddesi — https://islamansiklopedisi.org.tr/fatiha-suresi (Kur’an’ın tertibi itibariyle birinci sûre)',
  },
  {
    id: 'kb03',
    tur: 'bilgi',
    alan: 'kuranBilgi',
    basamak: 1,
    soru: {
      tr: 'Kur’an-ı Kerim kaç sûreden oluşur?',
      fr: 'Le Coran est composé de combien de sourates ?',
      en: 'How many surahs does the Qur’an consist of?',
      nl: 'Uit hoeveel soera’s bestaat de Koran?',
      de: 'Aus wie vielen Suren besteht der Koran?',
    },
    siklar: [
      { tr: '99 sûre', fr: '99 sourates', en: '99 surahs', nl: '99 soera’s', de: '99 Suren' },
      { tr: '104 sûre', fr: '104 sourates', en: '104 surahs', nl: '104 soera’s', de: '104 Suren' },
      { tr: '110 sûre', fr: '110 sourates', en: '110 surahs', nl: '110 soera’s', de: '110 Suren' },
      { tr: '114 sûre', fr: '114 sourates', en: '114 surahs', nl: '114 soera’s', de: '114 Suren' },
    ],
    dogru: 3,
    kaynak: 'TDV İslâm Ansiklopedisi, «Kur’an» maddesi — https://islamansiklopedisi.org.tr/kuran («Hz. Osman’ın mushaflarına göre Kur’an’da 114 sûre bulunmaktadır»)',
  },
  {
    id: 'kb04',
    tur: 'bilgi',
    alan: 'kuranBilgi',
    basamak: 1,
    soru: {
      tr: '«Yaratan Rabbinin adıyla oku!» âyetiyle başlayan ilk vahiy, hangi sûrenin ilk âyetleridir?',
      fr: 'La première révélation, qui commence par « Lis, au nom de ton Seigneur qui a créé ! », forme les premiers versets de quelle sourate ?',
      en: 'The first revelation, which begins “Read, in the name of your Lord who created”, forms the opening verses of which surah?',
      nl: 'De eerste openbaring, die begint met “Lees, in de naam van uw Heer die geschapen heeft!”, vormt de eerste verzen van welke soera?',
      de: 'Die erste Offenbarung, die mit „Lies, im Namen deines Herrn, der erschaffen hat!“ beginnt, bildet die ersten Verse welcher Sure?',
    },
    siklar: [
      { tr: 'Alak sûresi', fr: 'Sourate Al-Alaq', en: 'Surah Al-Alaq', nl: 'Soera Al-Alaq', de: 'Sure Al-Alaq' },
      { tr: 'Kalem sûresi', fr: 'Sourate Al-Qalam', en: 'Surah Al-Qalam', nl: 'Soera Al-Qalam', de: 'Sure Al-Qalam' },
      { tr: 'Müddessir sûresi', fr: 'Sourate Al-Mouddaththir', en: 'Surah Al-Muddaththir', nl: 'Soera Al-Moeddaththir', de: 'Sure Al-Muddaththir' },
      { tr: 'Duhâ sûresi', fr: 'Sourate Ad-Douha', en: 'Surah Ad-Duha', nl: 'Soera Ad-Doeha', de: 'Sure Ad-Duha' },
    ],
    dogru: 0,
    kaynak:
      'Diyanet Kur’an portalı, Alak 96/1 — https://kuran.diyanet.gov.tr/mushaf/kuran-meal-2/alak-suresi-96/ayet-1/diyanet-isleri-baskanligi-meali-1 («Yaratan Rabbinin adıyla oku!»); TDV İslâm Ansiklopedisi, «Kur’an» — https://islamansiklopedisi.org.tr/kuran',
  },

  // ——— B2: düzenli ibadet eden birinin bildiği uygulama bilgisi ———
  {
    id: 'kb05',
    tur: 'bilgi',
    alan: 'kuranBilgi',
    basamak: 2,
    soru: {
      tr: 'Kur’an-ı Kerim yaklaşık yirmi üç yıl boyunca parça parça indirilmiştir. Hicretten önce inen sûrelere ne ad verilir?',
      fr: 'Le Coran a été révélé progressivement pendant environ vingt-trois ans. Comment appelle-t-on les sourates révélées avant l’Hégire ?',
      en: 'The Qur’an was revealed gradually over about twenty-three years. What are the surahs revealed before the Hijrah called?',
      nl: 'De Koran is in ongeveer drieëntwintig jaar stukje bij beetje geopenbaard. Hoe noemt men de soera’s die vóór de hidjra zijn geopenbaard?',
      de: 'Der Koran wurde über etwa dreiundzwanzig Jahre hinweg nach und nach offenbart. Wie nennt man die Suren, die vor der Hidschra offenbart wurden?',
    },
    siklar: [
      {
        tr: 'Medenî sûreler',
        fr: 'Les sourates médinoises (madani)',
        en: 'Medinan (madani) surahs',
        nl: 'De Medinese soera’s (madani)',
        de: 'Die medinensischen Suren (madani)',
      },
      {
        tr: 'Mekkî sûreler',
        fr: 'Les sourates mecquoises (makki)',
        en: 'Meccan (makki) surahs',
        nl: 'De Mekkaanse soera’s (makki)',
        de: 'Die mekkanischen Suren (makki)',
      },
      {
        tr: 'Mufassal sûreler',
        fr: 'Les sourates moufassal',
        en: 'Mufassal surahs',
        nl: 'De moefassal-soera’s',
        de: 'Die Mufassal-Suren',
      },
      {
        tr: 'Mesânî sûreler',
        fr: 'Les sourates mathani',
        en: 'Mathani surahs',
        nl: 'De mathani-soera’s',
        de: 'Die Mathani-Suren',
      },
    ],
    dogru: 1,
    kaynak: 'TDV İslâm Ansiklopedisi, «Kur’an» maddesi — https://islamansiklopedisi.org.tr/kuran («hicretten önce nâzil olan âyet ve sûrelerin Mekkî, hicretten sonra nâzil olanların Medenî sayılması»)',
  },
  {
    id: 'kb06',
    tur: 'bilgi',
    alan: 'kuranBilgi',
    basamak: 2,
    soru: {
      tr: 'Kur’an-ı Kerim indirildiği günden bu yana hem yazıyla hem de ezberlenerek korunmuştur. Kur’an’ın tamamını ezberleyen kişiye ne ad verilir?',
      fr: 'Depuis sa révélation, le Coran a été préservé à la fois par l’écrit et par la mémorisation. Comment appelle-t-on la personne qui a mémorisé le Coran en entier ?',
      en: 'Since its revelation the Qur’an has been preserved both in writing and by memorisation. What is a person who has memorised the whole Qur’an called?',
      nl: 'Sinds de openbaring is de Koran zowel schriftelijk als door het uit het hoofd leren bewaard gebleven. Hoe noemt men iemand die de hele Koran uit het hoofd kent?',
      de: 'Seit seiner Offenbarung wird der Koran sowohl schriftlich als auch durch Auswendiglernen bewahrt. Wie nennt man jemanden, der den ganzen Koran auswendig kann?',
    },
    siklar: [
      {
        tr: 'Müfessir',
        fr: 'Un moufassir (exégète)',
        en: 'A mufassir (exegete)',
        nl: 'Een moefassir (uitlegger van de Koran)',
        de: 'Ein Mufassir (Koranausleger)',
      },
      {
        tr: 'Müezzin',
        fr: 'Un mouezzin',
        en: 'A muezzin',
        nl: 'Een muezzin',
        de: 'Ein Muezzin',
      },
      {
        tr: 'Muhaddis',
        fr: 'Un mouhaddith (savant du hadith)',
        en: 'A muhaddith (hadith scholar)',
        nl: 'Een moehaddith (hadithgeleerde)',
        de: 'Ein Muhaddith (Hadithgelehrter)',
      },
      {
        tr: 'Hâfız',
        fr: 'Un hafiz',
        en: 'A hafiz',
        nl: 'Een hafiz',
        de: 'Ein Hafiz',
      },
    ],
    dogru: 3,
    kaynak: 'TDV İslâm Ansiklopedisi, «Hâfız» maddesi — https://islamansiklopedisi.org.tr/hafiz--kuran («Kur’an’ın tamamını ezberleyene hâfız denilmiştir»)',
  },
  {
    id: 'kb07',
    tur: 'bilgi',
    alan: 'kuranBilgi',
    basamak: 2,
    soru: {
      tr: 'Kur’an-ı Kerim, okunmasını ve ezberlenmesini kolaylaştırmak için otuz bölüme ayrılmıştır. Bu bölümlerden her birine ne ad verilir?',
      fr: 'Pour faciliter la lecture et la mémorisation, le Coran est divisé en trente parties. Comment appelle-t-on chacune de ces parties ?',
      en: 'To make reading and memorising easier, the Qur’an is divided into thirty parts. What is each of these parts called?',
      nl: 'Om het lezen en het uit het hoofd leren te vergemakkelijken is de Koran in dertig delen verdeeld. Hoe noemt men elk van die delen?',
      de: 'Um das Lesen und das Auswendiglernen zu erleichtern, ist der Koran in dreißig Teile eingeteilt. Wie nennt man jeden dieser Teile?',
    },
    siklar: [
      { tr: 'Cüz', fr: 'Un jouz’', en: 'A juz', nl: 'Een djoez', de: 'Ein Dschuz' },
      { tr: 'Sûre', fr: 'Une sourate', en: 'A surah', nl: 'Een soera', de: 'Eine Sure' },
      { tr: 'Âyet', fr: 'Un verset (aya)', en: 'A verse (ayah)', nl: 'Een vers (aya)', de: 'Ein Vers (Aya)' },
      { tr: 'Mushaf', fr: 'Un moushaf', en: 'A mushaf', nl: 'Een moeshaf', de: 'Ein Mushaf' },
    ],
    dogru: 0,
    kaynak: 'Diyanet Kur’an portalı, Kur’an sözlüğü «Cüz» — https://kuran.diyanet.gov.tr/kuran-sozlugu/detay/34-cuz («Her yirmi sayfa bir cüz sayılmış, böylece Kur’ân 30 cüz’e bölünmüştür»)',
  },
  {
    id: 'kb08',
    tur: 'bilgi',
    alan: 'kuranBilgi',
    basamak: 2,
    soru: {
      tr: 'Kur’an âyetlerinin, anlamı esas alınarak başka bir dile aktarılmış hâline ne ad verilir?',
      fr: 'Comment appelle-t-on le rendu des versets du Coran dans une autre langue, fondé sur leur sens ?',
      en: 'What is the rendering of the Qur’an’s verses into another language, based on their meaning, called?',
      nl: 'Hoe noemt men de weergave van de Koranverzen in een andere taal, gebaseerd op hun betekenis?',
      de: 'Wie nennt man die Wiedergabe der Koranverse in einer anderen Sprache, die sich an ihrer Bedeutung orientiert?',
    },
    siklar: [
      {
        tr: 'Tefsir',
        fr: 'Le tafsir (exégèse)',
        en: 'Tafsir (exegesis)',
        nl: 'Tafsir (uitleg)',
        de: 'Tafsir (Auslegung)',
      },
      {
        tr: 'Tilâvet',
        fr: 'La tilawa (récitation)',
        en: 'Tilawah (recitation)',
        nl: 'Tilawa (recitatie)',
        de: 'Tilawa (Rezitation)',
      },
      {
        tr: 'Meâl',
        fr: 'Le meal (traduction du sens)',
        en: 'Meal (translation of the meaning)',
        nl: 'Meal (vertaling van de betekenis)',
        de: 'Meal (Übersetzung der Bedeutung)',
      },
      {
        tr: 'Kıraat',
        fr: 'La qiraa (lecture)',
        en: 'Qiraah (reading)',
        nl: 'Qiraa (lezing)',
        de: 'Qiraa (Lesung)',
      },
    ],
    dogru: 2,
    kaynak:
      'TDV İslâm Ansiklopedisi, «Meâl» maddesi — https://islamansiklopedisi.org.tr/meal ; «Tefsir» maddesi — https://islamansiklopedisi.org.tr/tefsir',
  },

  // ——— B3: tecvid kavramları (rapordaki «tecvid» işareti bu basamaktan gelir) ———
  {
    id: 'kb09',
    tur: 'bilgi',
    alan: 'kuranBilgi',
    basamak: 3,
    soru: {
      tr: 'Kur’an-ı Kerim’i harflerin hakkını vererek, kendine has kurallarına uygun biçimde okumayı öğreten ilme ne ad verilir?',
      fr: 'Comment appelle-t-on la science qui enseigne à réciter le Coran correctement, en donnant à chaque lettre son droit ?',
      en: 'What is the science that teaches reciting the Qur’an correctly, giving each letter its due, called?',
      nl: 'Hoe heet de wetenschap die leert de Koran correct te reciteren en elke letter haar recht te geven?',
      de: 'Wie heißt die Wissenschaft, die lehrt, den Koran richtig zu rezitieren und jedem Buchstaben sein Recht zu geben?',
    },
    siklar: [
      { tr: 'Tefsir', fr: 'Le tafsir', en: 'Tafsir', nl: 'Tafsir', de: 'Tafsir' },
      { tr: 'Tecvid', fr: 'Le tajwid', en: 'Tajwid', nl: 'Tadjwied', de: 'Tadschwid' },
      { tr: 'Siyer', fr: 'La sira', en: 'Sirah', nl: 'Sira', de: 'Sira' },
      { tr: 'Fıkıh', fr: 'Le fiqh', en: 'Fiqh', nl: 'Fiqh', de: 'Fiqh' },
    ],
    dogru: 1,
    kaynak: 'TDV İslâm Ansiklopedisi, «Tecvid» maddesi — https://islamansiklopedisi.org.tr/tecvid--kuran («Kur’ân-ı Kerîm’i harflerin mahreç ve sıfatlarına riayet edip … güzel ve hatasız okumayı öğreten ilim»)',
  },
  {
    id: 'kb10',
    tur: 'bilgi',
    alan: 'kuranBilgi',
    basamak: 3,
    soru: {
      tr: 'Tecvidde bir harfin sesinin uzatılmasına «med» denir. Bu uzatmayı sağlayan üç med harfi hangileridir?',
      fr: 'En tajwid, l’allongement du son d’une lettre s’appelle le madd. Quelles sont les trois lettres d’allongement (hourouf al-madd) ?',
      en: 'In tajwid, lengthening the sound of a letter is called madd. Which are the three letters of prolongation (huruf al-madd)?',
      nl: 'In de tadjwied heet het verlengen van de klank van een letter madd. Welke zijn de drie verlengingsletters (hoeroef al-madd)?',
      de: 'Im Tadschwid heißt die Dehnung des Lautes eines Buchstabens Madd. Welches sind die drei Dehnungsbuchstaben (Huruf al-Madd)?',
    },
    siklar: [
      { tr: 'Elif, vav, ye', fr: 'Alif, waw, ya', en: 'Alif, waw, ya', nl: 'Alif, waw, ya', de: 'Alif, Waw, Ya' },
      { tr: 'Be, cim, dal', fr: 'Ba, jim, dal', en: 'Ba, jim, dal', nl: 'Ba, djiem, dal', de: 'Ba, Dschim, Dal' },
      { tr: 'Sin, şın, ra', fr: 'Sin, chin, ra', en: 'Sin, shin, ra', nl: 'Sien, sjien, ra', de: 'Sin, Schin, Ra' },
      { tr: 'Mim, nun, lam', fr: 'Mim, noun, lam', en: 'Mim, nun, lam', nl: 'Miem, noen, lam', de: 'Mim, Nun, Lam' },
    ],
    dogru: 0,
    kaynak: 'TDV İslâm Ansiklopedisi, «Med» maddesi — https://islamansiklopedisi.org.tr/med (tabiî medlerin oluşumunda «med harfleri» [hurûf-ı med]: elif, vav, ye)',
  },
  {
    id: 'kb11',
    tur: 'bilgi',
    alan: 'kuranBilgi',
    basamak: 3,
    soru: {
      tr: 'Tecvidde, yan yana gelen iki harften birincisinin ikincisine katılarak tek harf gibi okunmasına ne ad verilir?',
      fr: 'En tajwid, comment appelle-t-on le fait de fondre la première de deux lettres voisines dans la seconde, de sorte qu’elles se prononcent comme une seule ?',
      en: 'In tajwid, what is it called when the first of two adjacent letters is merged into the second so that they are pronounced as one?',
      nl: 'Hoe heet het in de tadjwied wanneer de eerste van twee opeenvolgende letters opgaat in de tweede, zodat beide als één letter klinken?',
      de: 'Wie heißt es im Tadschwid, wenn der erste von zwei aufeinanderfolgenden Buchstaben in den zweiten übergeht, sodass beide wie ein Buchstabe klingen?',
    },
    siklar: [
      { tr: 'İzhâr', fr: 'L’izhar', en: 'Izhar', nl: 'Izhar', de: 'Izhar' },
      { tr: 'İhfâ', fr: 'L’ikhfa', en: 'Ikhfa', nl: 'Ichfa', de: 'Ichfa' },
      { tr: 'İdgam', fr: 'L’idgham', en: 'Idgham', nl: 'Idgham', de: 'Idgham' },
      { tr: 'Med', fr: 'Le madd', en: 'Madd', nl: 'Madd', de: 'Madd' },
    ],
    dogru: 2,
    kaynak:
      'TDV İslâm Ansiklopedisi, «İdgam» maddesi — https://islamansiklopedisi.org.tr/idgam («iki harften ilkini ikinciye katarak telaffuz etmek») ; «İhfâ» — https://islamansiklopedisi.org.tr/ihfa ; «İzhar» — https://islamansiklopedisi.org.tr/izhar--tecvid',
  },
  {
    id: 'kb12',
    tur: 'bilgi',
    alan: 'kuranBilgi',
    basamak: 3,
    soru: {
      tr: 'Tecvidde, sükûn hâlindeyken mahreçleri sarsılarak kuvvetli bir sesle okunan harflere «kalkale harfleri» denir. Bu harfler hangileridir?',
      fr: 'En tajwid, les lettres qui, portant un soukoun, se prononcent avec un rebond sonore s’appellent les lettres de la qalqala. Lesquelles sont-ce ?',
      en: 'In tajwid, the letters pronounced with a bounce when they carry a sukun are called the letters of qalqalah. Which are they?',
      nl: 'In de tadjwied heten de letters die met een hoorbare terugkaatsing worden uitgesproken wanneer zij een soekoen dragen, de letters van de qalqala. Welke zijn dat?',
      de: 'Im Tadschwid heißen die Buchstaben, die mit einem hörbaren Abprallen gesprochen werden, wenn sie ein Sukun tragen, die Buchstaben der Qalqala. Welche sind das?',
    },
    siklar: [
      {
        tr: 'Elif, vav, ye',
        fr: 'Alif, waw, ya',
        en: 'Alif, waw, ya',
        nl: 'Alif, waw, ya',
        de: 'Alif, Waw, Ya',
      },
      {
        tr: 'Hemze, he, ayn, hı',
        fr: 'Hamza, ha, ayn, kha',
        en: 'Hamza, ha, ayn, kha',
        nl: 'Hamza, ha, ain, cha',
        de: 'Hamza, Ha, Ain, Cha',
      },
      {
        tr: 'Mim, nun, lam, ra',
        fr: 'Mim, noun, lam, ra',
        en: 'Mim, nun, lam, ra',
        nl: 'Miem, noen, lam, ra',
        de: 'Mim, Nun, Lam, Ra',
      },
      {
        tr: 'Be, cim, dal, tı, kaf',
        fr: 'Ba, jim, dal, ta, qaf',
        en: 'Ba, jim, dal, ta, qaf',
        nl: 'Ba, djiem, dal, ta, qaf',
        de: 'Ba, Dschim, Dal, Ta, Qaf',
      },
    ],
    dogru: 3,
    kaynak: 'TDV İslâm Ansiklopedisi, «Kalkale» maddesi — https://islamansiklopedisi.org.tr/kalkale (sükûn hâlindeki be, cim, dal, tı, kaf harflerinin mahreçlerinin sarsılarak okunması)',
  },
];
