/** Seviye testi soru bankası — namaz (içerik yazımı sürüyor; docs/SEVIYE-TESTI.md kılavuzu). */
import type { BilgiMaddesi } from '../tipler.ts';

export const NAMAZ: BilgiMaddesi[] = [
  // ——— B1: ilk haftalarda öğrenilen temel bilgi ———
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 1,
    id: 'nm01',
    soru: {
      tr: "Namaz kılabilmek için namazdan önce hangisini yapmak gerekir?",
      fr: "Que faut-il faire avant d’accomplir la prière (salât) ?",
      en: "What needs to be done before performing the prayer (salah)?",
      nl: "Wat moet men doen voordat men het gebed (salat) verricht?",
      de: "Was muss man tun, bevor man das Gebet (Salat) verrichtet?",
    },
    siklar: [
      {
        tr: "Sadaka vermek",
        fr: "Donner une aumône (sadaqa)",
        en: "Give charity (sadaqah)",
        nl: "Een aalmoes (sadaka) geven",
        de: "Ein Almosen (Sadaka) geben",
      },
      {
        tr: "Abdest almak",
        fr: "Faire les ablutions (woudou)",
        en: "Perform the ablution (wudu)",
        nl: "De wudu (rituele wassing) verrichten",
        de: "Die rituelle Waschung (Wudu) vollziehen",
      },
      { tr: "Oruç tutmak", fr: "Jeûner (sawm)", en: "Fast (sawm)", nl: "Vasten (sawm)", de: "Fasten (Sawm)" },
      {
        tr: "Kurban kesmek",
        fr: "Sacrifier un animal (qourbani)",
        en: "Offer a sacrifice (qurbani)",
        nl: "Een dier offeren (kurban)",
        de: "Ein Tier opfern (Kurban)",
      },
    ],
    dogru: 1,
    kaynak: "TDV İslâm Ansiklopedisi, «Abdest» — https://islamansiklopedisi.org.tr/abdest (abdest namazın şartıdır; Mâide 5/6)",
  },
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 1,
    id: 'nm02',
    soru: {
      tr: "Beş vakit namazın adları aşağıdakilerden hangisinde doğru sırayla verilmiştir?",
      fr: "Dans quelle réponse les cinq prières quotidiennes sont-elles citées dans le bon ordre ?",
      en: "Which answer lists the five daily prayers in the correct order?",
      nl: "In welk antwoord staan de vijf dagelijkse gebeden in de juiste volgorde?",
      de: "In welcher Antwort stehen die fünf täglichen Gebete in der richtigen Reihenfolge?",
    },
    siklar: [
      {
        tr: "Sabah, öğle, ikindi, akşam, yatsı",
        fr: "Fajr (aube), dhouhr (midi), asr (après-midi), maghrib (coucher), icha (nuit)",
        en: "Fajr (dawn), dhuhr (noon), asr (afternoon), maghrib (sunset), isha (night)",
        nl: "Fajr (ochtendgebed), dhuhr (middaggebed), asr (namiddaggebed), maghrib (avondgebed), isha (nachtgebed)",
        de: "Fadschr (Morgengebet), Dhuhr (Mittagsgebet), Asr (Nachmittagsgebet), Maghrib (Abendgebet), Ischa (Nachtgebet)",
      },
      {
        tr: "Sabah, ikindi, öğle, akşam, yatsı",
        fr: "Fajr (aube), asr (après-midi), dhouhr (midi), maghrib (coucher), icha (nuit)",
        en: "Fajr (dawn), asr (afternoon), dhuhr (noon), maghrib (sunset), isha (night)",
        nl: "Fajr (ochtendgebed), asr (namiddaggebed), dhuhr (middaggebed), maghrib (avondgebed), isha (nachtgebed)",
        de: "Fadschr (Morgengebet), Asr (Nachmittagsgebet), Dhuhr (Mittagsgebet), Maghrib (Abendgebet), Ischa (Nachtgebet)",
      },
      {
        tr: "Öğle, sabah, ikindi, yatsı, akşam",
        fr: "Dhouhr (midi), fajr (aube), asr (après-midi), icha (nuit), maghrib (coucher)",
        en: "Dhuhr (noon), fajr (dawn), asr (afternoon), isha (night), maghrib (sunset)",
        nl: "Dhuhr (middaggebed), fajr (ochtendgebed), asr (namiddaggebed), isha (nachtgebed), maghrib (avondgebed)",
        de: "Dhuhr (Mittagsgebet), Fadschr (Morgengebet), Asr (Nachmittagsgebet), Ischa (Nachtgebet), Maghrib (Abendgebet)",
      },
      {
        tr: "Sabah, öğle, akşam, ikindi, yatsı",
        fr: "Fajr (aube), dhouhr (midi), maghrib (coucher), asr (après-midi), icha (nuit)",
        en: "Fajr (dawn), dhuhr (noon), maghrib (sunset), asr (afternoon), isha (night)",
        nl: "Fajr (ochtendgebed), dhuhr (middaggebed), maghrib (avondgebed), asr (namiddaggebed), isha (nachtgebed)",
        de: "Fadschr (Morgengebet), Dhuhr (Mittagsgebet), Maghrib (Abendgebet), Asr (Nachmittagsgebet), Ischa (Nachtgebet)",
      },
    ],
    dogru: 0,
    kaynak: "TDV İslâm Ansiklopedisi, «Namaz» — https://islamansiklopedisi.org.tr/namaz (beş vakit namaz)",
  },
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 1,
    id: 'nm03',
    soru: {
      tr: "Müslümanlar namaz kılarken hangi yöne dönerler?",
      fr: "Vers quoi vous tournez-vous pendant la prière (salât) ?",
      en: "What do Muslims turn towards during the prayer (salah)?",
      nl: "Naar welke richting keren moslims zich tijdens het gebed (salat)?",
      de: "In welche Richtung wenden sich Muslime während des Gebets (Salat)?",
    },
    siklar: [
      {
        tr: "Kudüs’teki Mescid-i Aksâ’ya",
        fr: "Vers la mosquée Al-Aqsa à Jérusalem",
        en: "Towards the Al-Aqsa Mosque in Jerusalem",
        nl: "Naar de Al-Aqsamoskee in Jeruzalem",
        de: "Zur Al-Aqsa-Moschee in Jerusalem",
      },
      {
        tr: "Medine’deki Mescid-i Nebevî’ye",
        fr: "Vers la mosquée du Prophète à Médine",
        en: "Towards the Prophet’s Mosque in Medina",
        nl: "Naar de Profeetsmoskee in Medina",
        de: "Zur Prophetenmoschee in Medina",
      },
      {
        tr: "Mekke’deki Kâbe’ye",
        fr: "Vers la Kaaba à La Mecque",
        en: "Towards the Kaaba in Mecca",
        nl: "Naar de Kaaba in Mekka",
        de: "Zur Kaaba in Mekka",
      },
      {
        tr: "Güneşin doğduğu yöne",
        fr: "Vers l’endroit où le soleil se lève",
        en: "Towards the place where the sun rises",
        nl: "Naar de plaats waar de zon opkomt",
        de: "Zu der Stelle, an der die Sonne aufgeht",
      },
    ],
    dogru: 2,
    kaynak: "TDV İslâm Ansiklopedisi, «Kıble» — https://islamansiklopedisi.org.tr/kible (Bakara 2/144)",
  },
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 1,
    id: 'nm04',
    soru: {
      tr: "Câminin minaresinden okunan ve namaz vaktinin girdiğini bildiren çağrının adı nedir?",
      fr: "Comment s’appelle l’annonce lancée du haut du minaret pour signaler que l’heure de la prière est arrivée ?",
      en: "What is the name of the call made from the minaret to announce that a prayer time has begun?",
      nl: "Hoe heet de oproep die vanaf de minaret van de moskee klinkt en aankondigt dat de gebedstijd is aangebroken?",
      de: "Wie heißt der Ruf, der vom Minarett der Moschee erklingt und ankündigt, dass die Gebetszeit begonnen hat?",
    },
    siklar: [
      { tr: "Kamet", fr: "L’iqama", en: "The iqamah", nl: "De iqama", de: "Die Iqama" },
      { tr: "Hutbe", fr: "La khoutba", en: "The khutbah", nl: "De khutba", de: "Die Chutba" },
      { tr: "Tekbir", fr: "Le takbir", en: "The takbir", nl: "De takbir", de: "Der Takbir" },
      { tr: "Ezan", fr: "L’adhan", en: "The adhan", nl: "De adhan", de: "Der Adhan" },
    ],
    dogru: 3,
    kaynak: "TDV İslâm Ansiklopedisi, «Ezan» — https://islamansiklopedisi.org.tr/ezan",
  },
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 1,
    id: 'nm05',
    soru: {
      tr: "Cuma namazı hangi gün, hangi vakitte ve nasıl kılınır?",
      fr: "Quel jour, à quel moment et comment la prière du vendredi (djoumou’a) est-elle accomplie ?",
      en: "On which day, at what time and how is the Friday prayer (jumu’ah) performed?",
      nl: "Op welke dag, op welk tijdstip en hoe wordt het vrijdaggebed (djoemoe’a) verricht?",
      de: "An welchem Tag, zu welcher Zeit und wie wird das Freitagsgebet (Dschumu’a) verrichtet?",
    },
    siklar: [
      {
        tr: "Cuma günü, öğle vaktinde ve cemaatle",
        fr: "Le vendredi, à l’heure de midi (dhouhr) et en communauté",
        en: "On Friday, at the noon (dhuhr) time and in congregation",
        nl: "Op vrijdag, op het tijdstip van dhuhr (middaggebed) en in gemeenschap",
        de: "Am Freitag, zur Dhuhr-Zeit (Mittagsgebet) und in Gemeinschaft",
      },
      {
        tr: "Cuma günü, sabah vaktinde ve tek başına",
        fr: "Le vendredi, à l’heure de l’aube (fajr) et seul",
        en: "On Friday, at the dawn (fajr) time and alone",
        nl: "Op vrijdag, op het tijdstip van fajr (ochtendgebed) en alleen",
        de: "Am Freitag, zur Fadschr-Zeit (Morgengebet) und allein",
      },
      {
        tr: "Perşembe günü, öğle vaktinde ve cemaatle",
        fr: "Le jeudi, à l’heure de midi (dhouhr) et en communauté",
        en: "On Thursday, at the noon (dhuhr) time and in congregation",
        nl: "Op donderdag, op het tijdstip van dhuhr (middaggebed) en in gemeenschap",
        de: "Am Donnerstag, zur Dhuhr-Zeit (Mittagsgebet) und in Gemeinschaft",
      },
      {
        tr: "Cuma günü, yatsı vaktinde ve tek başına",
        fr: "Le vendredi, à l’heure de la nuit (icha) et seul",
        en: "On Friday, at the night (isha) time and alone",
        nl: "Op vrijdag, op het tijdstip van isha (nachtgebed) en alleen",
        de: "Am Freitag, zur Ischa-Zeit (Nachtgebet) und allein",
      },
    ],
    dogru: 0,
    kaynak: "TDV İslâm Ansiklopedisi, «Cuma» — https://islamansiklopedisi.org.tr/cuma (öğle vakti, cemaat şartı)",
  },
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 1,
    id: 'nm06',
    soru: {
      tr: "Su bulunamadığında ya da kullanılamadığında abdest ve gusül yerine ne yapılır?",
      fr: "Lorsqu’il n’y a pas d’eau ou qu’on ne peut pas l’utiliser, que fait-on à la place des ablutions (woudou) et de la grande ablution (ghousl) ?",
      en: "When there is no water, or it cannot be used, what is done instead of ablution (wudu) and the full ablution (ghusl)?",
      nl: "Wat doet men in plaats van de wudu (rituele wassing) en de ghusl (volledige wassing) wanneer er geen water is of het water niet gebruikt kan worden?",
      de: "Was tut man anstelle der rituellen Waschung (Wudu) und der vollständigen Körperwaschung (Ghusl), wenn kein Wasser da ist oder es nicht benutzt werden kann?",
    },
    siklar: [
      {
        tr: "Su bulununcaya kadar namaz ertelenir",
        fr: "On reporte la prière jusqu’à trouver de l’eau",
        en: "The prayer is postponed until water is found",
        nl: "Het gebed wordt uitgesteld tot er water is gevonden",
        de: "Das Gebet wird verschoben, bis Wasser gefunden ist",
      },
      {
        tr: "Temiz toprağa el sürülerek teyemmüm yapılır",
        fr: "On fait l’ablution sèche (tayammoum) avec de la terre propre",
        en: "Dry ablution (tayammum) is done with clean earth",
        nl: "Men verricht de droge wassing (tayammum) met schone aarde",
        de: "Man vollzieht die trockene Waschung (Tayammum) mit sauberer Erde",
      },
      {
        tr: "Bir miktar sadaka verilerek namaz kılınır",
        fr: "On donne une aumône, puis on accomplit la prière",
        en: "Some charity is given and then the prayer is performed",
        nl: "Men geeft een aalmoes en verricht daarna het gebed",
        de: "Man gibt ein Almosen und verrichtet danach das Gebet",
      },
      {
        tr: "Yalnız eller yıkanarak namaz kılınır",
        fr: "On se lave seulement les mains, puis on prie",
        en: "Only the hands are washed and then the prayer is performed",
        nl: "Men wast alleen de handen en verricht daarna het gebed",
        de: "Man wäscht nur die Hände und verrichtet danach das Gebet",
      },
    ],
    dogru: 1,
    kaynak: "TDV İslâm Ansiklopedisi, «Teyemmüm» — https://islamansiklopedisi.org.tr/teyemmum (Mâide 5/6)",
  },

  // ——— B2: düzenli ibadet eden kişinin uygulama bilgisi ———
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 2,
    id: 'nm07',
    soru: {
      tr: "Beş vakit namazın farzları kaçar rekâttır?",
      fr: "Combien de rak’as comptent les parties obligatoires (fard) des cinq prières quotidiennes ?",
      en: "How many rak’ahs are the obligatory (fard) parts of the five daily prayers?",
      nl: "Uit hoeveel rak’a’s bestaan de verplichte delen (fard) van de vijf dagelijkse gebeden?",
      de: "Aus wie vielen Rak’as bestehen die Pflichtteile (Fard) der fünf täglichen Gebete?",
    },
    siklar: [
      {
        tr: "Sabah 2, öğle 4, ikindi 3, akşam 4, yatsı 4",
        fr: "Fajr 2, dhouhr 4, asr 3, maghrib 4, icha 4",
        en: "Fajr 2, dhuhr 4, asr 3, maghrib 4, isha 4",
        nl: "Fajr 2, dhuhr 4, asr 3, maghrib 4, isha 4",
        de: "Fadschr 2, Dhuhr 4, Asr 3, Maghrib 4, Ischa 4",
      },
      {
        tr: "Sabah 4, öğle 2, ikindi 4, akşam 3, yatsı 4",
        fr: "Fajr 4, dhouhr 2, asr 4, maghrib 3, icha 4",
        en: "Fajr 4, dhuhr 2, asr 4, maghrib 3, isha 4",
        nl: "Fajr 4, dhuhr 2, asr 4, maghrib 3, isha 4",
        de: "Fadschr 4, Dhuhr 2, Asr 4, Maghrib 3, Ischa 4",
      },
      {
        tr: "Sabah 2, öğle 4, ikindi 4, akşam 3, yatsı 4",
        fr: "Fajr 2, dhouhr 4, asr 4, maghrib 3, icha 4",
        en: "Fajr 2, dhuhr 4, asr 4, maghrib 3, isha 4",
        nl: "Fajr 2, dhuhr 4, asr 4, maghrib 3, isha 4",
        de: "Fadschr 2, Dhuhr 4, Asr 4, Maghrib 3, Ischa 4",
      },
      {
        tr: "Sabah 2, öğle 3, ikindi 4, akşam 4, yatsı 3",
        fr: "Fajr 2, dhouhr 3, asr 4, maghrib 4, icha 3",
        en: "Fajr 2, dhuhr 3, asr 4, maghrib 4, isha 3",
        nl: "Fajr 2, dhuhr 3, asr 4, maghrib 4, isha 3",
        de: "Fadschr 2, Dhuhr 3, Asr 4, Maghrib 4, Ischa 3",
      },
    ],
    dogru: 2,
    kaynak: "TDV İslâm Ansiklopedisi, «Namaz» — https://islamansiklopedisi.org.tr/namaz (farz rekâtları: 2-4-4-3-4)",
  },
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 2,
    id: 'nm08',
    soru: {
      tr: "Namazda elleri dizlerin üzerine koyarak öne eğilmeye ne ad verilir?",
      fr: "Comment appelle-t-on le fait de se pencher en avant en posant les mains sur les genoux pendant la prière ?",
      en: "What is the name for bending forward with the hands on the knees during prayer?",
      nl: "Hoe heet het vooroverbuigen met de handen op de knieën tijdens het gebed?",
      de: "Wie nennt man das Vorbeugen mit den Händen auf den Knien während des Gebets?",
    },
    siklar: [
      { tr: "Kıyam", fr: "Le qiyam", en: "Qiyam", nl: "Qiyam", de: "Qiyam" },
      { tr: "Rükû", fr: "Le roukou’", en: "Ruku", nl: "Roekoe", de: "Ruku" },
      { tr: "Secde", fr: "Le soujoud", en: "Sujud", nl: "Soedjoed", de: "Sudschud" },
      { tr: "Ka’de", fr: "La qa’da", en: "Qa’dah", nl: "Qa’da", de: "Qa’da" },
    ],
    dogru: 1,
    kaynak: "TDV İslâm Ansiklopedisi, «Rükû» — https://islamansiklopedisi.org.tr/ruku (namazın rükünlerinden)",
  },
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 2,
    id: 'nm09',
    soru: {
      tr: "Namazın her rekâtında ayakta iken her zaman okunan sûre hangisidir?",
      fr: "Quelle sourate récite-t-on toujours debout, à chaque rak’a de la prière ?",
      en: "Which surah is always recited while standing, in every rak’ah of the prayer?",
      nl: "Welke soera wordt in elke rak’a van het gebed altijd staand gereciteerd?",
      de: "Welche Sure wird in jeder Rak’a des Gebets immer im Stehen rezitiert?",
    },
    siklar: [
      { tr: "Fâtiha sûresi", fr: "La sourate Al-Fatiha", en: "Surah Al-Fatiha", nl: "Soera Al-Fatiha", de: "Sure Al-Fatiha" },
      { tr: "İhlâs sûresi", fr: "La sourate Al-Ikhlas", en: "Surah Al-Ikhlas", nl: "Soera Al-Ichlas", de: "Sure Al-Ichlas" },
      { tr: "Kevser sûresi", fr: "La sourate Al-Kawthar", en: "Surah Al-Kawthar", nl: "Soera Al-Kawthar", de: "Sure Al-Kawthar" },
      { tr: "Nas sûresi", fr: "La sourate An-Nas", en: "Surah An-Nas", nl: "Soera An-Nas", de: "Sure An-Nas" },
    ],
    dogru: 0,
    kaynak: "TDV İslâm Ansiklopedisi, «Namaz» — https://islamansiklopedisi.org.tr/namaz (namazın vâcipleri: «Namazların bütün rek’atlarında Fâtiha sûresini okumak»; fakihlerin çoğunluğuna göre farz)",
  },
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 2,
    id: 'nm10',
    soru: {
      tr: "Cünüplük hâlindeki bir kimse namaz kılabilmek için nasıl temizlenir?",
      fr: "Comment une personne en état d’impureté majeure (djanaba) se purifie-t-elle pour pouvoir prier ?",
      en: "How does a person in a state of major ritual impurity (janabah) purify themselves in order to pray?",
      nl: "Hoe reinigt iemand die in staat van grote rituele onreinheid (djanaba) verkeert zich om te kunnen bidden?",
      de: "Wie reinigt sich jemand, der sich im Zustand der großen rituellen Unreinheit (Dschanaba) befindet, um beten zu können?",
    },
    siklar: [
      {
        tr: "Yalnız yüzünü ve kollarını yıkar",
        fr: "Elle lave seulement le visage et les bras",
        en: "They wash only the face and the arms",
        nl: "Men wast alleen het gezicht en de armen",
        de: "Man wäscht nur Gesicht und Arme",
      },
      {
        tr: "Yalnız başını ve ayaklarını mesheder",
        fr: "Elle essuie seulement la tête et les pieds",
        en: "They wipe only the head and the feet",
        nl: "Men strijkt alleen over het hoofd en de voeten",
        de: "Man streicht nur über Kopf und Füße",
      },
      {
        tr: "Yalnız ellerini ve ağzını yıkar",
        fr: "Elle lave seulement les mains et la bouche",
        en: "They wash only the hands and the mouth",
        nl: "Men wast alleen de handen en de mond",
        de: "Man wäscht nur Hände und Mund",
      },
      {
        tr: "Bütün vücudunu yıkayarak gusül abdesti alır",
        fr: "Elle lave tout le corps : c’est la grande ablution (ghousl)",
        en: "They wash the whole body: this is the full ablution (ghusl)",
        nl: "Men wast het hele lichaam (ghusl)",
        de: "Man wäscht den ganzen Körper (Ghusl)",
      },
    ],
    dogru: 3,
    kaynak: "TDV İslâm Ansiklopedisi, «Gusül» — https://islamansiklopedisi.org.tr/gusul (cünüplük hâlinde gusül gerekir)",
  },
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 2,
    id: 'nm11',
    soru: {
      tr: "Namaz kılarken aşağıdaki davranışlardan hangisi namazı bozar?",
      fr: "Pendant la prière, lequel de ces comportements annule la prière ?",
      en: "During the prayer, which of these actions invalidates the prayer?",
      nl: "Welke van deze handelingen maakt het gebed ongeldig?",
      de: "Welche dieser Handlungen macht das Gebet ungültig?",
    },
    siklar: [
      {
        tr: "Rükûda tesbih duasını okumak",
        fr: "Réciter l’invocation de glorification pendant l’inclination (roukou’)",
        en: "Reciting the words of glorification during the bowing (ruku)",
        nl: "Tijdens de buiging (roekoe) de lofprijzing uitspreken",
        de: "Während der Verbeugung (Ruku) die Lobpreisung sprechen",
      },
      {
        tr: "Kıyamda Fâtiha sûresini okumak",
        fr: "Réciter la sourate Al-Fatiha en station debout (qiyam)",
        en: "Reciting Surah Al-Fatiha while standing (qiyam)",
        nl: "In staande houding (qiyam) soera Al-Fatiha reciteren",
        de: "Im Stehen (Qiyam) die Sure Al-Fatiha rezitieren",
      },
      {
        tr: "Namaz içinde başkasıyla konuşmak",
        fr: "Parler avec quelqu’un pendant la prière",
        en: "Speaking with someone during the prayer",
        nl: "Tijdens het gebed met iemand praten",
        de: "Während des Gebets mit jemandem sprechen",
      },
      {
        tr: "Secdeye giderken tekbir getirmek",
        fr: "Dire le takbir en allant à la prosternation (soujoud)",
        en: "Saying the takbir when going into prostration (sujud)",
        nl: "Bij het neergaan tot de prosternatie (soedjoed) de takbir zeggen",
        de: "Beim Niedergehen zur Niederwerfung (Sudschud) den Takbir sagen",
      },
    ],
    dogru: 2,
    kaynak: "TDV İslâm Ansiklopedisi, «Namaz» — https://islamansiklopedisi.org.tr/namaz (müfsidâtü’s-salât: «Abdestin bozulması, namazda konuşmak, … bir şey yiyip içmek, gülmek»)",
  },
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 2,
    id: 'nm12',
    soru: {
      tr: "Cemaatle namaz kılan bir kimse imama karşı nasıl davranır?",
      fr: "Lorsque vous priez en communauté (djama’a), comment vous comportez-vous vis-à-vis de l’imam ?",
      en: "When praying in congregation (jama’ah), how do you act with regard to the imam?",
      nl: "Hoe gedraagt iemand die in gemeenschap (djama’a) bidt zich tegenover de imam?",
      de: "Wie verhält sich jemand, der in Gemeinschaft (Dschama’a) betet, gegenüber dem Imam?",
    },
    siklar: [
      {
        tr: "İmamın önüne geçmeden durur ve hareketlerinde ona uyar",
        fr: "Vous vous placez sans dépasser l’imam et vous suivez ses mouvements",
        en: "You stand without going ahead of the imam and follow his movements",
        nl: "Men gaat niet vóór de imam staan en volgt zijn bewegingen",
        de: "Man stellt sich nicht vor den Imam und folgt seinen Bewegungen",
      },
      {
        tr: "İmamın önünde durur ve ondan önce rükûya gider",
        fr: "Vous vous placez devant l’imam et vous vous inclinez avant lui",
        en: "You stand in front of the imam and bow before he does",
        nl: "Men gaat vóór de imam staan en buigt eerder dan hij",
        de: "Man stellt sich vor den Imam und geht früher als er in die Verbeugung",
      },
      {
        tr: "İmamın yanında durur ve namazı kendi başına kılar",
        fr: "Vous vous placez à côté de l’imam et vous priez de votre côté",
        en: "You stand beside the imam and pray on your own",
        nl: "Men gaat naast de imam staan en bidt op zichzelf",
        de: "Man stellt sich neben den Imam und betet für sich allein",
      },
      {
        tr: "İmamdan önce selâm vererek namazdan çıkar",
        fr: "Vous terminez la prière par le salut avant l’imam",
        en: "You end the prayer with the salam before the imam",
        nl: "Men beëindigt het gebed met de slotgroet eerder dan de imam",
        de: "Man beendet das Gebet mit dem Schlussgruß früher als der Imam",
      },
    ],
    dogru: 0,
    kaynak: "TDV İslâm Ansiklopedisi, «İktidâ» — https://islamansiklopedisi.org.tr/iktida (imama uyma; imamın cemaatin önünde durması şarttır, «önüne geçilmesi veya aynı hizada durulması mekruhtur»)",
  },

  // ——— B3: kurs görmüş kişinin bildiği ayrıntı ———
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 3,
    id: 'nm13',
    soru: {
      tr: "Namazda yanılarak yapılan eksiklik veya fazlalığı telâfi etmek için namazın sonunda yapılan iki secdenin adı nedir?",
      fr: "Comment appelle-t-on les deux prosternations faites à la fin de la prière pour réparer un oubli ou un ajout involontaire ?",
      en: "What is the name of the two prostrations made at the end of the prayer to make up for an unintentional omission or addition?",
      nl: "Hoe heten de twee prosternaties aan het einde van het gebed die een onbedoelde weglating of toevoeging herstellen?",
      de: "Wie heißen die beiden Niederwerfungen am Ende des Gebets, die ein unbeabsichtigtes Auslassen oder Hinzufügen ausgleichen?",
    },
    siklar: [
      {
        tr: "Tilâvet secdesi",
        fr: "La prosternation de récitation (soujoud at-tilawa)",
        en: "The prostration of recitation (sujud al-tilawah)",
        nl: "De prosternatie van de recitatie (soedjoed at-tilawa)",
        de: "Die Niederwerfung der Rezitation (Sudschud at-Tilawa)",
      },
      {
        tr: "Sehiv secdesi",
        fr: "La prosternation d’oubli (soujoud as-sahw)",
        en: "The prostration of forgetfulness (sujud al-sahw)",
        nl: "De prosternatie van de vergetelheid (soedjoed as-sahw)",
        de: "Die Niederwerfung des Vergessens (Sudschud as-Sahw)",
      },
      {
        tr: "Şükür secdesi",
        fr: "La prosternation de gratitude (soujoud ach-choukr)",
        en: "The prostration of thankfulness (sujud al-shukr)",
        nl: "De prosternatie van de dankbaarheid (soedjoed asj-sjoekr)",
        de: "Die Niederwerfung der Dankbarkeit (Sudschud asch-Schukr)",
      },
      {
        tr: "Tesbih namazı",
        fr: "La prière de glorification (salât at-tasbih)",
        en: "The prayer of glorification (salat al-tasbih)",
        nl: "Het gebed van de lofprijzing (salat at-tasbih)",
        de: "Das Gebet der Lobpreisung (Salat at-Tasbih)",
      },
    ],
    dogru: 1,
    kaynak: "TDV İslâm Ansiklopedisi, «Sehiv secdesi» — https://islamansiklopedisi.org.tr/sehiv-secdesi",
  },
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 3,
    id: 'nm14',
    soru: {
      tr: "Yolculuk (seferîlik) hâlinde dört rekâtlı farz namazlar için tanınan kolaylık (ruhsat) nedir?",
      fr: "En voyage (safar), quelle facilité (roukhsa) est prévue pour les prières obligatoires de quatre rak’as ?",
      en: "While travelling (safar), what concession (rukhsah) applies to the four-rak’ah obligatory prayers?",
      nl: "Welke versoepeling (roechsa) geldt op reis (safar) voor de verplichte gebeden van vier rak’a’s?",
      de: "Welche Erleichterung (Ruchsa) gilt auf Reisen (Safar) für die Pflichtgebete mit vier Rak’as?",
    },
    siklar: [
      {
        tr: "Yolculuk boyunca bu namazlar tamamen düşer",
        fr: "Elles ne sont plus dues pendant tout le voyage",
        en: "They are dropped for the whole journey",
        nl: "Tijdens de hele reis vervallen deze gebeden volledig",
        de: "Während der ganzen Reise entfallen diese Gebete vollständig",
      },
      {
        tr: "Dönüşte kaza edilmek üzere ertelenir",
        fr: "Elles sont reportées et rattrapées au retour",
        en: "They are postponed and made up on return",
        nl: "Ze worden uitgesteld en na de terugkeer ingehaald",
        de: "Sie werden verschoben und nach der Rückkehr nachgeholt",
      },
      {
        tr: "Ayakta değil, oturarak kılınır",
        fr: "Elles s’accomplissent en position assise, non debout",
        en: "They are performed sitting, not standing",
        nl: "Ze worden zittend verricht in plaats van staand",
        de: "Sie werden im Sitzen statt im Stehen verrichtet",
      },
      {
        tr: "İki rekât olarak kısaltılıp kılınır",
        fr: "Elles se raccourcissent à deux rak’as",
        en: "They are shortened to two rak’ahs",
        nl: "Ze worden ingekort tot twee rak’a’s",
        de: "Sie werden auf zwei Rak’as verkürzt",
      },
    ],
    dogru: 3,
    kaynak: "TDV İslâm Ansiklopedisi, «Namaz» — https://islamansiklopedisi.org.tr/namaz («Yolculuk halinde bulunan kimse için dört rek’atlı namazların kısaltılması [kasr-ı salât] … ruhsat hükümleri söz konusudur»; Nisâ 4/101) ve «Sefer» — https://islamansiklopedisi.org.tr/sefer--fikih",
  },
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 3,
    id: 'nm15',
    soru: {
      tr: "Vakti içinde kılınamayan bir farz namazın sonradan kılınmasına ne ad verilir?",
      fr: "Comment appelle-t-on le fait d’accomplir plus tard une prière obligatoire qui n’a pas été faite dans son temps ?",
      en: "What is it called when an obligatory prayer missed in its time is performed later?",
      nl: "Hoe heet het later verrichten van een verplicht gebed dat niet binnen zijn tijd is verricht?",
      de: "Wie nennt man das spätere Verrichten eines Pflichtgebets, das nicht in seiner Zeit verrichtet wurde?",
    },
    siklar: [
      {
        tr: "Nâfile namaz",
        fr: "La prière surérogatoire (nafila)",
        en: "The voluntary prayer (nafilah)",
        nl: "Het vrijwillige gebed (nafila)",
        de: "Das freiwillige Gebet (Nafila)",
      },
      {
        tr: "Teheccüd namazı",
        fr: "La prière de nuit (tahajjoud)",
        en: "The night prayer (tahajjud)",
        nl: "Het nachtgebed (tahadjoed)",
        de: "Das Nachtgebet (Tahadschud)",
      },
      {
        tr: "Kaza namazı",
        fr: "La prière de rattrapage (qada)",
        en: "The make-up prayer (qada)",
        nl: "Het inhaalgebed (qada)",
        de: "Das Nachholgebet (Qada)",
      },
      {
        tr: "Tesbih namazı",
        fr: "La prière de glorification (salât at-tasbih)",
        en: "The prayer of glorification (salat al-tasbih)",
        nl: "Het gebed van de lofprijzing (salat at-tasbih)",
        de: "Das Gebet der Lobpreisung (Salat at-Tasbih)",
      },
    ],
    dogru: 2,
    kaynak: "TDV İslâm Ansiklopedisi, «Kazâ» — https://islamansiklopedisi.org.tr/kaza--ibadet (edâ / kazâ ayrımı)",
  },
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 3,
    id: 'nm16',
    soru: {
      tr: "Cenaze namazı nasıl kılınır?",
      fr: "Comment la prière funéraire (salât al-djanaza) est-elle accomplie ?",
      en: "How is the funeral prayer (salat al-janazah) performed?",
      nl: "Hoe wordt het gebed voor de overledene (salat al-djanaza) verricht?",
      de: "Wie wird das Totengebet (Salat al-Dschanaza) verrichtet?",
    },
    siklar: [
      {
        tr: "İki rekât hâlinde, rükû ve secde yapılarak",
        fr: "En deux rak’as, avec inclination (roukou’) et prosternation (soujoud)",
        en: "In two rak’ahs, with bowing (ruku) and prostration (sujud)",
        nl: "In twee rak’a’s, met buiging (roekoe) en prosternatie (soedjoed)",
        de: "In zwei Rak’as, mit Verbeugung (Ruku) und Niederwerfung (Sudschud)",
      },
      {
        tr: "Dört rekât hâlinde, oturarak",
        fr: "En quatre rak’as, en position assise",
        en: "In four rak’ahs, performed sitting down",
        nl: "In vier rak’a’s, in zittende houding",
        de: "In vier Rak’as, im Sitzen",
      },
      {
        tr: "Rükû yapılmadan, fakat secde yapılarak",
        fr: "Sans inclination (roukou’), mais avec prosternation (soujoud)",
        en: "Without bowing (ruku), but with prostration (sujud)",
        nl: "Zonder buiging (roekoe), maar met prosternatie (soedjoed)",
        de: "Ohne Verbeugung (Ruku), aber mit Niederwerfung (Sudschud)",
      },
      {
        tr: "Rükû ve secde yapılmadan, ayakta tekbirlerle",
        fr: "Sans inclination ni prosternation, debout, avec des takbirs",
        en: "Without bowing or prostration, standing, with takbirs",
        nl: "Zonder buiging en zonder prosternatie, staand, met takbirs",
        de: "Ohne Verbeugung und ohne Niederwerfung, im Stehen, mit Takbirs",
      },
    ],
    dogru: 3,
    kaynak: "Din İşleri Yüksek Kurulu, «Cenaze namazı nasıl kılınır?» — https://kurul.diyanet.gov.tr/tr/fetva/cenaze-namazi-nasil-kilinir/0193c42d-5ff0-7a8b-b744-96f510e9362a («Cenaze namazı rükû ve secdesi olmayan bir namazdır; rükünleri kıyam ve tekbirlerdir»)",
  },
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 3,
    id: 'nm17',
    mezhepBagli: true,
    soru: {
      tr: "Hanefî mezhebine göre abdestin farzları kaç tanedir?",
      fr: "Selon l’école hanafite, combien d’actes obligatoires (fard) comptent les ablutions (woudou) ?",
      en: "According to the Hanafi school, how many obligatory acts (fard) does the ablution (wudu) have?",
      nl: "Volgens de hanafitische rechtsschool: hoeveel verplichte handelingen (fard) telt de wudu (rituele wassing)?",
      de: "Nach der hanafitischen Rechtsschule: Wie viele Pflichthandlungen (Fard) hat die rituelle Waschung (Wudu)?",
    },
    siklar: [
      { tr: "İki", fr: "Deux", en: "Two", nl: "Twee", de: "Zwei" },
      { tr: "Üç", fr: "Trois", en: "Three", nl: "Drie", de: "Drei" },
      { tr: "Dört", fr: "Quatre", en: "Four", nl: "Vier", de: "Vier" },
      { tr: "Altı", fr: "Six", en: "Six", nl: "Zes", de: "Sechs" },
    ],
    dogru: 2,
    kaynak: "TDV İslâm Ansiklopedisi, «Abdest» — https://islamansiklopedisi.org.tr/abdest (Hanefîlere göre dört farz: yüz, kollar, başın meshi, ayaklar)",
  },
  {
    tur: 'bilgi',
    alan: 'namaz',
    basamak: 3,
    id: 'nm18',
    mezhepBagli: true,
    soru: {
      tr: "Hanefî mezhebine göre vitir namazının hükmü nedir?",
      fr: "Selon l’école hanafite, quel est le statut de la prière witr ?",
      en: "According to the Hanafi school, what is the ruling of the witr prayer?",
      nl: "Volgens de hanafitische rechtsschool: welk oordeel geldt voor het witr-gebed?",
      de: "Nach der hanafitischen Rechtsschule: Welchen Status hat das Witr-Gebet?",
    },
    siklar: [
      {
        tr: "Farzdır",
        fr: "Elle est obligatoire (fard)",
        en: "It is obligatory (fard)",
        nl: "Het is verplicht (fard)",
        de: "Es ist Pflicht (Fard)",
      },
      { tr: "Vâciptir", fr: "Elle est nécessaire (wadjib)", en: "It is necessary (wajib)", nl: "Het is noodzakelijk (wadjib)", de: "Es ist notwendig (Wadschib)" },
      { tr: "Sünnettir", fr: "Elle est une sunna", en: "It is a sunnah", nl: "Het is soenna", de: "Es ist Sunna" },
      {
        tr: "Nâfiledir",
        fr: "Elle est surérogatoire (nafila)",
        en: "It is voluntary (nafilah)",
        nl: "Het is vrijwillig (nafila)",
        de: "Es ist freiwillig (Nafila)",
      },
    ],
    dogru: 1,
    kaynak: "TDV İslâm Ansiklopedisi, «Vitir namazı» — https://islamansiklopedisi.org.tr/vitir-namazi (Ebû Hanîfe’ye göre vâcip, cumhura göre müekked sünnet)",
  },
];
