/** Seviye testi soru bankası — okuma: K1–K5 tanıma merdiveni (docs/SEVIYE-TESTI.md §5 kılavuzu).
 *
 *  Sesler yalnız resmî Diyanet kayıtlarıdır ve yereldedir: harf adları
 *  `/media/ses/elifba/<harfId>.mp3` (Elifbâ «1. Ders: Harfler ve İsimleri»), harekeler
 *  `/media/ses/elifba/{ustun,esre,otre}/<harfId>.mp3` («Harfler ve Sesleri» · «Kesra» · «Damme»),
 *  cezm ve şedde yalnız `src/data/elifba-alistirmalari.json` içindeki resmî metin–ses çiftleri.
 *  Harf ↔ dosya eşleşmesi `src/lib/elifba-verisi.ts` ve docs/OGRENCI-MODU-PORTAL.md §10 ile
 *  doğrulanmıştır. Âyet ve kelime metinleri kuran.diyanet.gov.tr mushafından birebir
 *  alınmış, yalnız durak işaretleri (U+06D9, U+06DA, U+06DC) çıkarılmıştır.
 */
import type { OkumaMaddesi } from '../tipler.ts';

export const OKUMA: OkumaMaddesi[] = [
  /* K1 · basamak 1 — harfleri tanıma (3 gör + 3 dinle) */
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 1,
    id: 'ok01',
    soru: {
      tr: 'Bu harfin adı nedir?',
      fr: 'Quel est le nom de cette lettre ?',
      en: 'What is the name of this letter?',
    },
    goster: 'م',
    siklar: [
      { tr: 'Elif', fr: 'Alif', en: 'Alif' },
      { tr: 'Vâv', fr: 'Waw', en: 'Waaw' },
      { tr: 'Mîm', fr: 'Mim', en: 'Meem' },
      { tr: 'Lâm', fr: 'Lam', en: 'Laam' },
    ],
    dogru: 2,
    kaynak: 'Diyanet Elifbâ portalı, kuran.diyanet.gov.tr/elifba — 1. Ders: Harfler ve İsimleri',
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 1,
    id: 'ok02',
    soru: {
      tr: 'Bu harfin adı nedir?',
      fr: 'Quel est le nom de cette lettre ?',
      en: 'What is the name of this letter?',
    },
    goster: 'ع',
    siklar: [
      { tr: 'Ayn', fr: 'Ayn', en: 'Ayn' },
      { tr: 'Fâ', fr: 'Fa', en: 'Faa' },
      { tr: 'Nûn', fr: 'Noun', en: 'Noon' },
      { tr: 'Cîm', fr: 'Jim', en: 'Jeem' },
    ],
    dogru: 0,
    kaynak: 'Diyanet Elifbâ portalı, kuran.diyanet.gov.tr/elifba — 1. Ders: Harfler ve İsimleri',
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 1,
    id: 'ok03',
    soru: {
      tr: 'Bu harfin adı nedir?',
      fr: 'Quel est le nom de cette lettre ?',
      en: 'What is the name of this letter?',
    },
    goster: 'ص',
    siklar: [
      { tr: 'Sîn', fr: 'Sin', en: 'Seen' },
      { tr: 'Tı', fr: 'Ta', en: 'Taa' },
      { tr: 'Dâd', fr: 'Dad', en: 'Daad' },
      { tr: 'Sâd', fr: 'Sad', en: 'Saad' },
    ],
    dogru: 3,
    kaynak: 'Diyanet Elifbâ portalı, kuran.diyanet.gov.tr/elifba — 1. Ders: Harfler ve İsimleri',
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 1,
    id: 'ok04',
    soru: {
      tr: 'Sesi dinleyin: hangi harf okunuyor?',
      fr: 'Écoutez : quelle lettre entendez-vous ?',
      en: 'Listen: which letter do you hear?',
    },
    ses: '/media/ses/elifba/se.mp3',
    siklar: [
      { ar: 'ب' },
      { ar: 'ث' },
      { ar: 'ت' },
      { ar: 'ن' },
    ],
    dogru: 1,
    kaynak: 'Diyanet Elifbâ portalı, kuran.diyanet.gov.tr/elifba — 1. Ders: Harfler ve İsimleri',
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 1,
    id: 'ok05',
    soru: {
      tr: 'Sesi dinleyin: hangi harf okunuyor?',
      fr: 'Écoutez : quelle lettre entendez-vous ?',
      en: 'Listen: which letter do you hear?',
    },
    ses: '/media/ses/elifba/zel.mp3',
    siklar: [
      { ar: 'د' },
      { ar: 'ر' },
      { ar: 'ذ' },
      { ar: 'ز' },
    ],
    dogru: 2,
    kaynak: 'Diyanet Elifbâ portalı, kuran.diyanet.gov.tr/elifba — 1. Ders: Harfler ve İsimleri',
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 1,
    id: 'ok06',
    soru: {
      tr: 'Sesi dinleyin: hangi harf okunuyor?',
      fr: 'Écoutez : quelle lettre entendez-vous ?',
      en: 'Listen: which letter do you hear?',
    },
    ses: '/media/ses/elifba/gayn.mp3',
    siklar: [
      { ar: 'ع' },
      { ar: 'غ' },
      { ar: 'ف' },
      { ar: 'ق' },
    ],
    dogru: 1,
    kaynak: 'Diyanet Elifbâ portalı, kuran.diyanet.gov.tr/elifba — 1. Ders: Harfler ve İsimleri',
  },
  /* K2 · basamak 2 — harfin başta, ortada ve sonda yazılışı (6 gör) */
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 2,
    id: 'ok07',
    soru: {
      tr: 'Bu, hangi harfin kelime başındaki yazılışıdır?',
      fr: 'De quelle lettre est-ce la forme initiale ?',
      en: 'This is the initial form of which letter?',
    },
    goster: 'بـ',
    siklar: [
      { ar: 'ت' },
      { ar: 'ن' },
      { ar: 'ي' },
      { ar: 'ب' },
    ],
    dogru: 3,
    kaynak: 'Diyanet Elifbâ portalı, kuran.diyanet.gov.tr/elifba — Harfler dersi',
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 2,
    id: 'ok08',
    soru: {
      tr: 'Bu, hangi harfin kelime ortasındaki yazılışıdır?',
      fr: 'De quelle lettre est-ce la forme médiane ?',
      en: 'This is the medial form of which letter?',
    },
    goster: 'ـهـ',
    siklar: [
      { ar: 'ه' },
      { ar: 'ح' },
      { ar: 'ع' },
      { ar: 'م' },
    ],
    dogru: 0,
    kaynak: 'Diyanet Elifbâ portalı, kuran.diyanet.gov.tr/elifba — Harfler dersi',
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 2,
    id: 'ok09',
    soru: {
      tr: 'Bu, hangi harfin kelime sonundaki yazılışıdır?',
      fr: 'De quelle lettre est-ce la forme finale ?',
      en: 'This is the final form of which letter?',
    },
    goster: 'ـش',
    siklar: [
      { ar: 'س' },
      { ar: 'ص' },
      { ar: 'ش' },
      { ar: 'ر' },
    ],
    dogru: 2,
    kaynak: 'Diyanet Elifbâ portalı, kuran.diyanet.gov.tr/elifba — Harfler dersi',
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 2,
    id: 'ok10',
    soru: {
      tr: 'Bu kelimede aşağıdaki harflerden hangisi vardır?',
      fr: 'Laquelle de ces lettres se trouve dans ce mot ?',
      en: 'Which of these letters appears in this word?',
    },
    goster: 'اَلْحَمْدُ',
    siklar: [
      { ar: 'ج' },
      { ar: 'خ' },
      { ar: 'ع' },
      { ar: 'ح' },
    ],
    dogru: 3,
    kaynak: "Kur'an-ı Kerim, Fâtiha 1:2 — kuran.diyanet.gov.tr",
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 2,
    id: 'ok11',
    soru: {
      tr: 'Bu kelimede hangi harf kendinden sonraki harfe bitişmez?',
      fr: 'Dans ce mot, quelle lettre ne se lie pas à la suivante ?',
      en: 'In this word, which letter does not join the next one?',
    },
    goster: 'مَالِكِ',
    siklar: [
      { ar: 'م' },
      { ar: 'ا' },
      { ar: 'ل' },
      { ar: 'ك' },
    ],
    dogru: 1,
    kaynak: "Kur'an-ı Kerim, Fâtiha 1:4 — kuran.diyanet.gov.tr",
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 2,
    id: 'ok12',
    soru: {
      tr: 'Gösterilen harf kendinden sonraki harfe bitişmez. Aşağıdaki harflerden hangisi de bitişmez?',
      fr: 'La lettre affichée ne se lie pas à la lettre suivante. Laquelle de ces lettres ne se lie pas non plus ?',
      en: 'The letter shown does not join the next letter. Which of these letters also does not join?',
    },
    goster: 'ر',
    siklar: [
      { ar: 'و' },
      { ar: 'ب' },
      { ar: 'ن' },
      { ar: 'ك' },
    ],
    dogru: 0,
    kaynak: 'Diyanet Elifbâ portalı, kuran.diyanet.gov.tr/elifba — Harfler dersi',
  },
  /* K3 · basamak 3 — harekeler (3 gör + 3 dinle) */
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 3,
    id: 'ok13',
    soru: {
      tr: 'Bu hece nasıl okunur?',
      fr: 'Comment lit-on cette syllabe ?',
      en: 'How is this syllable read?',
    },
    goster: 'بَ',
    siklar: [
      { tr: 'bi', fr: 'bi', en: 'bi' },
      { tr: 'bü', fr: 'bou', en: 'bu' },
      { tr: 'be', fr: 'ba', en: 'ba' },
    ],
    dogru: 2,
    kaynak: 'Diyanet Elifbâ portalı, kuran.diyanet.gov.tr/elifba — 2. Ders: Fetha',
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 3,
    id: 'ok14',
    soru: {
      tr: 'Bu hece nasıl okunur?',
      fr: 'Comment lit-on cette syllabe ?',
      en: 'How is this syllable read?',
    },
    goster: 'لِ',
    siklar: [
      { tr: 'le', fr: 'la', en: 'la' },
      { tr: 'li', fr: 'li', en: 'li' },
      { tr: 'lü', fr: 'lou', en: 'lu' },
    ],
    dogru: 1,
    kaynak: 'Diyanet Elifbâ portalı, kuran.diyanet.gov.tr/elifba — 5. Ders: Kesra',
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 3,
    id: 'ok15',
    soru: {
      tr: 'Bu hece nasıl okunur?',
      fr: 'Comment lit-on cette syllabe ?',
      en: 'How is this syllable read?',
    },
    goster: 'مُ',
    siklar: [
      { tr: 'me', fr: 'ma', en: 'ma' },
      { tr: 'mi', fr: 'mi', en: 'mi' },
      { tr: 'mü', fr: 'mou', en: 'mu' },
    ],
    dogru: 2,
    kaynak: 'Diyanet Elifbâ portalı, kuran.diyanet.gov.tr/elifba — 8. Ders: Damme',
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 3,
    id: 'ok16',
    soru: {
      tr: 'Sesi dinleyin: hangi hece okunuyor?',
      fr: 'Écoutez : quelle syllabe entendez-vous ?',
      en: 'Listen: which syllable do you hear?',
    },
    ses: '/media/ses/elifba/ustun/be.mp3',
    siklar: [
      { ar: 'بَ' },
      { ar: 'بِ' },
      { ar: 'بُ' },
    ],
    dogru: 0,
    kaynak: 'Diyanet Elifbâ portalı, kuran.diyanet.gov.tr/elifba — 1. Ders: Harfler ve Sesleri',
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 3,
    id: 'ok17',
    soru: {
      tr: 'Sesi dinleyin: hangi hece okunuyor?',
      fr: 'Écoutez : quelle syllabe entendez-vous ?',
      en: 'Listen: which syllable do you hear?',
    },
    ses: '/media/ses/elifba/esre/mim.mp3',
    siklar: [
      { ar: 'مَ' },
      { ar: 'مِ' },
      { ar: 'مُ' },
    ],
    dogru: 1,
    kaynak: 'Diyanet Elifbâ portalı, kuran.diyanet.gov.tr/elifba — 5. Ders: Kesra',
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 3,
    id: 'ok18',
    soru: {
      tr: 'Sesi dinleyin: hangi hece okunuyor?',
      fr: 'Écoutez : quelle syllabe entendez-vous ?',
      en: 'Listen: which syllable do you hear?',
    },
    ses: '/media/ses/elifba/otre/nun.mp3',
    siklar: [
      { ar: 'بُ' },
      { ar: 'تُ' },
      { ar: 'مُ' },
      { ar: 'نُ' },
    ],
    dogru: 3,
    kaynak: 'Diyanet Elifbâ portalı, kuran.diyanet.gov.tr/elifba — 8. Ders: Damme',
  },
  /* K4 · basamak 4 — cezm, şedde, tenvin ve med (3 gör + 3 dinle) */
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 4,
    id: 'ok19',
    soru: {
      tr: 'Durmadan devam edilerek okunduğunda bu kelime nasıl okunur?',
      fr: 'Comment lit-on ce mot lorsqu’on poursuit la lecture sans s’arrêter ?',
      en: 'How is this word read when the reading continues without stopping?',
    },
    goster: 'اَحَدٌ',
    siklar: [
      { tr: 'ehaden', fr: 'ahadan', en: 'ahadan' },
      { tr: 'ehadin', fr: 'ahadin', en: 'ahadin' },
      { tr: 'ehadün', fr: 'ahadoun', en: 'ahadun' },
      { tr: 'ehadü', fr: 'ahadou', en: 'ahadu' },
    ],
    dogru: 2,
    kaynak: "Kur'an-ı Kerim, İhlâs 112:4 — kuran.diyanet.gov.tr",
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 4,
    id: 'ok20',
    soru: {
      tr: 'Bu kelimede sesi uzatan (med) harf hangisidir?',
      fr: 'Quelle lettre allonge le son (madd) dans ce mot ?',
      en: 'Which letter lengthens the sound (madd) in this word?',
    },
    goster: 'يُولَدْ',
    siklar: [
      { ar: 'ي' },
      { ar: 'و' },
      { ar: 'ل' },
      { ar: 'د' },
    ],
    dogru: 1,
    kaynak: "Kur'an-ı Kerim, İhlâs 112:3 — kuran.diyanet.gov.tr",
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 4,
    id: 'ok21',
    soru: {
      tr: 'Bu kelime nasıl okunur?',
      fr: 'Comment lit-on ce mot ?',
      en: 'How is this word read?',
    },
    goster: 'قُلْ',
    siklar: [
      { tr: 'kule', fr: 'qoula', en: 'qula' },
      { tr: 'kulü', fr: 'qoulou', en: 'qulu' },
      { tr: 'kuli', fr: 'qouli', en: 'quli' },
      { tr: 'kul', fr: 'qoul', en: 'qul' },
    ],
    dogru: 3,
    kaynak: "Kur'an-ı Kerim, İhlâs 112:1 — kuran.diyanet.gov.tr",
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 4,
    id: 'ok22',
    soru: {
      tr: 'Sesi dinleyin: hangi yazılış okunuyor?',
      fr: 'Écoutez : quelle graphie entendez-vous ?',
      en: 'Listen: which spelling do you hear?',
    },
    ses: '/media/ses/elifba/cezm/8.mp3',
    siklar: [
      { ar: 'فَقْ' },
      { ar: 'مُتْ' },
      { ar: 'قَدْ' },
      { ar: 'عُذْ' },
    ],
    dogru: 2,
    kaynak: 'https://kuran.diyanet.gov.tr/elifba/templates/dersler/eb/cezm/kavrama.html',
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 4,
    id: 'ok23',
    soru: {
      tr: 'Sesi dinleyin: hangi kelime okunuyor?',
      fr: 'Écoutez : quel mot entendez-vous ?',
      en: 'Listen: which word do you hear?',
    },
    ses: '/media/ses/elifba/sedde/2.mp3',
    siklar: [
      { ar: 'عَدَّ' },
      { ar: 'مِمَّا' },
      { ar: 'كُلٌّ' },
      { ar: 'تَبَّتْ' },
    ],
    dogru: 0,
    kaynak: 'https://kuran.diyanet.gov.tr/elifba/templates/dersler/eb/sedde/uygulama.html',
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 4,
    id: 'ok24',
    soru: {
      tr: 'Sesi dinleyin: hangi kelime okunuyor?',
      fr: 'Écoutez : quel mot entendez-vous ?',
      en: 'Listen: which word do you hear?',
    },
    ses: '/media/ses/elifba/sedde/8.mp3',
    siklar: [
      { ar: 'تَوَّابًا' },
      { ar: 'مُسْتَقَرٌّ' },
      { ar: 'يَمُدُّهُمْ' },
      { ar: 'يُكَذِّبُ' },
    ],
    dogru: 3,
    kaynak: 'https://kuran.diyanet.gov.tr/elifba/templates/dersler/eb/sedde/uygulama.html',
  },
  /* K5 · basamak 5 — kelime ve âyet (6 gör) */
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 5,
    id: 'ok25',
    soru: {
      tr: 'Bu kelime nasıl okunur?',
      fr: 'Comment lit-on ce mot ?',
      en: 'How is this word read?',
    },
    goster: 'اَللّٰهُ',
    siklar: [
      { tr: 'Allâhü', fr: 'Allâhou', en: 'Allahu' },
      { tr: 'ilâhü', fr: 'ilâhou', en: 'ilahu' },
      { tr: 'lillâhi', fr: 'lillâhi', en: 'lillahi' },
    ],
    dogru: 0,
    kaynak: "Kur'an-ı Kerim, İhlâs 112:2 — kuran.diyanet.gov.tr",
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 5,
    id: 'ok26',
    soru: {
      tr: 'Bu kelime nasıl okunur?',
      fr: 'Comment lit-on ce mot ?',
      en: 'How is this word read?',
    },
    goster: 'الصَّمَدُ',
    siklar: [
      { tr: 'el-samedü', fr: 'al-samadou', en: 'al-samadu' },
      { tr: 'es-sâmidü', fr: 'as-sâmidou', en: 'as-samidu' },
      { tr: 'es-samedü', fr: 'as-samadou', en: 'as-samadu' },
    ],
    dogru: 2,
    kaynak: "Kur'an-ı Kerim, İhlâs 112:2 — kuran.diyanet.gov.tr",
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 5,
    id: 'ok27',
    soru: {
      tr: 'Bu âyet nasıl okunur?',
      fr: 'Comment lit-on ce verset ?',
      en: 'How is this verse read?',
    },
    goster: 'اَلْحَمْدُ لِلّٰهِ رَبِّ الْعَالَمٖينَ',
    siklar: [
      { tr: "Mâliki yevmi'd-dîn", fr: 'Mâliki yawmi-d-dîn', en: 'Maliki yawmi-d-din' },
      { tr: "Elhamdü lillâhi Rabbi'l-âlemîn", fr: 'Alhamdou lillâhi Rabbi-l-âlamîn', en: 'Alhamdu lillahi Rabbi-l-alamin' },
      { tr: "İyyâke na'büdü ve iyyâke nesteîn", fr: "Iyyâka na'boudou wa iyyâka nasta'în", en: "Iyyaka na'budu wa iyyaka nasta'in" },
      { tr: "Er-rahmâni'r-rahîm", fr: 'Ar-rahmâni-r-rahîm', en: 'Ar-rahmani-r-raheem' },
    ],
    dogru: 1,
    kaynak: "Kur'an-ı Kerim, Fâtiha 1:2 — kuran.diyanet.gov.tr",
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 5,
    id: 'ok28',
    soru: {
      tr: 'Bu âyet nasıl okunur?',
      fr: 'Comment lit-on ce verset ?',
      en: 'How is this verse read?',
    },
    goster: 'قُلْ هُوَ اللّٰهُ اَحَدٌ',
    siklar: [
      { tr: "Allâhü's-samed", fr: 'Allâhou-s-samad', en: 'Allahu-s-samad' },
      { tr: 'Lem yelid ve lem yûled', fr: 'Lam yalid wa lam yoûlad', en: 'Lam yalid wa lam yulad' },
      { tr: "Kul eûzü bi-Rabbi'l-felak", fr: "Qoul a'oûdhou bi-Rabbi-l-falaq", en: "Qul a'udhu bi-Rabbi-l-falaq" },
      { tr: 'Kul hüvellâhü ehad', fr: 'Qoul houwa-llâhou ahad', en: 'Qul huwa-llahu ahad' },
    ],
    dogru: 3,
    kaynak: "Kur'an-ı Kerim, İhlâs 112:1 — kuran.diyanet.gov.tr",
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 5,
    id: 'ok29',
    soru: {
      tr: 'Bu âyet nasıl okunur?',
      fr: 'Comment lit-on ce verset ?',
      en: 'How is this verse read?',
    },
    goster: 'اِهْدِنَا الصِّرَاطَ الْمُسْتَقٖيمَ',
    siklar: [
      { tr: "İhdine's-sırâta'l-müstakîm", fr: 'Ihdina-s-sirâta-l-moustaqîm', en: 'Ihdina-s-sirata-l-mustaqim' },
      { tr: "Elhamdü lillâhi Rabbi'l-âlemîn", fr: 'Alhamdou lillâhi Rabbi-l-âlamîn', en: 'Alhamdu lillahi Rabbi-l-alamin' },
      { tr: "Mâliki yevmi'd-dîn", fr: 'Mâliki yawmi-d-dîn', en: 'Maliki yawmi-d-din' },
      { tr: "İyyâke na'büdü ve iyyâke nesteîn", fr: "Iyyâka na'boudou wa iyyâka nasta'în", en: "Iyyaka na'budu wa iyyaka nasta'in" },
    ],
    dogru: 0,
    kaynak: "Kur'an-ı Kerim, Fâtiha 1:6 — kuran.diyanet.gov.tr",
  },
  {
    tur: 'okuma',
    alan: 'okuma',
    basamak: 5,
    id: 'ok30',
    soru: {
      tr: 'Bu âyetin sonunda durarak okuduğunuzda son kelime nasıl okunur?',
      fr: 'Lorsque vous vous arrêtez à la fin de ce verset, comment se lit le dernier mot ?',
      en: 'When you stop at the end of this verse, how is the last word read?',
    },
    goster: 'اَلرَّحْمٰنِ الرَّحٖيمِ',
    siklar: [
      { tr: 'er-rahîmi', fr: 'ar-rahîmi', en: 'ar-raheemi' },
      { tr: 'er-rahîm', fr: 'ar-rahîm', en: 'ar-raheem' },
      { tr: 'er-rahîmü', fr: 'ar-rahîmou', en: 'ar-raheemu' },
      { tr: 'er-rahîmin', fr: 'ar-rahîmin', en: 'ar-raheemin' },
    ],
    dogru: 1,
    kaynak: "Kur'an-ı Kerim, Fâtiha 1:3 — kuran.diyanet.gov.tr",
  },
];
