/** Seviye testi soru bankası — siyer (docs/SEVIYE-TESTI.md §5 soru yazım kılavuzu).
 *
 *  12 madde: B1 4 · B2 4 · B3 4. Yalnız üzerinde ittifak edilen bilgiler soruldu; tartışmalı
 *  tarih ve sayılar dışarıda bırakıldı. Kaynaklar madde başına `kaynak` alanındadır (TDV İslâm
 *  Ansiklopedisi ve Diyanet Kur’an portalı). B3’te hıristiyan geçmişli katılımcılar için önceki
 *  peygamberlerle ilgili iki madde vardır; üslup başka inançları küçültmeyecek biçimde kurulmuştur.
 */
import type { BilgiMaddesi } from '../tipler.ts';

export const SIYER: BilgiMaddesi[] = [
  {
    tur: 'bilgi',
    alan: 'siyer',
    basamak: 1,
    id: 'sy01',
    soru: {
      tr: 'Hz. Muhammed (s.a.s.) hangi şehirde dünyaya gelmiştir?',
      fr: 'Dans quelle ville le Prophète Muhammad (paix et salut sur lui) est-il né ?',
      en: 'In which city was Prophet Muhammad (peace be upon him) born?',
      nl: 'In welke stad is de Profeet Mohammed (vrede zij met hem) geboren?',
      de: 'In welcher Stadt wurde der Prophet Muhammad (Friede sei mit ihm) geboren?',
    },
    siklar: [
      { tr: 'Medine’de', fr: 'À Médine', en: 'In Medina', nl: 'In Medina', de: 'In Medina' },
      { tr: 'Mekke’de', fr: 'À La Mecque', en: 'In Mecca', nl: 'In Mekka', de: 'In Mekka' },
      { tr: 'Kudüs’te', fr: 'À Jérusalem', en: 'In Jerusalem', nl: 'In Jeruzalem', de: 'In Jerusalem' },
      { tr: 'Tâif’te', fr: 'À Tâ’if', en: 'In Ta’if', nl: 'In Taif', de: 'In Taif' },
    ],
    dogru: 1,
    kaynak: 'TDV İslâm Ansiklopedisi, «Muhammed» — islamansiklopedisi.org.tr/muhammed',
  },
  {
    tur: 'bilgi',
    alan: 'siyer',
    basamak: 1,
    id: 'sy02',
    soru: {
      tr: 'Hz. Muhammed’e (s.a.s.) ilk vahiy nerede gelmiştir?',
      fr: 'Où le Prophète Muhammad (paix et salut sur lui) a-t-il reçu la première révélation (wahy) ?',
      en: 'Where did Prophet Muhammad (peace be upon him) receive the first revelation (wahy)?',
      nl: 'Waar heeft de Profeet Mohammed (vrede zij met hem) de eerste openbaring (wahy) ontvangen?',
      de: 'Wo hat der Prophet Muhammad (Friede sei mit ihm) die erste Offenbarung (Wahy) empfangen?',
    },
    siklar: [
      {
        tr: 'Mekke yakınındaki Hira mağarasında',
        fr: 'Dans la grotte de Hirâ, près de La Mecque',
        en: 'In the cave of Hirâ, near Mecca',
        nl: 'In de grot van Hira, bij Mekka',
        de: 'In der Höhle Hira, bei Mekka',
      },
      {
        tr: 'Medine’deki Mescid-i Nebevî’de',
        fr: 'Dans la mosquée du Prophète, à Médine',
        en: 'In the Prophet’s Mosque, in Medina',
        nl: 'In de Moskee van de Profeet, in Medina',
        de: 'In der Prophetenmoschee, in Medina',
      },
      {
        tr: 'Kudüs’teki Mescid-i Aksâ’da',
        fr: 'Dans la mosquée al-Aqsâ, à Jérusalem',
        en: 'In the al-Aqsâ Mosque, in Jerusalem',
        nl: 'In de al-Aqsa-moskee, in Jeruzalem',
        de: 'In der al-Aqsa-Moschee, in Jerusalem',
      },
      {
        tr: 'Mekke’deki Kâbe’nin içinde',
        fr: 'À l’intérieur de la Kaaba, à La Mecque',
        en: 'Inside the Kaaba, in Mecca',
        nl: 'Binnen in de Kaaba, in Mekka',
        de: 'Im Inneren der Kaaba, in Mekka',
      },
    ],
    dogru: 0,
    kaynak: 'TDV İslâm Ansiklopedisi, «Hira» — islamansiklopedisi.org.tr/hira',
  },
  {
    tur: 'bilgi',
    alan: 'siyer',
    basamak: 1,
    id: 'sy03',
    soru: {
      tr: 'Hicret, Hz. Peygamber’in ve müslümanların hangi şehirden hangi şehre göç etmesidir?',
      fr: 'L’hégire (hidjra) est l’émigration du Prophète et des musulmans de quelle ville vers quelle ville ?',
      en: 'The Hijra is the migration of the Prophet and the Muslims from which city to which city?',
      nl: 'De hidjra is de emigratie van de Profeet en de moslims van welke stad naar welke stad?',
      de: 'Die Hidschra ist die Auswanderung des Propheten und der Muslime von welcher Stadt in welche Stadt?',
    },
    siklar: [
      {
        tr: 'Medine’den Mekke’ye',
        fr: 'De Médine vers La Mecque',
        en: 'From Medina to Mecca',
        nl: 'Van Medina naar Mekka',
        de: 'Von Medina nach Mekka',
      },
      {
        tr: 'Mekke’den Kudüs’e',
        fr: 'De La Mecque vers Jérusalem',
        en: 'From Mecca to Jerusalem',
        nl: 'Van Mekka naar Jeruzalem',
        de: 'Von Mekka nach Jerusalem',
      },
      {
        tr: 'Mekke’den Medine’ye',
        fr: 'De La Mecque vers Médine',
        en: 'From Mecca to Medina',
        nl: 'Van Mekka naar Medina',
        de: 'Von Mekka nach Medina',
      },
      {
        tr: 'Tâif’ten Mekke’ye',
        fr: 'De Tâ’if vers La Mecque',
        en: 'From Ta’if to Mecca',
        nl: 'Van Taif naar Mekka',
        de: 'Von Taif nach Mekka',
      },
    ],
    dogru: 2,
    kaynak: 'TDV İslâm Ansiklopedisi, «Hicret» — islamansiklopedisi.org.tr/hicret',
  },
  {
    tur: 'bilgi',
    alan: 'siyer',
    basamak: 1,
    id: 'sy04',
    soru: {
      tr: 'Mekkeliler, peygamberlikten önce Hz. Muhammed’e (s.a.s.) niçin «el-Emîn (güvenilir)» derlerdi?',
      fr: 'Pourquoi les Mecquois appelaient-ils le Prophète Muhammad (paix et salut sur lui) « al-Amîn » (le digne de confiance) avant sa mission prophétique ?',
      en: 'Why did the people of Mecca call Prophet Muhammad (peace be upon him) “al-Amîn” (the trustworthy) before his prophethood?',
      nl: 'Waarom noemden de Mekkanen de Profeet Mohammed (vrede zij met hem) vóór zijn profeetschap “al-Amîn” (de betrouwbare)?',
      de: 'Warum nannten die Mekkaner den Propheten Muhammad (Friede sei mit ihm) vor seiner Prophetenschaft „al-Amîn“ (der Vertrauenswürdige)?',
    },
    siklar: [
      {
        tr: 'Kureyş kabilesinin en zengin tüccarı olduğu için',
        fr: 'Parce qu’il était le marchand le plus riche de la tribu de Quraych',
        en: 'Because he was the wealthiest merchant of the Quraysh tribe',
        nl: 'Omdat hij de rijkste koopman van de stam Quraysh was',
        de: 'Weil er der reichste Kaufmann des Stammes Quraisch war',
      },
      {
        tr: 'Kâbe’nin bakımıyla görevlendirilmiş olduğu için',
        fr: 'Parce qu’il avait été chargé de l’entretien de la Kaaba',
        en: 'Because he had been put in charge of looking after the Kaaba',
        nl: 'Omdat hij belast was met het onderhoud van de Kaaba',
        de: 'Weil er mit der Pflege der Kaaba betraut war',
      },
      {
        tr: 'Okuma yazma bilen sayılı kişilerden biri olduğu için',
        fr: 'Parce qu’il était l’un des rares à savoir lire et écrire',
        en: 'Because he was one of the few people who could read and write',
        nl: 'Omdat hij een van de weinigen was die konden lezen en schrijven',
        de: 'Weil er einer der wenigen war, die lesen und schreiben konnten',
      },
      {
        tr: 'Sözünde ve ticaretinde son derece güvenilir olduğu için',
        fr: 'Parce qu’il était d’une fiabilité exemplaire dans sa parole et son commerce',
        en: 'Because he was utterly reliable in his word and in his trade',
        nl: 'Omdat hij in zijn woord en in zijn handel uiterst betrouwbaar was',
        de: 'Weil er in seinem Wort und in seinem Handel überaus vertrauenswürdig war',
      },
    ],
    dogru: 3,
    kaynak: 'TDV İslâm Ansiklopedisi, «Muhammed» — islamansiklopedisi.org.tr/muhammed',
  },
  {
    tur: 'bilgi',
    alan: 'siyer',
    basamak: 2,
    id: 'sy05',
    soru: {
      tr: 'Hicret hangi milâdî yılda gerçekleşmiş ve hicrî takvimin başlangıcı olmuştur?',
      fr: 'En quelle année de l’ère chrétienne l’hégire a-t-elle eu lieu, marquant le début du calendrier hégirien ?',
      en: 'In which year CE did the Hijra take place, marking the beginning of the Hijri calendar?',
      nl: 'In welk jaar na Christus vond de hidjra plaats, waarmee de islamitische kalender begint?',
      de: 'In welchem Jahr nach Christus fand die Hidschra statt, mit der der islamische Kalender beginnt?',
    },
    siklar: [
      { tr: '610 yılında', fr: 'En 610', en: 'In 610', nl: 'In 610', de: 'Im Jahr 610' },
      { tr: '622 yılında', fr: 'En 622', en: 'In 622', nl: 'In 622', de: 'Im Jahr 622' },
      { tr: '630 yılında', fr: 'En 630', en: 'In 630', nl: 'In 630', de: 'Im Jahr 630' },
      { tr: '632 yılında', fr: 'En 632', en: 'In 632', nl: 'In 632', de: 'Im Jahr 632' },
    ],
    dogru: 1,
    kaynak: 'TDV İslâm Ansiklopedisi, «Hicret» — islamansiklopedisi.org.tr/hicret',
  },
  {
    tur: 'bilgi',
    alan: 'siyer',
    basamak: 2,
    id: 'sy06',
    soru: {
      tr: 'Hz. Peygamber’in ilk hanımı ve kendisine ilk iman eden kişi kimdir?',
      fr: 'Qui fut la première épouse du Prophète et la première personne à croire en lui ?',
      en: 'Who was the Prophet’s first wife and the first person to believe in him?',
      nl: 'Wie was de eerste echtgenote van de Profeet en de eerste die in hem geloofde?',
      de: 'Wer war die erste Ehefrau des Propheten und der erste Mensch, der an ihn glaubte?',
    },
    siklar: [
      { tr: 'Hz. Âişe', fr: 'Aïcha', en: 'Aishah', nl: 'Aisha', de: 'Aischa' },
      { tr: 'Hz. Hafsa', fr: 'Hafsa', en: 'Hafsah', nl: 'Hafsa', de: 'Hafsa' },
      { tr: 'Hz. Hatice', fr: 'Khadîdja', en: 'Khadijah', nl: 'Khadidja', de: 'Chadidscha' },
      { tr: 'Hz. Ümmü Seleme', fr: 'Oumm Salama', en: 'Umm Salamah', nl: 'Oemm Salama', de: 'Umm Salama' },
    ],
    dogru: 2,
    kaynak: 'TDV İslâm Ansiklopedisi, «Hatice» — islamansiklopedisi.org.tr/hatice',
  },
  {
    tur: 'bilgi',
    alan: 'siyer',
    basamak: 2,
    id: 'sy07',
    soru: {
      tr: 'İslâm’ın ilk müezzini olan sahâbî kimdir?',
      fr: 'Quel Compagnon fut le premier muezzin de l’islam ?',
      en: 'Which Companion was the first muezzin of Islam?',
      nl: 'Welke metgezel was de eerste muezzin van de islam?',
      de: 'Welcher Gefährte war der erste Muezzin des Islams?',
    },
    siklar: [
      { tr: 'Selmân-ı Fârisî', fr: 'Salmân al-Fârisî', en: 'Salman al-Farisi', nl: 'Salman al-Farisi', de: 'Salman al-Farisi' },
      { tr: 'Zeyd b. Hârise', fr: 'Zayd ibn Hâritha', en: 'Zayd ibn Harithah', nl: 'Zayd ibn Haritha', de: 'Zaid ibn Haritha' },
      { tr: 'Abdullah b. Mes‘ûd', fr: 'Abdallah ibn Mas‘oûd', en: 'Abdullah ibn Mas‘ud', nl: 'Abdallah ibn Mas‘oed', de: 'Abdullah ibn Mas‘ud' },
      { tr: 'Bilâl-i Habeşî', fr: 'Bilâl al-Habachî', en: 'Bilal al-Habashi', nl: 'Bilal al-Habasji', de: 'Bilal al-Habaschi' },
    ],
    dogru: 3,
    kaynak: 'TDV İslâm Ansiklopedisi, «Bilâl-i Habeşî» — islamansiklopedisi.org.tr/bilal-i-habesi',
  },
  {
    tur: 'bilgi',
    alan: 'siyer',
    basamak: 2,
    id: 'sy08',
    soru: {
      tr: 'Hz. Peygamber, hicretten sonra Mekke’den gelen muhacirlerle Medineli ensar arasında neyi kurmuştur?',
      fr: 'Après l’hégire, qu’a institué le Prophète entre les émigrés venus de La Mecque (mouhâdjiroûn) et leurs hôtes médinois (ansâr) ?',
      en: 'After the Hijra, what did the Prophet establish between the emigrants from Mecca (muhajirun) and their Medinan hosts (ansar)?',
      nl: 'Wat heeft de Profeet na de hidjra ingesteld tussen de uitgeweken Mekkanen (moehadjiroen) en hun Medinese gastheren (ansar)?',
      de: 'Was hat der Prophet nach der Hidschra zwischen den aus Mekka ausgewanderten Muslimen (Muhadschirun) und ihren medinensischen Gastgebern (Ansar) gestiftet?',
    },
    siklar: [
      {
        tr: 'Onları karşılıklı olarak kardeş ilân eden kardeşlik bağını (muâhât)',
        fr: 'Un pacte de fraternité (mou’âkhât) les déclarant frères les uns des autres',
        en: 'A bond of brotherhood (mu’akhat) declaring them brothers of one another',
        nl: 'Een band van broederschap (moe‘akhaat) die hen tot elkaars broeders verklaarde',
        de: 'Einen Bund der Brüderlichkeit (Mu‘achat), der sie zu Brüdern füreinander erklärte',
      },
      {
        tr: 'Muhacirler için ayrı bir mahalle ve ayrı bir pazar düzenini',
        fr: 'Un quartier séparé et un marché propre aux émigrés',
        en: 'A separate quarter and a separate market for the emigrants',
        nl: 'Een aparte wijk en een eigen markt voor de uitgewekenen',
        de: 'Ein eigenes Viertel und einen eigenen Markt für die Ausgewanderten',
      },
      {
        tr: 'Ensarın mallarının yarısını hazineye bağışlaması kuralını',
        fr: 'La règle imposant aux Médinois de céder la moitié de leurs biens',
        en: 'A rule requiring the Medinans to give up half of their property',
        nl: 'De regel dat de Medinezen de helft van hun bezit moesten afstaan',
        de: 'Die Regel, dass die Medinenser die Hälfte ihres Besitzes abgeben mussten',
      },
      {
        tr: 'Mekke’ye geri dönecekler için ayrı bir kafile düzenini',
        fr: 'Une organisation de caravanes pour ceux qui rentreraient à La Mecque',
        en: 'A caravan system for those who would return to Mecca',
        nl: 'Een karavaanregeling voor wie naar Mekka zou terugkeren',
        de: 'Eine Karawanenordnung für diejenigen, die nach Mekka zurückkehren würden',
      },
    ],
    dogru: 0,
    kaynak:
      'TDV İslâm Ansiklopedisi, «Muâhât»: «Hz. Peygamber’in Medine’de ensar ve muhacirlerden bazılarını birbirleriyle kardeş ilân etmesi» — islamansiklopedisi.org.tr/muahat',
  },
  {
    tur: 'bilgi',
    alan: 'siyer',
    basamak: 3,
    id: 'sy09',
    soru: {
      tr: 'Hudeybiye Antlaşması’nın niteliği nedir?',
      fr: 'Quelle était la nature du traité de Houdaybiya ?',
      en: 'What was the nature of the Treaty of Hudaybiyah?',
      nl: 'Wat was de aard van het Verdrag van Hoedaybiya?',
      de: 'Welcher Art war der Vertrag von Hudaibiya?',
    },
    siklar: [
      {
        tr: 'Bizans imparatoruyla yapılan bir ticaret ve geçiş antlaşmasıdır',
        fr: 'Un accord de commerce et de passage conclu avec l’empereur byzantin',
        en: 'A trade and transit agreement made with the Byzantine emperor',
        nl: 'Een handels- en doorgangsakkoord met de Byzantijnse keizer',
        de: 'Ein Handels- und Durchreiseabkommen mit dem byzantinischen Kaiser',
      },
      {
        tr: 'Mekkeli müşriklerle yapılan, on yıl sürmesi kararlaştırılan barış antlaşmasıdır',
        fr: 'Un traité de paix de dix ans conclu avec les polythéistes de La Mecque',
        en: 'A ten-year peace treaty concluded with the polytheists of Mecca',
        nl: 'Een vredesverdrag van tien jaar met de polytheïsten van Mekka',
        de: 'Ein Friedensvertrag über zehn Jahre mit den Polytheisten von Mekka',
      },
      {
        tr: 'Medineli kabilelerle yapılan bir ortak savunma sözleşmesidir',
        fr: 'Un pacte de défense commune conclu avec les tribus de Médine',
        en: 'A joint defence pact concluded with the tribes of Medina',
        nl: 'Een gezamenlijk verdedigingspact met de stammen van Medina',
        de: 'Ein gemeinsamer Verteidigungspakt mit den Stämmen von Medina',
      },
      {
        tr: 'Tâif halkıyla yapılan, hac yollarını güvenceye alan bir sözleşmedir',
        fr: 'Un accord avec les habitants de Tâ’if garantissant les routes du pèlerinage',
        en: 'An agreement with the people of Ta’if securing the pilgrimage routes',
        nl: 'Een akkoord met de inwoners van Taif dat de bedevaartwegen veiligstelde',
        de: 'Ein Abkommen mit den Einwohnern von Taif, das die Pilgerwege sicherte',
      },
    ],
    dogru: 1,
    kaynak: 'TDV İslâm Ansiklopedisi, «Hudeybiye Antlaşması» — islamansiklopedisi.org.tr/hudeybiye-antlasmasi',
  },
  {
    tur: 'bilgi',
    alan: 'siyer',
    basamak: 3,
    id: 'sy10',
    soru: {
      tr: 'Vedâ Hutbesi’nde Hz. Peygamber’in bildirdiği temel ilkelerden biri nedir?',
      fr: 'Quel est l’un des principes fondamentaux énoncés par le Prophète dans le Sermon d’adieu ?',
      en: 'What is one of the core principles the Prophet declared in the Farewell Sermon?',
      nl: 'Wat is een van de grondbeginselen die de Profeet in de Afscheidspreek heeft verkondigd?',
      de: 'Welches ist einer der Grundsätze, die der Prophet in der Abschiedspredigt verkündet hat?',
    },
    siklar: [
      {
        tr: 'Müslümanların yılda bir kez Mekke’ye gitmekle yükümlü olduğu',
        fr: 'Que les musulmans doivent se rendre à La Mecque une fois par an',
        en: 'That Muslims must travel to Mecca once every year',
        nl: 'Dat moslims eenmaal per jaar naar Mekka moeten reizen',
        de: 'Dass Muslime einmal im Jahr nach Mekka reisen müssen',
      },
      {
        tr: 'Yalnız Arapça bilenlerin Kur’an-ı Kerim’i okuyabileceği',
        fr: 'Que seuls ceux qui connaissent l’arabe peuvent lire le Coran',
        en: 'That only those who know Arabic may read the Qur’an',
        nl: 'Dat alleen wie Arabisch kent de Koran mag lezen',
        de: 'Dass nur diejenigen den Koran lesen dürfen, die Arabisch können',
      },
      {
        tr: 'İnsanların can ve mallarının dokunulmaz olduğu, üstünlüğün ancak takvâ ile olduğu',
        fr: 'Que la vie et les biens sont inviolables et que la supériorité ne tient qu’à la piété (taqwâ)',
        en: 'That people’s lives and property are inviolable and that superiority lies only in piety (taqwa)',
        nl: 'Dat leven en bezit onschendbaar zijn en dat voorrang alleen in godsvrees (taqwa) ligt',
        de: 'Dass Leben und Besitz unantastbar sind und Vorrang allein in der Gottesfurcht (Taqwa) liegt',
      },
      {
        tr: 'Ticaretin yalnız Medine pazarında yapılabileceği',
        fr: 'Que le commerce ne peut se faire qu’au marché de Médine',
        en: 'That trade may be carried on only in the market of Medina',
        nl: 'Dat handel alleen op de markt van Medina mag plaatsvinden',
        de: 'Dass Handel nur auf dem Markt von Medina getrieben werden darf',
      },
    ],
    dogru: 2,
    kaynak: 'TDV İslâm Ansiklopedisi, «Vedâ hutbesi» — islamansiklopedisi.org.tr/veda-hutbesi',
  },
  {
    tur: 'bilgi',
    alan: 'siyer',
    basamak: 3,
    id: 'sy11',
    soru: {
      tr: 'Kur’an-ı Kerim’e göre Kâbe’nin temellerini kim, kiminle birlikte yükseltmiştir?',
      fr: 'Selon le Coran, qui a élevé les fondations de la Kaaba, et avec qui ?',
      en: 'According to the Qur’an, who raised the foundations of the Kaaba, and with whom?',
      nl: 'Wie heeft volgens de Koran de fundamenten van de Kaaba opgetrokken, en met wie?',
      de: 'Wer hat dem Koran zufolge die Fundamente der Kaaba errichtet, und mit wem?',
    },
    siklar: [
      {
        tr: 'Hz. Âdem, oğlu Hz. Şît ile birlikte',
        fr: 'Adam, avec son fils Seth (Chîth)',
        en: 'Adam, together with his son Seth (Shîth)',
        nl: 'Adam, samen met zijn zoon Seth (Sjith)',
        de: 'Adam, zusammen mit seinem Sohn Seth (Schith)',
      },
      {
        tr: 'Hz. Nûh, oğullarıyla birlikte',
        fr: 'Noé (Noûh), avec ses fils',
        en: 'Noah (Nûh), together with his sons',
        nl: 'Noeh (Noach), samen met zijn zonen',
        de: 'Nuh (Noah), zusammen mit seinen Söhnen',
      },
      {
        tr: 'Hz. Mûsâ, kardeşi Hz. Hârûn ile birlikte',
        fr: 'Moïse (Mûsâ), avec son frère Aaron (Hârûn)',
        en: 'Moses (Mûsâ), together with his brother Aaron (Hârûn)',
        nl: 'Moesa (Mozes), samen met zijn broer Haroen (Aäron)',
        de: 'Musa (Mose), zusammen mit seinem Bruder Harun (Aaron)',
      },
      {
        tr: 'Hz. İbrâhim, oğlu Hz. İsmâil ile birlikte',
        fr: 'Abraham (Ibrâhîm), avec son fils Ismaël (Ismâ‘îl)',
        en: 'Abraham (Ibrâhîm), together with his son Ishmael (Ismâ‘îl)',
        nl: 'Ibrahim (Abraham), samen met zijn zoon Ismaïl (Ismaël)',
        de: 'Ibrahim (Abraham), zusammen mit seinem Sohn Ismail (Ismael)',
      },
    ],
    dogru: 3,
    kaynak:
      'Diyanet Kur’an portalı, Bakara sûresi 2/127 («Hani İbrahim, İsmail ile birlikte evin (Kâbe’nin) temellerini yükseltiyor») — kuran.diyanet.gov.tr/mushaf/kuran-meal-2/bakara-suresi-2/ayet-127/diyanet-isleri-baskanligi-meali-1',
  },
  {
    tur: 'bilgi',
    alan: 'siyer',
    basamak: 3,
    id: 'sy12',
    soru: {
      tr: 'İslâm inancına göre Hz. Îsâ kimdir?',
      fr: 'Selon la foi musulmane, qui est Jésus (Îsâ) ?',
      en: 'According to Islamic belief, who is Jesus (Îsâ)?',
      nl: 'Wie is Isa (Jezus) volgens het islamitische geloof?',
      de: 'Wer ist Isa (Jesus) nach islamischem Glauben?',
    },
    siklar: [
      {
        tr: 'Allah’ın kulu ve insanlara gönderdiği peygamberlerden biridir',
        fr: 'Il est un serviteur d’Allah et l’un des prophètes envoyés aux hommes',
        en: 'He is a servant of Allah and one of the prophets sent to humankind',
        nl: 'Hij is een dienaar van Allah en een van de profeten die naar de mensen zijn gezonden',
        de: 'Er ist ein Diener Allahs und einer der Propheten, die zu den Menschen gesandt wurden',
      },
      {
        tr: 'Peygamber değil, ahlâkı güzel bir öğretmen ve bilgedir',
        fr: 'Il n’est pas prophète, mais un sage et un maître de bonne morale',
        en: 'He is not a prophet, but a sage and a teacher of good character',
        nl: 'Hij is geen profeet, maar een wijze en een leraar van goede zeden',
        de: 'Er ist kein Prophet, sondern ein Weiser und ein Lehrer guter Sitten',
      },
      {
        tr: 'Kendisine hiçbir ilâhî kitap verilmemiş bir peygamberdir',
        fr: 'C’est un prophète à qui aucun Livre n’a été révélé',
        en: 'He is a prophet to whom no divine Book was revealed',
        nl: 'Hij is een profeet aan wie geen enkel goddelijk Boek is geopenbaard',
        de: 'Er ist ein Prophet, dem kein göttliches Buch offenbart wurde',
      },
      {
        tr: 'Adı Kur’an-ı Kerim’de geçmeyen bir din büyüğüdür',
        fr: 'C’est une grande figure religieuse dont le Coran ne parle pas',
        en: 'He is a great religious figure not mentioned in the Qur’an',
        nl: 'Hij is een grote religieuze figuur over wie de Koran niet spreekt',
        de: 'Er ist eine große religiöse Gestalt, von der der Koran nicht spricht',
      },
    ],
    dogru: 0,
    kaynak:
      'TDV İslâm Ansiklopedisi, «Îsâ»: «Kur’an’da adı geçen ve kendisine kutsal kitap İncil verilen peygamber» — islamansiklopedisi.org.tr/isa',
  },
];
